// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chat

import (
	"answer/kitex_service/chat_service/kitex_gen/chat"
	"context"
	"errors"

	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newChatChatArgs,
		newChatChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChatHis": kitex.NewMethodInfo(
		chatHisHandler,
		newChatChatHisArgs,
		newChatChatHisResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	chatServiceInfo                = NewServiceInfo()
	chatServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Chat"
	handlerType := (*chat.Chat)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatChatArgs)
	realResult := result.(*chat.ChatChatResult)
	success, err := handler.(chat.Chat).Chat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatChatArgs() interface{} {
	return chat.NewChatChatArgs()
}

func newChatChatResult() interface{} {
	return chat.NewChatChatResult()
}

func chatHisHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatChatHisArgs)
	realResult := result.(*chat.ChatChatHisResult)
	success, err := handler.(chat.Chat).ChatHis(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatChatHisArgs() interface{} {
	return chat.NewChatChatHisArgs()
}

func newChatChatHisResult() interface{} {
	return chat.NewChatChatHisResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Chat(ctx context.Context, req *chat.ChatReq) (r *chat.ChatRes, err error) {
	var _args chat.ChatChatArgs
	_args.Req = req
	var _result chat.ChatChatResult
	if err = p.c.Call(ctx, "Chat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChatHis(ctx context.Context, req *chat.ChatHistory) (r *chat.ChatHistoryRes, err error) {
	var _args chat.ChatChatHisArgs
	_args.Req = req
	var _result chat.ChatChatHisResult
	if err = p.c.Call(ctx, "ChatHis", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
