// Code generated by Kitex v0.16.2. DO NOT EDIT.

package chatservice

import (
	"context"
	"errors"
	chat "github.com/Airiseina/answer/kitex_service/chat_service/kitex_gen/chat"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newChatServiceSendMessageArgs,
		newChatServiceSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHistory": kitex.NewMethodInfo(
		getHistoryHandler,
		newChatServiceGetHistoryArgs,
		newChatServiceGetHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateConversation": kitex.NewMethodInfo(
		createConversationHandler,
		newChatServiceCreateConversationArgs,
		newChatServiceCreateConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetConversations": kitex.NewMethodInfo(
		getConversationsHandler,
		newChatServiceGetConversationsArgs,
		newChatServiceGetConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetOnline": kitex.NewMethodInfo(
		setOnlineHandler,
		newChatServiceSetOnlineArgs,
		newChatServiceSetOnlineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetOffline": kitex.NewMethodInfo(
		setOfflineHandler,
		newChatServiceSetOfflineArgs,
		newChatServiceSetOfflineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RenewOnline": kitex.NewMethodInfo(
		renewOnlineHandler,
		newChatServiceRenewOnlineArgs,
		newChatServiceRenewOnlineResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOnlineStatus": kitex.NewMethodInfo(
		getOnlineStatusHandler,
		newChatServiceGetOnlineStatusArgs,
		newChatServiceGetOnlineStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddConversationMembers": kitex.NewMethodInfo(
		addConversationMembersHandler,
		newChatServiceAddConversationMembersArgs,
		newChatServiceAddConversationMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveConversationMembers": kitex.NewMethodInfo(
		removeConversationMembersHandler,
		newChatServiceRemoveConversationMembersArgs,
		newChatServiceRemoveConversationMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteConversation": kitex.NewMethodInfo(
		deleteConversationHandler,
		newChatServiceDeleteConversationArgs,
		newChatServiceDeleteConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkRead": kitex.NewMethodInfo(
		markReadHandler,
		newChatServiceMarkReadArgs,
		newChatServiceMarkReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetConversationMembers": kitex.NewMethodInfo(
		getConversationMembersHandler,
		newChatServiceGetConversationMembersArgs,
		newChatServiceGetConversationMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrCreatePrivateConversation": kitex.NewMethodInfo(
		getOrCreatePrivateConversationHandler,
		newChatServiceGetOrCreatePrivateConversationArgs,
		newChatServiceGetOrCreatePrivateConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecallMessage": kitex.NewMethodInfo(
		recallMessageHandler,
		newChatServiceRecallMessageArgs,
		newChatServiceRecallMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditMessage": kitex.NewMethodInfo(
		editMessageHandler,
		newChatServiceEditMessageArgs,
		newChatServiceEditMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetEditHistory": kitex.NewMethodInfo(
		getEditHistoryHandler,
		newChatServiceGetEditHistoryArgs,
		newChatServiceGetEditHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SyncMessages": kitex.NewMethodInfo(
		syncMessagesHandler,
		newChatServiceSyncMessagesArgs,
		newChatServiceSyncMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchColdMessages": kitex.NewMethodInfo(
		searchColdMessagesHandler,
		newChatServiceSearchColdMessagesArgs,
		newChatServiceSearchColdMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	chatServiceServiceInfo                = NewServiceInfo()
	chatServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*chat.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSendMessageArgs)
	realResult := result.(*chat.ChatServiceSendMessageResult)
	success, err := handler.(chat.ChatService).SendMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSendMessageArgs() interface{} {
	return chat.NewChatServiceSendMessageArgs()
}

func newChatServiceSendMessageResult() interface{} {
	return chat.NewChatServiceSendMessageResult()
}

func getHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetHistoryArgs)
	realResult := result.(*chat.ChatServiceGetHistoryResult)
	success, err := handler.(chat.ChatService).GetHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetHistoryArgs() interface{} {
	return chat.NewChatServiceGetHistoryArgs()
}

func newChatServiceGetHistoryResult() interface{} {
	return chat.NewChatServiceGetHistoryResult()
}

func createConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceCreateConversationArgs)
	realResult := result.(*chat.ChatServiceCreateConversationResult)
	success, err := handler.(chat.ChatService).CreateConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceCreateConversationArgs() interface{} {
	return chat.NewChatServiceCreateConversationArgs()
}

func newChatServiceCreateConversationResult() interface{} {
	return chat.NewChatServiceCreateConversationResult()
}

func getConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetConversationsArgs)
	realResult := result.(*chat.ChatServiceGetConversationsResult)
	success, err := handler.(chat.ChatService).GetConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetConversationsArgs() interface{} {
	return chat.NewChatServiceGetConversationsArgs()
}

func newChatServiceGetConversationsResult() interface{} {
	return chat.NewChatServiceGetConversationsResult()
}

func setOnlineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSetOnlineArgs)
	realResult := result.(*chat.ChatServiceSetOnlineResult)
	success, err := handler.(chat.ChatService).SetOnline(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSetOnlineArgs() interface{} {
	return chat.NewChatServiceSetOnlineArgs()
}

func newChatServiceSetOnlineResult() interface{} {
	return chat.NewChatServiceSetOnlineResult()
}

func setOfflineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSetOfflineArgs)
	realResult := result.(*chat.ChatServiceSetOfflineResult)
	success, err := handler.(chat.ChatService).SetOffline(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSetOfflineArgs() interface{} {
	return chat.NewChatServiceSetOfflineArgs()
}

func newChatServiceSetOfflineResult() interface{} {
	return chat.NewChatServiceSetOfflineResult()
}

func renewOnlineHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRenewOnlineArgs)
	realResult := result.(*chat.ChatServiceRenewOnlineResult)
	success, err := handler.(chat.ChatService).RenewOnline(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRenewOnlineArgs() interface{} {
	return chat.NewChatServiceRenewOnlineArgs()
}

func newChatServiceRenewOnlineResult() interface{} {
	return chat.NewChatServiceRenewOnlineResult()
}

func getOnlineStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetOnlineStatusArgs)
	realResult := result.(*chat.ChatServiceGetOnlineStatusResult)
	success, err := handler.(chat.ChatService).GetOnlineStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetOnlineStatusArgs() interface{} {
	return chat.NewChatServiceGetOnlineStatusArgs()
}

func newChatServiceGetOnlineStatusResult() interface{} {
	return chat.NewChatServiceGetOnlineStatusResult()
}

func addConversationMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceAddConversationMembersArgs)
	realResult := result.(*chat.ChatServiceAddConversationMembersResult)
	success, err := handler.(chat.ChatService).AddConversationMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceAddConversationMembersArgs() interface{} {
	return chat.NewChatServiceAddConversationMembersArgs()
}

func newChatServiceAddConversationMembersResult() interface{} {
	return chat.NewChatServiceAddConversationMembersResult()
}

func removeConversationMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRemoveConversationMembersArgs)
	realResult := result.(*chat.ChatServiceRemoveConversationMembersResult)
	success, err := handler.(chat.ChatService).RemoveConversationMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRemoveConversationMembersArgs() interface{} {
	return chat.NewChatServiceRemoveConversationMembersArgs()
}

func newChatServiceRemoveConversationMembersResult() interface{} {
	return chat.NewChatServiceRemoveConversationMembersResult()
}

func deleteConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceDeleteConversationArgs)
	realResult := result.(*chat.ChatServiceDeleteConversationResult)
	success, err := handler.(chat.ChatService).DeleteConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceDeleteConversationArgs() interface{} {
	return chat.NewChatServiceDeleteConversationArgs()
}

func newChatServiceDeleteConversationResult() interface{} {
	return chat.NewChatServiceDeleteConversationResult()
}

func markReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceMarkReadArgs)
	realResult := result.(*chat.ChatServiceMarkReadResult)
	success, err := handler.(chat.ChatService).MarkRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceMarkReadArgs() interface{} {
	return chat.NewChatServiceMarkReadArgs()
}

func newChatServiceMarkReadResult() interface{} {
	return chat.NewChatServiceMarkReadResult()
}

func getConversationMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetConversationMembersArgs)
	realResult := result.(*chat.ChatServiceGetConversationMembersResult)
	success, err := handler.(chat.ChatService).GetConversationMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetConversationMembersArgs() interface{} {
	return chat.NewChatServiceGetConversationMembersArgs()
}

func newChatServiceGetConversationMembersResult() interface{} {
	return chat.NewChatServiceGetConversationMembersResult()
}

func getOrCreatePrivateConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetOrCreatePrivateConversationArgs)
	realResult := result.(*chat.ChatServiceGetOrCreatePrivateConversationResult)
	success, err := handler.(chat.ChatService).GetOrCreatePrivateConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetOrCreatePrivateConversationArgs() interface{} {
	return chat.NewChatServiceGetOrCreatePrivateConversationArgs()
}

func newChatServiceGetOrCreatePrivateConversationResult() interface{} {
	return chat.NewChatServiceGetOrCreatePrivateConversationResult()
}

func recallMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceRecallMessageArgs)
	realResult := result.(*chat.ChatServiceRecallMessageResult)
	success, err := handler.(chat.ChatService).RecallMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceRecallMessageArgs() interface{} {
	return chat.NewChatServiceRecallMessageArgs()
}

func newChatServiceRecallMessageResult() interface{} {
	return chat.NewChatServiceRecallMessageResult()
}

func editMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceEditMessageArgs)
	realResult := result.(*chat.ChatServiceEditMessageResult)
	success, err := handler.(chat.ChatService).EditMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceEditMessageArgs() interface{} {
	return chat.NewChatServiceEditMessageArgs()
}

func newChatServiceEditMessageResult() interface{} {
	return chat.NewChatServiceEditMessageResult()
}

func getEditHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetEditHistoryArgs)
	realResult := result.(*chat.ChatServiceGetEditHistoryResult)
	success, err := handler.(chat.ChatService).GetEditHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetEditHistoryArgs() interface{} {
	return chat.NewChatServiceGetEditHistoryArgs()
}

func newChatServiceGetEditHistoryResult() interface{} {
	return chat.NewChatServiceGetEditHistoryResult()
}

func syncMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSyncMessagesArgs)
	realResult := result.(*chat.ChatServiceSyncMessagesResult)
	success, err := handler.(chat.ChatService).SyncMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSyncMessagesArgs() interface{} {
	return chat.NewChatServiceSyncMessagesArgs()
}

func newChatServiceSyncMessagesResult() interface{} {
	return chat.NewChatServiceSyncMessagesResult()
}

func searchColdMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceSearchColdMessagesArgs)
	realResult := result.(*chat.ChatServiceSearchColdMessagesResult)
	success, err := handler.(chat.ChatService).SearchColdMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceSearchColdMessagesArgs() interface{} {
	return chat.NewChatServiceSearchColdMessagesArgs()
}

func newChatServiceSearchColdMessagesResult() interface{} {
	return chat.NewChatServiceSearchColdMessagesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessage(ctx context.Context, req *chat.SendMessageReq) (r *chat.SendMessageRes, err error) {
	var _args chat.ChatServiceSendMessageArgs
	_args.Req = req
	var _result chat.ChatServiceSendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHistory(ctx context.Context, req *chat.GetHistoryReq) (r *chat.GetHistoryRes, err error) {
	var _args chat.ChatServiceGetHistoryArgs
	_args.Req = req
	var _result chat.ChatServiceGetHistoryResult
	if err = p.c.Call(ctx, "GetHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateConversation(ctx context.Context, req *chat.CreateConversationReq) (r *chat.CreateConversationRes, err error) {
	var _args chat.ChatServiceCreateConversationArgs
	_args.Req = req
	var _result chat.ChatServiceCreateConversationResult
	if err = p.c.Call(ctx, "CreateConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversations(ctx context.Context, req *chat.GetConversationsReq) (r *chat.GetConversationsRes, err error) {
	var _args chat.ChatServiceGetConversationsArgs
	_args.Req = req
	var _result chat.ChatServiceGetConversationsResult
	if err = p.c.Call(ctx, "GetConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetOnline(ctx context.Context, req *chat.SetOnlineReq) (r *chat.CommonRes, err error) {
	var _args chat.ChatServiceSetOnlineArgs
	_args.Req = req
	var _result chat.ChatServiceSetOnlineResult
	if err = p.c.Call(ctx, "SetOnline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetOffline(ctx context.Context, req *chat.SetOfflineReq) (r *chat.CommonRes, err error) {
	var _args chat.ChatServiceSetOfflineArgs
	_args.Req = req
	var _result chat.ChatServiceSetOfflineResult
	if err = p.c.Call(ctx, "SetOffline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RenewOnline(ctx context.Context, req *chat.RenewOnlineReq) (r *chat.CommonRes, err error) {
	var _args chat.ChatServiceRenewOnlineArgs
	_args.Req = req
	var _result chat.ChatServiceRenewOnlineResult
	if err = p.c.Call(ctx, "RenewOnline", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOnlineStatus(ctx context.Context, req *chat.GetOnlineStatusReq) (r *chat.GetOnlineStatusRes, err error) {
	var _args chat.ChatServiceGetOnlineStatusArgs
	_args.Req = req
	var _result chat.ChatServiceGetOnlineStatusResult
	if err = p.c.Call(ctx, "GetOnlineStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddConversationMembers(ctx context.Context, req *chat.AddConversationMembersReq) (r *chat.AddConversationMembersRes, err error) {
	var _args chat.ChatServiceAddConversationMembersArgs
	_args.Req = req
	var _result chat.ChatServiceAddConversationMembersResult
	if err = p.c.Call(ctx, "AddConversationMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveConversationMembers(ctx context.Context, req *chat.RemoveConversationMembersReq) (r *chat.RemoveConversationMembersRes, err error) {
	var _args chat.ChatServiceRemoveConversationMembersArgs
	_args.Req = req
	var _result chat.ChatServiceRemoveConversationMembersResult
	if err = p.c.Call(ctx, "RemoveConversationMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteConversation(ctx context.Context, req *chat.DeleteConversationReq) (r *chat.DeleteConversationRes, err error) {
	var _args chat.ChatServiceDeleteConversationArgs
	_args.Req = req
	var _result chat.ChatServiceDeleteConversationResult
	if err = p.c.Call(ctx, "DeleteConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkRead(ctx context.Context, req *chat.MarkReadReq) (r *chat.MarkReadRes, err error) {
	var _args chat.ChatServiceMarkReadArgs
	_args.Req = req
	var _result chat.ChatServiceMarkReadResult
	if err = p.c.Call(ctx, "MarkRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConversationMembers(ctx context.Context, req *chat.GetConversationMembersReq) (r *chat.GetConversationMembersRes, err error) {
	var _args chat.ChatServiceGetConversationMembersArgs
	_args.Req = req
	var _result chat.ChatServiceGetConversationMembersResult
	if err = p.c.Call(ctx, "GetConversationMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrCreatePrivateConversation(ctx context.Context, req *chat.GetOrCreatePrivateConversationReq) (r *chat.GetOrCreatePrivateConversationRes, err error) {
	var _args chat.ChatServiceGetOrCreatePrivateConversationArgs
	_args.Req = req
	var _result chat.ChatServiceGetOrCreatePrivateConversationResult
	if err = p.c.Call(ctx, "GetOrCreatePrivateConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecallMessage(ctx context.Context, req *chat.RecallMessageReq) (r *chat.RecallMessageRes, err error) {
	var _args chat.ChatServiceRecallMessageArgs
	_args.Req = req
	var _result chat.ChatServiceRecallMessageResult
	if err = p.c.Call(ctx, "RecallMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditMessage(ctx context.Context, req *chat.EditMessageReq) (r *chat.EditMessageRes, err error) {
	var _args chat.ChatServiceEditMessageArgs
	_args.Req = req
	var _result chat.ChatServiceEditMessageResult
	if err = p.c.Call(ctx, "EditMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetEditHistory(ctx context.Context, req *chat.GetEditHistoryReq) (r *chat.GetEditHistoryRes, err error) {
	var _args chat.ChatServiceGetEditHistoryArgs
	_args.Req = req
	var _result chat.ChatServiceGetEditHistoryResult
	if err = p.c.Call(ctx, "GetEditHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SyncMessages(ctx context.Context, req *chat.SyncMessagesReq) (r *chat.SyncMessagesRes, err error) {
	var _args chat.ChatServiceSyncMessagesArgs
	_args.Req = req
	var _result chat.ChatServiceSyncMessagesResult
	if err = p.c.Call(ctx, "SyncMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchColdMessages(ctx context.Context, req *chat.SearchColdMessagesReq) (r *chat.SearchColdMessagesRes, err error) {
	var _args chat.ChatServiceSearchColdMessagesArgs
	_args.Req = req
	var _result chat.ChatServiceSearchColdMessagesResult
	if err = p.c.Call(ctx, "SearchColdMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
