// Code generated by Kitex v0.16.2. DO NOT EDIT.

package chatservice

import (
	"context"
	chat "github.com/Airiseina/answer/kitex_service/chat_service/kitex_gen/chat"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, req *chat.SendMessageReq, callOptions ...callopt.Option) (r *chat.SendMessageRes, err error)
	GetHistory(ctx context.Context, req *chat.GetHistoryReq, callOptions ...callopt.Option) (r *chat.GetHistoryRes, err error)
	CreateConversation(ctx context.Context, req *chat.CreateConversationReq, callOptions ...callopt.Option) (r *chat.CreateConversationRes, err error)
	GetConversations(ctx context.Context, req *chat.GetConversationsReq, callOptions ...callopt.Option) (r *chat.GetConversationsRes, err error)
	SetOnline(ctx context.Context, req *chat.SetOnlineReq, callOptions ...callopt.Option) (r *chat.CommonRes, err error)
	SetOffline(ctx context.Context, req *chat.SetOfflineReq, callOptions ...callopt.Option) (r *chat.CommonRes, err error)
	RenewOnline(ctx context.Context, req *chat.RenewOnlineReq, callOptions ...callopt.Option) (r *chat.CommonRes, err error)
	GetOnlineStatus(ctx context.Context, req *chat.GetOnlineStatusReq, callOptions ...callopt.Option) (r *chat.GetOnlineStatusRes, err error)
	AddConversationMembers(ctx context.Context, req *chat.AddConversationMembersReq, callOptions ...callopt.Option) (r *chat.AddConversationMembersRes, err error)
	RemoveConversationMembers(ctx context.Context, req *chat.RemoveConversationMembersReq, callOptions ...callopt.Option) (r *chat.RemoveConversationMembersRes, err error)
	DeleteConversation(ctx context.Context, req *chat.DeleteConversationReq, callOptions ...callopt.Option) (r *chat.DeleteConversationRes, err error)
	MarkRead(ctx context.Context, req *chat.MarkReadReq, callOptions ...callopt.Option) (r *chat.MarkReadRes, err error)
	GetConversationMembers(ctx context.Context, req *chat.GetConversationMembersReq, callOptions ...callopt.Option) (r *chat.GetConversationMembersRes, err error)
	GetOrCreatePrivateConversation(ctx context.Context, req *chat.GetOrCreatePrivateConversationReq, callOptions ...callopt.Option) (r *chat.GetOrCreatePrivateConversationRes, err error)
	RecallMessage(ctx context.Context, req *chat.RecallMessageReq, callOptions ...callopt.Option) (r *chat.RecallMessageRes, err error)
	EditMessage(ctx context.Context, req *chat.EditMessageReq, callOptions ...callopt.Option) (r *chat.EditMessageRes, err error)
	GetEditHistory(ctx context.Context, req *chat.GetEditHistoryReq, callOptions ...callopt.Option) (r *chat.GetEditHistoryRes, err error)
	SyncMessages(ctx context.Context, req *chat.SyncMessagesReq, callOptions ...callopt.Option) (r *chat.SyncMessagesRes, err error)
	SearchColdMessages(ctx context.Context, req *chat.SearchColdMessagesReq, callOptions ...callopt.Option) (r *chat.SearchColdMessagesRes, err error)
	SearchMessages(ctx context.Context, req *chat.SearchMessagesReq, callOptions ...callopt.Option) (r *chat.SearchMessagesRes, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) SendMessage(ctx context.Context, req *chat.SendMessageReq, callOptions ...callopt.Option) (r *chat.SendMessageRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, req)
}

func (p *kChatServiceClient) GetHistory(ctx context.Context, req *chat.GetHistoryReq, callOptions ...callopt.Option) (r *chat.GetHistoryRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHistory(ctx, req)
}

func (p *kChatServiceClient) CreateConversation(ctx context.Context, req *chat.CreateConversationReq, callOptions ...callopt.Option) (r *chat.CreateConversationRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateConversation(ctx, req)
}

func (p *kChatServiceClient) GetConversations(ctx context.Context, req *chat.GetConversationsReq, callOptions ...callopt.Option) (r *chat.GetConversationsRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversations(ctx, req)
}

func (p *kChatServiceClient) SetOnline(ctx context.Context, req *chat.SetOnlineReq, callOptions ...callopt.Option) (r *chat.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetOnline(ctx, req)
}

func (p *kChatServiceClient) SetOffline(ctx context.Context, req *chat.SetOfflineReq, callOptions ...callopt.Option) (r *chat.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetOffline(ctx, req)
}

func (p *kChatServiceClient) RenewOnline(ctx context.Context, req *chat.RenewOnlineReq, callOptions ...callopt.Option) (r *chat.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RenewOnline(ctx, req)
}

func (p *kChatServiceClient) GetOnlineStatus(ctx context.Context, req *chat.GetOnlineStatusReq, callOptions ...callopt.Option) (r *chat.GetOnlineStatusRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOnlineStatus(ctx, req)
}

func (p *kChatServiceClient) AddConversationMembers(ctx context.Context, req *chat.AddConversationMembersReq, callOptions ...callopt.Option) (r *chat.AddConversationMembersRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddConversationMembers(ctx, req)
}

func (p *kChatServiceClient) RemoveConversationMembers(ctx context.Context, req *chat.RemoveConversationMembersReq, callOptions ...callopt.Option) (r *chat.RemoveConversationMembersRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveConversationMembers(ctx, req)
}

func (p *kChatServiceClient) DeleteConversation(ctx context.Context, req *chat.DeleteConversationReq, callOptions ...callopt.Option) (r *chat.DeleteConversationRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteConversation(ctx, req)
}

func (p *kChatServiceClient) MarkRead(ctx context.Context, req *chat.MarkReadReq, callOptions ...callopt.Option) (r *chat.MarkReadRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkRead(ctx, req)
}

func (p *kChatServiceClient) GetConversationMembers(ctx context.Context, req *chat.GetConversationMembersReq, callOptions ...callopt.Option) (r *chat.GetConversationMembersRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConversationMembers(ctx, req)
}

func (p *kChatServiceClient) GetOrCreatePrivateConversation(ctx context.Context, req *chat.GetOrCreatePrivateConversationReq, callOptions ...callopt.Option) (r *chat.GetOrCreatePrivateConversationRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrCreatePrivateConversation(ctx, req)
}

func (p *kChatServiceClient) RecallMessage(ctx context.Context, req *chat.RecallMessageReq, callOptions ...callopt.Option) (r *chat.RecallMessageRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RecallMessage(ctx, req)
}

func (p *kChatServiceClient) EditMessage(ctx context.Context, req *chat.EditMessageReq, callOptions ...callopt.Option) (r *chat.EditMessageRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EditMessage(ctx, req)
}

func (p *kChatServiceClient) GetEditHistory(ctx context.Context, req *chat.GetEditHistoryReq, callOptions ...callopt.Option) (r *chat.GetEditHistoryRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetEditHistory(ctx, req)
}

func (p *kChatServiceClient) SyncMessages(ctx context.Context, req *chat.SyncMessagesReq, callOptions ...callopt.Option) (r *chat.SyncMessagesRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SyncMessages(ctx, req)
}

func (p *kChatServiceClient) SearchColdMessages(ctx context.Context, req *chat.SearchColdMessagesReq, callOptions ...callopt.Option) (r *chat.SearchColdMessagesRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchColdMessages(ctx, req)
}

func (p *kChatServiceClient) SearchMessages(ctx context.Context, req *chat.SearchMessagesReq, callOptions ...callopt.Option) (r *chat.SearchMessagesRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchMessages(ctx, req)
}
