// Code generated by Kitex v0.16.2. DO NOT EDIT.

package groupservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	group "group_service/kitex_gen/group"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newGroupServiceCreateGroupArgs,
		newGroupServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InviteMembers": kitex.NewMethodInfo(
		inviteMembersHandler,
		newGroupServiceInviteMembersArgs,
		newGroupServiceInviteMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"KickMembers": kitex.NewMethodInfo(
		kickMembersHandler,
		newGroupServiceKickMembersArgs,
		newGroupServiceKickMembersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupInfo": kitex.NewMethodInfo(
		getGroupInfoHandler,
		newGroupServiceGetGroupInfoArgs,
		newGroupServiceGetGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeOwner": kitex.NewMethodInfo(
		changeOwnerHandler,
		newGroupServiceChangeOwnerArgs,
		newGroupServiceChangeOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeNotice": kitex.NewMethodInfo(
		changeNoticeHandler,
		newGroupServiceChangeNoticeArgs,
		newGroupServiceChangeNoticeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Muted": kitex.NewMethodInfo(
		mutedHandler,
		newGroupServiceMutedArgs,
		newGroupServiceMutedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetAdmin": kitex.NewMethodInfo(
		setAdminHandler,
		newGroupServiceSetAdminArgs,
		newGroupServiceSetAdminResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserGroups": kitex.NewMethodInfo(
		getUserGroupsHandler,
		newGroupServiceGetUserGroupsArgs,
		newGroupServiceGetUserGroupsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchGroupByNumber": kitex.NewMethodInfo(
		searchGroupByNumberHandler,
		newGroupServiceSearchGroupByNumberArgs,
		newGroupServiceSearchGroupByNumberResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JoinGroup": kitex.NewMethodInfo(
		joinGroupHandler,
		newGroupServiceJoinGroupArgs,
		newGroupServiceJoinGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"HandleJoinReq": kitex.NewMethodInfo(
		handleJoinReqHandler,
		newGroupServiceHandleJoinReqArgs,
		newGroupServiceHandleJoinReqResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetJoinRequests": kitex.NewMethodInfo(
		getJoinRequestsHandler,
		newGroupServiceGetJoinRequestsArgs,
		newGroupServiceGetJoinRequestsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckMuted": kitex.NewMethodInfo(
		checkMutedHandler,
		newGroupServiceCheckMutedArgs,
		newGroupServiceCheckMutedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	groupServiceServiceInfo                = NewServiceInfo()
	groupServiceServiceInfoForClient       = NewServiceInfoForClient()
	groupServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return groupServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GroupService"
	handlerType := (*group.GroupService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "group",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceCreateGroupArgs)
	realResult := result.(*group.GroupServiceCreateGroupResult)
	success, err := handler.(group.GroupService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCreateGroupArgs() interface{} {
	return group.NewGroupServiceCreateGroupArgs()
}

func newGroupServiceCreateGroupResult() interface{} {
	return group.NewGroupServiceCreateGroupResult()
}

func inviteMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceInviteMembersArgs)
	realResult := result.(*group.GroupServiceInviteMembersResult)
	success, err := handler.(group.GroupService).InviteMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceInviteMembersArgs() interface{} {
	return group.NewGroupServiceInviteMembersArgs()
}

func newGroupServiceInviteMembersResult() interface{} {
	return group.NewGroupServiceInviteMembersResult()
}

func kickMembersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceKickMembersArgs)
	realResult := result.(*group.GroupServiceKickMembersResult)
	success, err := handler.(group.GroupService).KickMembers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceKickMembersArgs() interface{} {
	return group.NewGroupServiceKickMembersArgs()
}

func newGroupServiceKickMembersResult() interface{} {
	return group.NewGroupServiceKickMembersResult()
}

func getGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceGetGroupInfoArgs)
	realResult := result.(*group.GroupServiceGetGroupInfoResult)
	success, err := handler.(group.GroupService).GetGroupInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupInfoArgs() interface{} {
	return group.NewGroupServiceGetGroupInfoArgs()
}

func newGroupServiceGetGroupInfoResult() interface{} {
	return group.NewGroupServiceGetGroupInfoResult()
}

func changeOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceChangeOwnerArgs)
	realResult := result.(*group.GroupServiceChangeOwnerResult)
	success, err := handler.(group.GroupService).ChangeOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceChangeOwnerArgs() interface{} {
	return group.NewGroupServiceChangeOwnerArgs()
}

func newGroupServiceChangeOwnerResult() interface{} {
	return group.NewGroupServiceChangeOwnerResult()
}

func changeNoticeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceChangeNoticeArgs)
	realResult := result.(*group.GroupServiceChangeNoticeResult)
	success, err := handler.(group.GroupService).ChangeNotice(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceChangeNoticeArgs() interface{} {
	return group.NewGroupServiceChangeNoticeArgs()
}

func newGroupServiceChangeNoticeResult() interface{} {
	return group.NewGroupServiceChangeNoticeResult()
}

func mutedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceMutedArgs)
	realResult := result.(*group.GroupServiceMutedResult)
	success, err := handler.(group.GroupService).Muted(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceMutedArgs() interface{} {
	return group.NewGroupServiceMutedArgs()
}

func newGroupServiceMutedResult() interface{} {
	return group.NewGroupServiceMutedResult()
}

func setAdminHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceSetAdminArgs)
	realResult := result.(*group.GroupServiceSetAdminResult)
	success, err := handler.(group.GroupService).SetAdmin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSetAdminArgs() interface{} {
	return group.NewGroupServiceSetAdminArgs()
}

func newGroupServiceSetAdminResult() interface{} {
	return group.NewGroupServiceSetAdminResult()
}

func getUserGroupsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceGetUserGroupsArgs)
	realResult := result.(*group.GroupServiceGetUserGroupsResult)
	success, err := handler.(group.GroupService).GetUserGroups(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetUserGroupsArgs() interface{} {
	return group.NewGroupServiceGetUserGroupsArgs()
}

func newGroupServiceGetUserGroupsResult() interface{} {
	return group.NewGroupServiceGetUserGroupsResult()
}

func searchGroupByNumberHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceSearchGroupByNumberArgs)
	realResult := result.(*group.GroupServiceSearchGroupByNumberResult)
	success, err := handler.(group.GroupService).SearchGroupByNumber(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSearchGroupByNumberArgs() interface{} {
	return group.NewGroupServiceSearchGroupByNumberArgs()
}

func newGroupServiceSearchGroupByNumberResult() interface{} {
	return group.NewGroupServiceSearchGroupByNumberResult()
}

func joinGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceJoinGroupArgs)
	realResult := result.(*group.GroupServiceJoinGroupResult)
	success, err := handler.(group.GroupService).JoinGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceJoinGroupArgs() interface{} {
	return group.NewGroupServiceJoinGroupArgs()
}

func newGroupServiceJoinGroupResult() interface{} {
	return group.NewGroupServiceJoinGroupResult()
}

func handleJoinReqHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceHandleJoinReqArgs)
	realResult := result.(*group.GroupServiceHandleJoinReqResult)
	success, err := handler.(group.GroupService).HandleJoinReq(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceHandleJoinReqArgs() interface{} {
	return group.NewGroupServiceHandleJoinReqArgs()
}

func newGroupServiceHandleJoinReqResult() interface{} {
	return group.NewGroupServiceHandleJoinReqResult()
}

func getJoinRequestsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceGetJoinRequestsArgs)
	realResult := result.(*group.GroupServiceGetJoinRequestsResult)
	success, err := handler.(group.GroupService).GetJoinRequests(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetJoinRequestsArgs() interface{} {
	return group.NewGroupServiceGetJoinRequestsArgs()
}

func newGroupServiceGetJoinRequestsResult() interface{} {
	return group.NewGroupServiceGetJoinRequestsResult()
}

func checkMutedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*group.GroupServiceCheckMutedArgs)
	realResult := result.(*group.GroupServiceCheckMutedResult)
	success, err := handler.(group.GroupService).CheckMuted(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCheckMutedArgs() interface{} {
	return group.NewGroupServiceCheckMutedArgs()
}

func newGroupServiceCheckMutedResult() interface{} {
	return group.NewGroupServiceCheckMutedResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateGroup(ctx context.Context, req *group.CreateGroupReq) (r *group.CreateGroupRes, err error) {
	var _args group.GroupServiceCreateGroupArgs
	_args.Req = req
	var _result group.GroupServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InviteMembers(ctx context.Context, req *group.InviteMembersReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceInviteMembersArgs
	_args.Req = req
	var _result group.GroupServiceInviteMembersResult
	if err = p.c.Call(ctx, "InviteMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) KickMembers(ctx context.Context, req *group.KickMembersReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceKickMembersArgs
	_args.Req = req
	var _result group.GroupServiceKickMembersResult
	if err = p.c.Call(ctx, "KickMembers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupInfo(ctx context.Context, req *group.GetGroupInfoReq) (r *group.GetGroupInfoRes, err error) {
	var _args group.GroupServiceGetGroupInfoArgs
	_args.Req = req
	var _result group.GroupServiceGetGroupInfoResult
	if err = p.c.Call(ctx, "GetGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeOwner(ctx context.Context, req *group.ChangeOwnerReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceChangeOwnerArgs
	_args.Req = req
	var _result group.GroupServiceChangeOwnerResult
	if err = p.c.Call(ctx, "ChangeOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeNotice(ctx context.Context, req *group.ChangeNoticeReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceChangeNoticeArgs
	_args.Req = req
	var _result group.GroupServiceChangeNoticeResult
	if err = p.c.Call(ctx, "ChangeNotice", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Muted(ctx context.Context, req *group.MutedReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceMutedArgs
	_args.Req = req
	var _result group.GroupServiceMutedResult
	if err = p.c.Call(ctx, "Muted", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetAdmin(ctx context.Context, req *group.SetAdminReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceSetAdminArgs
	_args.Req = req
	var _result group.GroupServiceSetAdminResult
	if err = p.c.Call(ctx, "SetAdmin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserGroups(ctx context.Context, req *group.GetUserGroupsReq) (r *group.GetUserGroupsRes, err error) {
	var _args group.GroupServiceGetUserGroupsArgs
	_args.Req = req
	var _result group.GroupServiceGetUserGroupsResult
	if err = p.c.Call(ctx, "GetUserGroups", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchGroupByNumber(ctx context.Context, req *group.SearchGroupByNumberReq) (r *group.SearchGroupByNumberRes, err error) {
	var _args group.GroupServiceSearchGroupByNumberArgs
	_args.Req = req
	var _result group.GroupServiceSearchGroupByNumberResult
	if err = p.c.Call(ctx, "SearchGroupByNumber", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinGroup(ctx context.Context, req *group.JoinGroupReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceJoinGroupArgs
	_args.Req = req
	var _result group.GroupServiceJoinGroupResult
	if err = p.c.Call(ctx, "JoinGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HandleJoinReq(ctx context.Context, req *group.HandleJoinReqReq) (r *group.CommonRes, err error) {
	var _args group.GroupServiceHandleJoinReqArgs
	_args.Req = req
	var _result group.GroupServiceHandleJoinReqResult
	if err = p.c.Call(ctx, "HandleJoinReq", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetJoinRequests(ctx context.Context, req *group.GetJoinRequestsReq) (r *group.GetJoinRequestsRes, err error) {
	var _args group.GroupServiceGetJoinRequestsArgs
	_args.Req = req
	var _result group.GroupServiceGetJoinRequestsResult
	if err = p.c.Call(ctx, "GetJoinRequests", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckMuted(ctx context.Context, req *group.CheckMutedReq) (r *group.CheckMutedRes, err error) {
	var _args group.GroupServiceCheckMutedArgs
	_args.Req = req
	var _result group.GroupServiceCheckMutedResult
	if err = p.c.Call(ctx, "CheckMuted", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
