// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package chat

import (
	"context"
	"fmt"
)

type CommonRes struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewCommonRes() *CommonRes {
	return &CommonRes{}
}

func (p *CommonRes) InitDefault() {
}

func (p *CommonRes) GetSuccess() (v bool) {
	return p.Success
}
func (p *CommonRes) SetSuccess(val bool) {
	p.Success = val
}

func (p *CommonRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonRes(%+v)", *p)
}

var fieldIDToName_CommonRes = map[int16]string{
	1: "success",
}

type SendMessageReq struct {
	SenderId       int64  `thrift:"sender_id,1" frugal:"1,default,i64" json:"sender_id"`
	ConversationId int64  `thrift:"conversation_id,2" frugal:"2,default,i64" json:"conversation_id"`
	PeerId         int64  `thrift:"peer_id,3" frugal:"3,default,i64" json:"peer_id"`
	Content        string `thrift:"content,4" frugal:"4,default,string" json:"content"`
	ClientSeq      int64  `thrift:"client_seq,5" frugal:"5,default,i64" json:"client_seq"`
	QuoteMsgId     *int64 `thrift:"quote_msg_id,6,optional" frugal:"6,optional,i64" json:"quote_msg_id,omitempty"`
}

func NewSendMessageReq() *SendMessageReq {
	return &SendMessageReq{}
}

func (p *SendMessageReq) InitDefault() {
}

func (p *SendMessageReq) GetSenderId() (v int64) {
	return p.SenderId
}

func (p *SendMessageReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *SendMessageReq) GetPeerId() (v int64) {
	return p.PeerId
}

func (p *SendMessageReq) GetContent() (v string) {
	return p.Content
}

func (p *SendMessageReq) GetClientSeq() (v int64) {
	return p.ClientSeq
}

var SendMessageReq_QuoteMsgId_DEFAULT int64

func (p *SendMessageReq) GetQuoteMsgId() (v int64) {
	if !p.IsSetQuoteMsgId() {
		return SendMessageReq_QuoteMsgId_DEFAULT
	}
	return *p.QuoteMsgId
}
func (p *SendMessageReq) SetSenderId(val int64) {
	p.SenderId = val
}
func (p *SendMessageReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *SendMessageReq) SetPeerId(val int64) {
	p.PeerId = val
}
func (p *SendMessageReq) SetContent(val string) {
	p.Content = val
}
func (p *SendMessageReq) SetClientSeq(val int64) {
	p.ClientSeq = val
}
func (p *SendMessageReq) SetQuoteMsgId(val *int64) {
	p.QuoteMsgId = val
}

func (p *SendMessageReq) IsSetQuoteMsgId() bool {
	return p.QuoteMsgId != nil
}

func (p *SendMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageReq(%+v)", *p)
}

var fieldIDToName_SendMessageReq = map[int16]string{
	1: "sender_id",
	2: "conversation_id",
	3: "peer_id",
	4: "content",
	5: "client_seq",
	6: "quote_msg_id",
}

type SendMessageRes struct {
	Success          bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	MsgId            int64   `thrift:"msg_id,2" frugal:"2,default,i64" json:"msg_id"`
	Timestamp        int64   `thrift:"timestamp,3" frugal:"3,default,i64" json:"timestamp"`
	ConversationId   int64   `thrift:"conversation_id,4" frugal:"4,default,i64" json:"conversation_id"`
	MemberIds        []int64 `thrift:"member_ids,5" frugal:"5,default,list<i64>" json:"member_ids"`
	Content          *string `thrift:"content,6,optional" frugal:"6,optional,string" json:"content,omitempty"`
	ConversationType *int16  `thrift:"conversation_type,7,optional" frugal:"7,optional,i16" json:"conversation_type,omitempty"`
	Seq              *int64  `thrift:"seq,8,optional" frugal:"8,optional,i64" json:"seq,omitempty"`
}

func NewSendMessageRes() *SendMessageRes {
	return &SendMessageRes{}
}

func (p *SendMessageRes) InitDefault() {
}

func (p *SendMessageRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *SendMessageRes) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *SendMessageRes) GetTimestamp() (v int64) {
	return p.Timestamp
}

func (p *SendMessageRes) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *SendMessageRes) GetMemberIds() (v []int64) {
	return p.MemberIds
}

var SendMessageRes_Content_DEFAULT string

func (p *SendMessageRes) GetContent() (v string) {
	if !p.IsSetContent() {
		return SendMessageRes_Content_DEFAULT
	}
	return *p.Content
}

var SendMessageRes_ConversationType_DEFAULT int16

func (p *SendMessageRes) GetConversationType() (v int16) {
	if !p.IsSetConversationType() {
		return SendMessageRes_ConversationType_DEFAULT
	}
	return *p.ConversationType
}

var SendMessageRes_Seq_DEFAULT int64

func (p *SendMessageRes) GetSeq() (v int64) {
	if !p.IsSetSeq() {
		return SendMessageRes_Seq_DEFAULT
	}
	return *p.Seq
}
func (p *SendMessageRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *SendMessageRes) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *SendMessageRes) SetTimestamp(val int64) {
	p.Timestamp = val
}
func (p *SendMessageRes) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *SendMessageRes) SetMemberIds(val []int64) {
	p.MemberIds = val
}
func (p *SendMessageRes) SetContent(val *string) {
	p.Content = val
}
func (p *SendMessageRes) SetConversationType(val *int16) {
	p.ConversationType = val
}
func (p *SendMessageRes) SetSeq(val *int64) {
	p.Seq = val
}

func (p *SendMessageRes) IsSetContent() bool {
	return p.Content != nil
}

func (p *SendMessageRes) IsSetConversationType() bool {
	return p.ConversationType != nil
}

func (p *SendMessageRes) IsSetSeq() bool {
	return p.Seq != nil
}

func (p *SendMessageRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendMessageRes(%+v)", *p)
}

var fieldIDToName_SendMessageRes = map[int16]string{
	1: "success",
	2: "msg_id",
	3: "timestamp",
	4: "conversation_id",
	5: "member_ids",
	6: "content",
	7: "conversation_type",
	8: "seq",
}

type Message struct {
	MsgId          int64   `thrift:"msg_id,1" frugal:"1,default,i64" json:"msg_id"`
	ClientSeq      int64   `thrift:"client_seq,2" frugal:"2,default,i64" json:"client_seq"`
	SenderId       int64   `thrift:"sender_id,3" frugal:"3,default,i64" json:"sender_id"`
	ConversationId int64   `thrift:"conversation_id,4" frugal:"4,default,i64" json:"conversation_id"`
	Content        string  `thrift:"content,5" frugal:"5,default,string" json:"content"`
	Timestamp      int64   `thrift:"timestamp,6" frugal:"6,default,i64" json:"timestamp"`
	SenderName     *string `thrift:"sender_name,7,optional" frugal:"7,optional,string" json:"sender_name,omitempty"`
	Seq            *int64  `thrift:"seq,8,optional" frugal:"8,optional,i64" json:"seq,omitempty"`
	Status         *int16  `thrift:"status,9,optional" frugal:"9,optional,i16" json:"status,omitempty"`
	IsEdited       *bool   `thrift:"is_edited,10,optional" frugal:"10,optional,bool" json:"is_edited,omitempty"`
	QuoteMsgId     *int64  `thrift:"quote_msg_id,11,optional" frugal:"11,optional,i64" json:"quote_msg_id,omitempty"`
}

func NewMessage() *Message {
	return &Message{}
}

func (p *Message) InitDefault() {
}

func (p *Message) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *Message) GetClientSeq() (v int64) {
	return p.ClientSeq
}

func (p *Message) GetSenderId() (v int64) {
	return p.SenderId
}

func (p *Message) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *Message) GetContent() (v string) {
	return p.Content
}

func (p *Message) GetTimestamp() (v int64) {
	return p.Timestamp
}

var Message_SenderName_DEFAULT string

func (p *Message) GetSenderName() (v string) {
	if !p.IsSetSenderName() {
		return Message_SenderName_DEFAULT
	}
	return *p.SenderName
}

var Message_Seq_DEFAULT int64

func (p *Message) GetSeq() (v int64) {
	if !p.IsSetSeq() {
		return Message_Seq_DEFAULT
	}
	return *p.Seq
}

var Message_Status_DEFAULT int16

func (p *Message) GetStatus() (v int16) {
	if !p.IsSetStatus() {
		return Message_Status_DEFAULT
	}
	return *p.Status
}

var Message_IsEdited_DEFAULT bool

func (p *Message) GetIsEdited() (v bool) {
	if !p.IsSetIsEdited() {
		return Message_IsEdited_DEFAULT
	}
	return *p.IsEdited
}

var Message_QuoteMsgId_DEFAULT int64

func (p *Message) GetQuoteMsgId() (v int64) {
	if !p.IsSetQuoteMsgId() {
		return Message_QuoteMsgId_DEFAULT
	}
	return *p.QuoteMsgId
}
func (p *Message) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *Message) SetClientSeq(val int64) {
	p.ClientSeq = val
}
func (p *Message) SetSenderId(val int64) {
	p.SenderId = val
}
func (p *Message) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *Message) SetContent(val string) {
	p.Content = val
}
func (p *Message) SetTimestamp(val int64) {
	p.Timestamp = val
}
func (p *Message) SetSenderName(val *string) {
	p.SenderName = val
}
func (p *Message) SetSeq(val *int64) {
	p.Seq = val
}
func (p *Message) SetStatus(val *int16) {
	p.Status = val
}
func (p *Message) SetIsEdited(val *bool) {
	p.IsEdited = val
}
func (p *Message) SetQuoteMsgId(val *int64) {
	p.QuoteMsgId = val
}

func (p *Message) IsSetSenderName() bool {
	return p.SenderName != nil
}

func (p *Message) IsSetSeq() bool {
	return p.Seq != nil
}

func (p *Message) IsSetStatus() bool {
	return p.Status != nil
}

func (p *Message) IsSetIsEdited() bool {
	return p.IsEdited != nil
}

func (p *Message) IsSetQuoteMsgId() bool {
	return p.QuoteMsgId != nil
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

var fieldIDToName_Message = map[int16]string{
	1:  "msg_id",
	2:  "client_seq",
	3:  "sender_id",
	4:  "conversation_id",
	5:  "content",
	6:  "timestamp",
	7:  "sender_name",
	8:  "seq",
	9:  "status",
	10: "is_edited",
	11: "quote_msg_id",
}

type GetHistoryReq struct {
	UserId         int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ConversationId int64 `thrift:"conversation_id,2" frugal:"2,default,i64" json:"conversation_id"`
	BeforeMsgId    int64 `thrift:"before_msg_id,3" frugal:"3,default,i64" json:"before_msg_id"`
	Limit          int16 `thrift:"limit,4" frugal:"4,default,i16" json:"limit"`
}

func NewGetHistoryReq() *GetHistoryReq {
	return &GetHistoryReq{}
}

func (p *GetHistoryReq) InitDefault() {
}

func (p *GetHistoryReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetHistoryReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *GetHistoryReq) GetBeforeMsgId() (v int64) {
	return p.BeforeMsgId
}

func (p *GetHistoryReq) GetLimit() (v int16) {
	return p.Limit
}
func (p *GetHistoryReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetHistoryReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *GetHistoryReq) SetBeforeMsgId(val int64) {
	p.BeforeMsgId = val
}
func (p *GetHistoryReq) SetLimit(val int16) {
	p.Limit = val
}

func (p *GetHistoryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetHistoryReq(%+v)", *p)
}

var fieldIDToName_GetHistoryReq = map[int16]string{
	1: "user_id",
	2: "conversation_id",
	3: "before_msg_id",
	4: "limit",
}

type GetHistoryRes struct {
	Success  bool       `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Messages []*Message `thrift:"messages,2" frugal:"2,default,list<Message>" json:"messages"`
}

func NewGetHistoryRes() *GetHistoryRes {
	return &GetHistoryRes{}
}

func (p *GetHistoryRes) InitDefault() {
}

func (p *GetHistoryRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetHistoryRes) GetMessages() (v []*Message) {
	return p.Messages
}
func (p *GetHistoryRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetHistoryRes) SetMessages(val []*Message) {
	p.Messages = val
}

func (p *GetHistoryRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetHistoryRes(%+v)", *p)
}

var fieldIDToName_GetHistoryRes = map[int16]string{
	1: "success",
	2: "messages",
}

type CreateConversationReq struct {
	Name      string  `thrift:"name,1" frugal:"1,default,string" json:"name"`
	MemberIds []int64 `thrift:"member_ids,2" frugal:"2,default,list<i64>" json:"member_ids"`
	GroupId   *int64  `thrift:"group_id,3,optional" frugal:"3,optional,i64" json:"group_id,omitempty"`
}

func NewCreateConversationReq() *CreateConversationReq {
	return &CreateConversationReq{}
}

func (p *CreateConversationReq) InitDefault() {
}

func (p *CreateConversationReq) GetName() (v string) {
	return p.Name
}

func (p *CreateConversationReq) GetMemberIds() (v []int64) {
	return p.MemberIds
}

var CreateConversationReq_GroupId_DEFAULT int64

func (p *CreateConversationReq) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return CreateConversationReq_GroupId_DEFAULT
	}
	return *p.GroupId
}
func (p *CreateConversationReq) SetName(val string) {
	p.Name = val
}
func (p *CreateConversationReq) SetMemberIds(val []int64) {
	p.MemberIds = val
}
func (p *CreateConversationReq) SetGroupId(val *int64) {
	p.GroupId = val
}

func (p *CreateConversationReq) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *CreateConversationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateConversationReq(%+v)", *p)
}

var fieldIDToName_CreateConversationReq = map[int16]string{
	1: "name",
	2: "member_ids",
	3: "group_id",
}

type CreateConversationRes struct {
	Success        bool  `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	ConversationId int64 `thrift:"conversation_id,2" frugal:"2,default,i64" json:"conversation_id"`
}

func NewCreateConversationRes() *CreateConversationRes {
	return &CreateConversationRes{}
}

func (p *CreateConversationRes) InitDefault() {
}

func (p *CreateConversationRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreateConversationRes) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *CreateConversationRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreateConversationRes) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *CreateConversationRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateConversationRes(%+v)", *p)
}

var fieldIDToName_CreateConversationRes = map[int16]string{
	1: "success",
	2: "conversation_id",
}

type GetConversationsReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetConversationsReq() *GetConversationsReq {
	return &GetConversationsReq{}
}

func (p *GetConversationsReq) InitDefault() {
}

func (p *GetConversationsReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetConversationsReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetConversationsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetConversationsReq(%+v)", *p)
}

var fieldIDToName_GetConversationsReq = map[int16]string{
	1: "user_id",
}

type ConversationInfo struct {
	ConversationId int64   `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
	Type           int16   `thrift:"type,2" frugal:"2,default,i16" json:"type"`
	Name           string  `thrift:"name,3" frugal:"3,default,string" json:"name"`
	MemberIds      []int64 `thrift:"member_ids,4" frugal:"4,default,list<i64>" json:"member_ids"`
	GroupId        *int64  `thrift:"group_id,5,optional" frugal:"5,optional,i64" json:"group_id,omitempty"`
	MaxSeq         *int64  `thrift:"max_seq,6,optional" frugal:"6,optional,i64" json:"max_seq,omitempty"`
	MaxReadSeq     *int64  `thrift:"max_read_seq,7,optional" frugal:"7,optional,i64" json:"max_read_seq,omitempty"`
	UnreadCount    *int64  `thrift:"unread_count,8,optional" frugal:"8,optional,i64" json:"unread_count,omitempty"`
}

func NewConversationInfo() *ConversationInfo {
	return &ConversationInfo{}
}

func (p *ConversationInfo) InitDefault() {
}

func (p *ConversationInfo) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *ConversationInfo) GetType() (v int16) {
	return p.Type
}

func (p *ConversationInfo) GetName() (v string) {
	return p.Name
}

func (p *ConversationInfo) GetMemberIds() (v []int64) {
	return p.MemberIds
}

var ConversationInfo_GroupId_DEFAULT int64

func (p *ConversationInfo) GetGroupId() (v int64) {
	if !p.IsSetGroupId() {
		return ConversationInfo_GroupId_DEFAULT
	}
	return *p.GroupId
}

var ConversationInfo_MaxSeq_DEFAULT int64

func (p *ConversationInfo) GetMaxSeq() (v int64) {
	if !p.IsSetMaxSeq() {
		return ConversationInfo_MaxSeq_DEFAULT
	}
	return *p.MaxSeq
}

var ConversationInfo_MaxReadSeq_DEFAULT int64

func (p *ConversationInfo) GetMaxReadSeq() (v int64) {
	if !p.IsSetMaxReadSeq() {
		return ConversationInfo_MaxReadSeq_DEFAULT
	}
	return *p.MaxReadSeq
}

var ConversationInfo_UnreadCount_DEFAULT int64

func (p *ConversationInfo) GetUnreadCount() (v int64) {
	if !p.IsSetUnreadCount() {
		return ConversationInfo_UnreadCount_DEFAULT
	}
	return *p.UnreadCount
}
func (p *ConversationInfo) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *ConversationInfo) SetType(val int16) {
	p.Type = val
}
func (p *ConversationInfo) SetName(val string) {
	p.Name = val
}
func (p *ConversationInfo) SetMemberIds(val []int64) {
	p.MemberIds = val
}
func (p *ConversationInfo) SetGroupId(val *int64) {
	p.GroupId = val
}
func (p *ConversationInfo) SetMaxSeq(val *int64) {
	p.MaxSeq = val
}
func (p *ConversationInfo) SetMaxReadSeq(val *int64) {
	p.MaxReadSeq = val
}
func (p *ConversationInfo) SetUnreadCount(val *int64) {
	p.UnreadCount = val
}

func (p *ConversationInfo) IsSetGroupId() bool {
	return p.GroupId != nil
}

func (p *ConversationInfo) IsSetMaxSeq() bool {
	return p.MaxSeq != nil
}

func (p *ConversationInfo) IsSetMaxReadSeq() bool {
	return p.MaxReadSeq != nil
}

func (p *ConversationInfo) IsSetUnreadCount() bool {
	return p.UnreadCount != nil
}

func (p *ConversationInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConversationInfo(%+v)", *p)
}

var fieldIDToName_ConversationInfo = map[int16]string{
	1: "conversation_id",
	2: "type",
	3: "name",
	4: "member_ids",
	5: "group_id",
	6: "max_seq",
	7: "max_read_seq",
	8: "unread_count",
}

type GetConversationsRes struct {
	Success       bool                `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Conversations []*ConversationInfo `thrift:"conversations,2" frugal:"2,default,list<ConversationInfo>" json:"conversations"`
}

func NewGetConversationsRes() *GetConversationsRes {
	return &GetConversationsRes{}
}

func (p *GetConversationsRes) InitDefault() {
}

func (p *GetConversationsRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetConversationsRes) GetConversations() (v []*ConversationInfo) {
	return p.Conversations
}
func (p *GetConversationsRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetConversationsRes) SetConversations(val []*ConversationInfo) {
	p.Conversations = val
}

func (p *GetConversationsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetConversationsRes(%+v)", *p)
}

var fieldIDToName_GetConversationsRes = map[int16]string{
	1: "success",
	2: "conversations",
}

type SetOnlineReq struct {
	UserId      int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	GatewayAddr string `thrift:"gateway_addr,2" frugal:"2,default,string" json:"gateway_addr"`
}

func NewSetOnlineReq() *SetOnlineReq {
	return &SetOnlineReq{}
}

func (p *SetOnlineReq) InitDefault() {
}

func (p *SetOnlineReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SetOnlineReq) GetGatewayAddr() (v string) {
	return p.GatewayAddr
}
func (p *SetOnlineReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SetOnlineReq) SetGatewayAddr(val string) {
	p.GatewayAddr = val
}

func (p *SetOnlineReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetOnlineReq(%+v)", *p)
}

var fieldIDToName_SetOnlineReq = map[int16]string{
	1: "user_id",
	2: "gateway_addr",
}

type SetOfflineReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewSetOfflineReq() *SetOfflineReq {
	return &SetOfflineReq{}
}

func (p *SetOfflineReq) InitDefault() {
}

func (p *SetOfflineReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *SetOfflineReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *SetOfflineReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetOfflineReq(%+v)", *p)
}

var fieldIDToName_SetOfflineReq = map[int16]string{
	1: "user_id",
}

type RenewOnlineReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewRenewOnlineReq() *RenewOnlineReq {
	return &RenewOnlineReq{}
}

func (p *RenewOnlineReq) InitDefault() {
}

func (p *RenewOnlineReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *RenewOnlineReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *RenewOnlineReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RenewOnlineReq(%+v)", *p)
}

var fieldIDToName_RenewOnlineReq = map[int16]string{
	1: "user_id",
}

type GetOnlineStatusReq struct {
	UserIds []int64 `thrift:"user_ids,1" frugal:"1,default,list<i64>" json:"user_ids"`
}

func NewGetOnlineStatusReq() *GetOnlineStatusReq {
	return &GetOnlineStatusReq{}
}

func (p *GetOnlineStatusReq) InitDefault() {
}

func (p *GetOnlineStatusReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *GetOnlineStatusReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *GetOnlineStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOnlineStatusReq(%+v)", *p)
}

var fieldIDToName_GetOnlineStatusReq = map[int16]string{
	1: "user_ids",
}

type OnlineStatus struct {
	UserId      int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Online      bool   `thrift:"online,2" frugal:"2,default,bool" json:"online"`
	GatewayAddr string `thrift:"gateway_addr,3" frugal:"3,default,string" json:"gateway_addr"`
}

func NewOnlineStatus() *OnlineStatus {
	return &OnlineStatus{}
}

func (p *OnlineStatus) InitDefault() {
}

func (p *OnlineStatus) GetUserId() (v int64) {
	return p.UserId
}

func (p *OnlineStatus) GetOnline() (v bool) {
	return p.Online
}

func (p *OnlineStatus) GetGatewayAddr() (v string) {
	return p.GatewayAddr
}
func (p *OnlineStatus) SetUserId(val int64) {
	p.UserId = val
}
func (p *OnlineStatus) SetOnline(val bool) {
	p.Online = val
}
func (p *OnlineStatus) SetGatewayAddr(val string) {
	p.GatewayAddr = val
}

func (p *OnlineStatus) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OnlineStatus(%+v)", *p)
}

var fieldIDToName_OnlineStatus = map[int16]string{
	1: "user_id",
	2: "online",
	3: "gateway_addr",
}

type GetOnlineStatusRes struct {
	Statuses []*OnlineStatus `thrift:"statuses,1" frugal:"1,default,list<OnlineStatus>" json:"statuses"`
}

func NewGetOnlineStatusRes() *GetOnlineStatusRes {
	return &GetOnlineStatusRes{}
}

func (p *GetOnlineStatusRes) InitDefault() {
}

func (p *GetOnlineStatusRes) GetStatuses() (v []*OnlineStatus) {
	return p.Statuses
}
func (p *GetOnlineStatusRes) SetStatuses(val []*OnlineStatus) {
	p.Statuses = val
}

func (p *GetOnlineStatusRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOnlineStatusRes(%+v)", *p)
}

var fieldIDToName_GetOnlineStatusRes = map[int16]string{
	1: "statuses",
}

type AddConversationMembersReq struct {
	ConversationId int64   `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
	MemberIds      []int64 `thrift:"member_ids,2" frugal:"2,default,list<i64>" json:"member_ids"`
}

func NewAddConversationMembersReq() *AddConversationMembersReq {
	return &AddConversationMembersReq{}
}

func (p *AddConversationMembersReq) InitDefault() {
}

func (p *AddConversationMembersReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *AddConversationMembersReq) GetMemberIds() (v []int64) {
	return p.MemberIds
}
func (p *AddConversationMembersReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *AddConversationMembersReq) SetMemberIds(val []int64) {
	p.MemberIds = val
}

func (p *AddConversationMembersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddConversationMembersReq(%+v)", *p)
}

var fieldIDToName_AddConversationMembersReq = map[int16]string{
	1: "conversation_id",
	2: "member_ids",
}

type AddConversationMembersRes struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewAddConversationMembersRes() *AddConversationMembersRes {
	return &AddConversationMembersRes{}
}

func (p *AddConversationMembersRes) InitDefault() {
}

func (p *AddConversationMembersRes) GetSuccess() (v bool) {
	return p.Success
}
func (p *AddConversationMembersRes) SetSuccess(val bool) {
	p.Success = val
}

func (p *AddConversationMembersRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddConversationMembersRes(%+v)", *p)
}

var fieldIDToName_AddConversationMembersRes = map[int16]string{
	1: "success",
}

type RemoveConversationMembersReq struct {
	ConversationId int64   `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
	MemberIds      []int64 `thrift:"member_ids,2" frugal:"2,default,list<i64>" json:"member_ids"`
}

func NewRemoveConversationMembersReq() *RemoveConversationMembersReq {
	return &RemoveConversationMembersReq{}
}

func (p *RemoveConversationMembersReq) InitDefault() {
}

func (p *RemoveConversationMembersReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *RemoveConversationMembersReq) GetMemberIds() (v []int64) {
	return p.MemberIds
}
func (p *RemoveConversationMembersReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *RemoveConversationMembersReq) SetMemberIds(val []int64) {
	p.MemberIds = val
}

func (p *RemoveConversationMembersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemoveConversationMembersReq(%+v)", *p)
}

var fieldIDToName_RemoveConversationMembersReq = map[int16]string{
	1: "conversation_id",
	2: "member_ids",
}

type RemoveConversationMembersRes struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewRemoveConversationMembersRes() *RemoveConversationMembersRes {
	return &RemoveConversationMembersRes{}
}

func (p *RemoveConversationMembersRes) InitDefault() {
}

func (p *RemoveConversationMembersRes) GetSuccess() (v bool) {
	return p.Success
}
func (p *RemoveConversationMembersRes) SetSuccess(val bool) {
	p.Success = val
}

func (p *RemoveConversationMembersRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemoveConversationMembersRes(%+v)", *p)
}

var fieldIDToName_RemoveConversationMembersRes = map[int16]string{
	1: "success",
}

type DeleteConversationReq struct {
	ConversationId int64 `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
}

func NewDeleteConversationReq() *DeleteConversationReq {
	return &DeleteConversationReq{}
}

func (p *DeleteConversationReq) InitDefault() {
}

func (p *DeleteConversationReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *DeleteConversationReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *DeleteConversationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteConversationReq(%+v)", *p)
}

var fieldIDToName_DeleteConversationReq = map[int16]string{
	1: "conversation_id",
}

type DeleteConversationRes struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewDeleteConversationRes() *DeleteConversationRes {
	return &DeleteConversationRes{}
}

func (p *DeleteConversationRes) InitDefault() {
}

func (p *DeleteConversationRes) GetSuccess() (v bool) {
	return p.Success
}
func (p *DeleteConversationRes) SetSuccess(val bool) {
	p.Success = val
}

func (p *DeleteConversationRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteConversationRes(%+v)", *p)
}

var fieldIDToName_DeleteConversationRes = map[int16]string{
	1: "success",
}

type MarkReadReq struct {
	UserId         int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ConversationId int64 `thrift:"conversation_id,2" frugal:"2,default,i64" json:"conversation_id"`
}

func NewMarkReadReq() *MarkReadReq {
	return &MarkReadReq{}
}

func (p *MarkReadReq) InitDefault() {
}

func (p *MarkReadReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *MarkReadReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *MarkReadReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *MarkReadReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *MarkReadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarkReadReq(%+v)", *p)
}

var fieldIDToName_MarkReadReq = map[int16]string{
	1: "user_id",
	2: "conversation_id",
}

type MarkReadRes struct {
	Success    bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	MaxReadSeq *int64 `thrift:"max_read_seq,2,optional" frugal:"2,optional,i64" json:"max_read_seq,omitempty"`
}

func NewMarkReadRes() *MarkReadRes {
	return &MarkReadRes{}
}

func (p *MarkReadRes) InitDefault() {
}

func (p *MarkReadRes) GetSuccess() (v bool) {
	return p.Success
}

var MarkReadRes_MaxReadSeq_DEFAULT int64

func (p *MarkReadRes) GetMaxReadSeq() (v int64) {
	if !p.IsSetMaxReadSeq() {
		return MarkReadRes_MaxReadSeq_DEFAULT
	}
	return *p.MaxReadSeq
}
func (p *MarkReadRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *MarkReadRes) SetMaxReadSeq(val *int64) {
	p.MaxReadSeq = val
}

func (p *MarkReadRes) IsSetMaxReadSeq() bool {
	return p.MaxReadSeq != nil
}

func (p *MarkReadRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarkReadRes(%+v)", *p)
}

var fieldIDToName_MarkReadRes = map[int16]string{
	1: "success",
	2: "max_read_seq",
}

type GetConversationMembersReq struct {
	ConversationId int64 `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
}

func NewGetConversationMembersReq() *GetConversationMembersReq {
	return &GetConversationMembersReq{}
}

func (p *GetConversationMembersReq) InitDefault() {
}

func (p *GetConversationMembersReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *GetConversationMembersReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *GetConversationMembersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetConversationMembersReq(%+v)", *p)
}

var fieldIDToName_GetConversationMembersReq = map[int16]string{
	1: "conversation_id",
}

type GetConversationMembersRes struct {
	Success   bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	MemberIds []int64 `thrift:"member_ids,2" frugal:"2,default,list<i64>" json:"member_ids"`
}

func NewGetConversationMembersRes() *GetConversationMembersRes {
	return &GetConversationMembersRes{}
}

func (p *GetConversationMembersRes) InitDefault() {
}

func (p *GetConversationMembersRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetConversationMembersRes) GetMemberIds() (v []int64) {
	return p.MemberIds
}
func (p *GetConversationMembersRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetConversationMembersRes) SetMemberIds(val []int64) {
	p.MemberIds = val
}

func (p *GetConversationMembersRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetConversationMembersRes(%+v)", *p)
}

var fieldIDToName_GetConversationMembersRes = map[int16]string{
	1: "success",
	2: "member_ids",
}

type GetOrCreatePrivateConversationReq struct {
	UserIdA int64 `thrift:"user_id_a,1" frugal:"1,default,i64" json:"user_id_a"`
	UserIdB int64 `thrift:"user_id_b,2" frugal:"2,default,i64" json:"user_id_b"`
}

func NewGetOrCreatePrivateConversationReq() *GetOrCreatePrivateConversationReq {
	return &GetOrCreatePrivateConversationReq{}
}

func (p *GetOrCreatePrivateConversationReq) InitDefault() {
}

func (p *GetOrCreatePrivateConversationReq) GetUserIdA() (v int64) {
	return p.UserIdA
}

func (p *GetOrCreatePrivateConversationReq) GetUserIdB() (v int64) {
	return p.UserIdB
}
func (p *GetOrCreatePrivateConversationReq) SetUserIdA(val int64) {
	p.UserIdA = val
}
func (p *GetOrCreatePrivateConversationReq) SetUserIdB(val int64) {
	p.UserIdB = val
}

func (p *GetOrCreatePrivateConversationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrCreatePrivateConversationReq(%+v)", *p)
}

var fieldIDToName_GetOrCreatePrivateConversationReq = map[int16]string{
	1: "user_id_a",
	2: "user_id_b",
}

type GetOrCreatePrivateConversationRes struct {
	Success        bool  `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	ConversationId int64 `thrift:"conversation_id,2" frugal:"2,default,i64" json:"conversation_id"`
}

func NewGetOrCreatePrivateConversationRes() *GetOrCreatePrivateConversationRes {
	return &GetOrCreatePrivateConversationRes{}
}

func (p *GetOrCreatePrivateConversationRes) InitDefault() {
}

func (p *GetOrCreatePrivateConversationRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetOrCreatePrivateConversationRes) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *GetOrCreatePrivateConversationRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetOrCreatePrivateConversationRes) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *GetOrCreatePrivateConversationRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrCreatePrivateConversationRes(%+v)", *p)
}

var fieldIDToName_GetOrCreatePrivateConversationRes = map[int16]string{
	1: "success",
	2: "conversation_id",
}

type RecallMessageReq struct {
	UserId         int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	MsgId          int64 `thrift:"msg_id,2" frugal:"2,default,i64" json:"msg_id"`
	ConversationId int64 `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
}

func NewRecallMessageReq() *RecallMessageReq {
	return &RecallMessageReq{}
}

func (p *RecallMessageReq) InitDefault() {
}

func (p *RecallMessageReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *RecallMessageReq) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *RecallMessageReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *RecallMessageReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *RecallMessageReq) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *RecallMessageReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *RecallMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecallMessageReq(%+v)", *p)
}

var fieldIDToName_RecallMessageReq = map[int16]string{
	1: "user_id",
	2: "msg_id",
	3: "conversation_id",
}

type RecallMessageRes struct {
	Success        bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	ConversationId *int64  `thrift:"conversation_id,2,optional" frugal:"2,optional,i64" json:"conversation_id,omitempty"`
	MemberIds      []int64 `thrift:"member_ids,3,optional" frugal:"3,optional,list<i64>" json:"member_ids,omitempty"`
}

func NewRecallMessageRes() *RecallMessageRes {
	return &RecallMessageRes{}
}

func (p *RecallMessageRes) InitDefault() {
}

func (p *RecallMessageRes) GetSuccess() (v bool) {
	return p.Success
}

var RecallMessageRes_ConversationId_DEFAULT int64

func (p *RecallMessageRes) GetConversationId() (v int64) {
	if !p.IsSetConversationId() {
		return RecallMessageRes_ConversationId_DEFAULT
	}
	return *p.ConversationId
}

var RecallMessageRes_MemberIds_DEFAULT []int64

func (p *RecallMessageRes) GetMemberIds() (v []int64) {
	if !p.IsSetMemberIds() {
		return RecallMessageRes_MemberIds_DEFAULT
	}
	return p.MemberIds
}
func (p *RecallMessageRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *RecallMessageRes) SetConversationId(val *int64) {
	p.ConversationId = val
}
func (p *RecallMessageRes) SetMemberIds(val []int64) {
	p.MemberIds = val
}

func (p *RecallMessageRes) IsSetConversationId() bool {
	return p.ConversationId != nil
}

func (p *RecallMessageRes) IsSetMemberIds() bool {
	return p.MemberIds != nil
}

func (p *RecallMessageRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecallMessageRes(%+v)", *p)
}

var fieldIDToName_RecallMessageRes = map[int16]string{
	1: "success",
	2: "conversation_id",
	3: "member_ids",
}

type EditMessageReq struct {
	UserId         int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	MsgId          int64  `thrift:"msg_id,2" frugal:"2,default,i64" json:"msg_id"`
	ConversationId int64  `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
	NewContent_    string `thrift:"new_content,4" frugal:"4,default,string" json:"new_content"`
}

func NewEditMessageReq() *EditMessageReq {
	return &EditMessageReq{}
}

func (p *EditMessageReq) InitDefault() {
}

func (p *EditMessageReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *EditMessageReq) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *EditMessageReq) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *EditMessageReq) GetNewContent_() (v string) {
	return p.NewContent_
}
func (p *EditMessageReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *EditMessageReq) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *EditMessageReq) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *EditMessageReq) SetNewContent_(val string) {
	p.NewContent_ = val
}

func (p *EditMessageReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EditMessageReq(%+v)", *p)
}

var fieldIDToName_EditMessageReq = map[int16]string{
	1: "user_id",
	2: "msg_id",
	3: "conversation_id",
	4: "new_content",
}

type EditMessageRes struct {
	Success        bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	ConversationId *int64  `thrift:"conversation_id,2,optional" frugal:"2,optional,i64" json:"conversation_id,omitempty"`
	MemberIds      []int64 `thrift:"member_ids,3,optional" frugal:"3,optional,list<i64>" json:"member_ids,omitempty"`
}

func NewEditMessageRes() *EditMessageRes {
	return &EditMessageRes{}
}

func (p *EditMessageRes) InitDefault() {
}

func (p *EditMessageRes) GetSuccess() (v bool) {
	return p.Success
}

var EditMessageRes_ConversationId_DEFAULT int64

func (p *EditMessageRes) GetConversationId() (v int64) {
	if !p.IsSetConversationId() {
		return EditMessageRes_ConversationId_DEFAULT
	}
	return *p.ConversationId
}

var EditMessageRes_MemberIds_DEFAULT []int64

func (p *EditMessageRes) GetMemberIds() (v []int64) {
	if !p.IsSetMemberIds() {
		return EditMessageRes_MemberIds_DEFAULT
	}
	return p.MemberIds
}
func (p *EditMessageRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *EditMessageRes) SetConversationId(val *int64) {
	p.ConversationId = val
}
func (p *EditMessageRes) SetMemberIds(val []int64) {
	p.MemberIds = val
}

func (p *EditMessageRes) IsSetConversationId() bool {
	return p.ConversationId != nil
}

func (p *EditMessageRes) IsSetMemberIds() bool {
	return p.MemberIds != nil
}

func (p *EditMessageRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EditMessageRes(%+v)", *p)
}

var fieldIDToName_EditMessageRes = map[int16]string{
	1: "success",
	2: "conversation_id",
	3: "member_ids",
}

type EditHistoryItem struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	MsgId      int64  `thrift:"msg_id,2" frugal:"2,default,i64" json:"msg_id"`
	Version    int32  `thrift:"version,3" frugal:"3,default,i32" json:"version"`
	OldContent string `thrift:"old_content,4" frugal:"4,default,string" json:"old_content"`
	EditorId   int64  `thrift:"editor_id,5" frugal:"5,default,i64" json:"editor_id"`
	EditedAt   int64  `thrift:"edited_at,6" frugal:"6,default,i64" json:"edited_at"`
}

func NewEditHistoryItem() *EditHistoryItem {
	return &EditHistoryItem{}
}

func (p *EditHistoryItem) InitDefault() {
}

func (p *EditHistoryItem) GetId() (v int64) {
	return p.Id
}

func (p *EditHistoryItem) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *EditHistoryItem) GetVersion() (v int32) {
	return p.Version
}

func (p *EditHistoryItem) GetOldContent() (v string) {
	return p.OldContent
}

func (p *EditHistoryItem) GetEditorId() (v int64) {
	return p.EditorId
}

func (p *EditHistoryItem) GetEditedAt() (v int64) {
	return p.EditedAt
}
func (p *EditHistoryItem) SetId(val int64) {
	p.Id = val
}
func (p *EditHistoryItem) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *EditHistoryItem) SetVersion(val int32) {
	p.Version = val
}
func (p *EditHistoryItem) SetOldContent(val string) {
	p.OldContent = val
}
func (p *EditHistoryItem) SetEditorId(val int64) {
	p.EditorId = val
}
func (p *EditHistoryItem) SetEditedAt(val int64) {
	p.EditedAt = val
}

func (p *EditHistoryItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EditHistoryItem(%+v)", *p)
}

var fieldIDToName_EditHistoryItem = map[int16]string{
	1: "id",
	2: "msg_id",
	3: "version",
	4: "old_content",
	5: "editor_id",
	6: "edited_at",
}

type GetEditHistoryReq struct {
	UserId         int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	MsgId          int64 `thrift:"msg_id,2" frugal:"2,default,i64" json:"msg_id"`
	ConversationId int64 `thrift:"conversation_id,3" frugal:"3,default,i64" json:"conversation_id"`
}

func NewGetEditHistoryReq() *GetEditHistoryReq {
	return &GetEditHistoryReq{}
}

func (p *GetEditHistoryReq) InitDefault() {
}

func (p *GetEditHistoryReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetEditHistoryReq) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *GetEditHistoryReq) GetConversationId() (v int64) {
	return p.ConversationId
}
func (p *GetEditHistoryReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetEditHistoryReq) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *GetEditHistoryReq) SetConversationId(val int64) {
	p.ConversationId = val
}

func (p *GetEditHistoryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetEditHistoryReq(%+v)", *p)
}

var fieldIDToName_GetEditHistoryReq = map[int16]string{
	1: "user_id",
	2: "msg_id",
	3: "conversation_id",
}

type GetEditHistoryRes struct {
	Success   bool               `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Histories []*EditHistoryItem `thrift:"histories,2" frugal:"2,default,list<EditHistoryItem>" json:"histories"`
}

func NewGetEditHistoryRes() *GetEditHistoryRes {
	return &GetEditHistoryRes{}
}

func (p *GetEditHistoryRes) InitDefault() {
}

func (p *GetEditHistoryRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetEditHistoryRes) GetHistories() (v []*EditHistoryItem) {
	return p.Histories
}
func (p *GetEditHistoryRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetEditHistoryRes) SetHistories(val []*EditHistoryItem) {
	p.Histories = val
}

func (p *GetEditHistoryRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetEditHistoryRes(%+v)", *p)
}

var fieldIDToName_GetEditHistoryRes = map[int16]string{
	1: "success",
	2: "histories",
}

type ConvSeqPair struct {
	ConversationId int64 `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
	LastSeq        int64 `thrift:"last_seq,2" frugal:"2,default,i64" json:"last_seq"`
}

func NewConvSeqPair() *ConvSeqPair {
	return &ConvSeqPair{}
}

func (p *ConvSeqPair) InitDefault() {
}

func (p *ConvSeqPair) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *ConvSeqPair) GetLastSeq() (v int64) {
	return p.LastSeq
}
func (p *ConvSeqPair) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *ConvSeqPair) SetLastSeq(val int64) {
	p.LastSeq = val
}

func (p *ConvSeqPair) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConvSeqPair(%+v)", *p)
}

var fieldIDToName_ConvSeqPair = map[int16]string{
	1: "conversation_id",
	2: "last_seq",
}

type SyncMessagesReq struct {
	UserId   int64          `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ConvSeqs []*ConvSeqPair `thrift:"conv_seqs,2" frugal:"2,default,list<ConvSeqPair>" json:"conv_seqs"`
	Limit    int16          `thrift:"limit,3" frugal:"3,default,i16" json:"limit"`
}

func NewSyncMessagesReq() *SyncMessagesReq {
	return &SyncMessagesReq{}
}

func (p *SyncMessagesReq) InitDefault() {
}

func (p *SyncMessagesReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SyncMessagesReq) GetConvSeqs() (v []*ConvSeqPair) {
	return p.ConvSeqs
}

func (p *SyncMessagesReq) GetLimit() (v int16) {
	return p.Limit
}
func (p *SyncMessagesReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SyncMessagesReq) SetConvSeqs(val []*ConvSeqPair) {
	p.ConvSeqs = val
}
func (p *SyncMessagesReq) SetLimit(val int16) {
	p.Limit = val
}

func (p *SyncMessagesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SyncMessagesReq(%+v)", *p)
}

var fieldIDToName_SyncMessagesReq = map[int16]string{
	1: "user_id",
	2: "conv_seqs",
	3: "limit",
}

type ConvMessages struct {
	ConversationId int64      `thrift:"conversation_id,1" frugal:"1,default,i64" json:"conversation_id"`
	Messages       []*Message `thrift:"messages,2" frugal:"2,default,list<Message>" json:"messages"`
}

func NewConvMessages() *ConvMessages {
	return &ConvMessages{}
}

func (p *ConvMessages) InitDefault() {
}

func (p *ConvMessages) GetConversationId() (v int64) {
	return p.ConversationId
}

func (p *ConvMessages) GetMessages() (v []*Message) {
	return p.Messages
}
func (p *ConvMessages) SetConversationId(val int64) {
	p.ConversationId = val
}
func (p *ConvMessages) SetMessages(val []*Message) {
	p.Messages = val
}

func (p *ConvMessages) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConvMessages(%+v)", *p)
}

var fieldIDToName_ConvMessages = map[int16]string{
	1: "conversation_id",
	2: "messages",
}

type SyncMessagesRes struct {
	Success      bool            `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	ConvMessages []*ConvMessages `thrift:"conv_messages,2" frugal:"2,default,list<ConvMessages>" json:"conv_messages"`
}

func NewSyncMessagesRes() *SyncMessagesRes {
	return &SyncMessagesRes{}
}

func (p *SyncMessagesRes) InitDefault() {
}

func (p *SyncMessagesRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *SyncMessagesRes) GetConvMessages() (v []*ConvMessages) {
	return p.ConvMessages
}
func (p *SyncMessagesRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *SyncMessagesRes) SetConvMessages(val []*ConvMessages) {
	p.ConvMessages = val
}

func (p *SyncMessagesRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SyncMessagesRes(%+v)", *p)
}

var fieldIDToName_SyncMessagesRes = map[int16]string{
	1: "success",
	2: "conv_messages",
}

type ChatService interface {
	SendMessage(ctx context.Context, req *SendMessageReq) (r *SendMessageRes, err error)

	GetHistory(ctx context.Context, req *GetHistoryReq) (r *GetHistoryRes, err error)

	CreateConversation(ctx context.Context, req *CreateConversationReq) (r *CreateConversationRes, err error)

	GetConversations(ctx context.Context, req *GetConversationsReq) (r *GetConversationsRes, err error)

	SetOnline(ctx context.Context, req *SetOnlineReq) (r *CommonRes, err error)

	SetOffline(ctx context.Context, req *SetOfflineReq) (r *CommonRes, err error)

	RenewOnline(ctx context.Context, req *RenewOnlineReq) (r *CommonRes, err error)

	GetOnlineStatus(ctx context.Context, req *GetOnlineStatusReq) (r *GetOnlineStatusRes, err error)

	AddConversationMembers(ctx context.Context, req *AddConversationMembersReq) (r *AddConversationMembersRes, err error)

	RemoveConversationMembers(ctx context.Context, req *RemoveConversationMembersReq) (r *RemoveConversationMembersRes, err error)

	DeleteConversation(ctx context.Context, req *DeleteConversationReq) (r *DeleteConversationRes, err error)

	MarkRead(ctx context.Context, req *MarkReadReq) (r *MarkReadRes, err error)

	GetConversationMembers(ctx context.Context, req *GetConversationMembersReq) (r *GetConversationMembersRes, err error)

	GetOrCreatePrivateConversation(ctx context.Context, req *GetOrCreatePrivateConversationReq) (r *GetOrCreatePrivateConversationRes, err error)

	RecallMessage(ctx context.Context, req *RecallMessageReq) (r *RecallMessageRes, err error)

	EditMessage(ctx context.Context, req *EditMessageReq) (r *EditMessageRes, err error)

	GetEditHistory(ctx context.Context, req *GetEditHistoryReq) (r *GetEditHistoryRes, err error)

	SyncMessages(ctx context.Context, req *SyncMessagesReq) (r *SyncMessagesRes, err error)
}

type ChatServiceSendMessageArgs struct {
	Req *SendMessageReq `thrift:"req,1" frugal:"1,default,SendMessageReq" json:"req"`
}

func NewChatServiceSendMessageArgs() *ChatServiceSendMessageArgs {
	return &ChatServiceSendMessageArgs{}
}

func (p *ChatServiceSendMessageArgs) InitDefault() {
}

var ChatServiceSendMessageArgs_Req_DEFAULT *SendMessageReq

func (p *ChatServiceSendMessageArgs) GetReq() (v *SendMessageReq) {
	if !p.IsSetReq() {
		return ChatServiceSendMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceSendMessageArgs) SetReq(val *SendMessageReq) {
	p.Req = val
}

func (p *ChatServiceSendMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceSendMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSendMessageArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceSendMessageArgs = map[int16]string{
	1: "req",
}

type ChatServiceSendMessageResult struct {
	Success *SendMessageRes `thrift:"success,0,optional" frugal:"0,optional,SendMessageRes" json:"success,omitempty"`
}

func NewChatServiceSendMessageResult() *ChatServiceSendMessageResult {
	return &ChatServiceSendMessageResult{}
}

func (p *ChatServiceSendMessageResult) InitDefault() {
}

var ChatServiceSendMessageResult_Success_DEFAULT *SendMessageRes

func (p *ChatServiceSendMessageResult) GetSuccess() (v *SendMessageRes) {
	if !p.IsSetSuccess() {
		return ChatServiceSendMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceSendMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendMessageRes)
}

func (p *ChatServiceSendMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceSendMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSendMessageResult(%+v)", *p)
}

var fieldIDToName_ChatServiceSendMessageResult = map[int16]string{
	0: "success",
}

type ChatServiceGetHistoryArgs struct {
	Req *GetHistoryReq `thrift:"req,1" frugal:"1,default,GetHistoryReq" json:"req"`
}

func NewChatServiceGetHistoryArgs() *ChatServiceGetHistoryArgs {
	return &ChatServiceGetHistoryArgs{}
}

func (p *ChatServiceGetHistoryArgs) InitDefault() {
}

var ChatServiceGetHistoryArgs_Req_DEFAULT *GetHistoryReq

func (p *ChatServiceGetHistoryArgs) GetReq() (v *GetHistoryReq) {
	if !p.IsSetReq() {
		return ChatServiceGetHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetHistoryArgs) SetReq(val *GetHistoryReq) {
	p.Req = val
}

func (p *ChatServiceGetHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetHistoryArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetHistoryArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetHistoryResult struct {
	Success *GetHistoryRes `thrift:"success,0,optional" frugal:"0,optional,GetHistoryRes" json:"success,omitempty"`
}

func NewChatServiceGetHistoryResult() *ChatServiceGetHistoryResult {
	return &ChatServiceGetHistoryResult{}
}

func (p *ChatServiceGetHistoryResult) InitDefault() {
}

var ChatServiceGetHistoryResult_Success_DEFAULT *GetHistoryRes

func (p *ChatServiceGetHistoryResult) GetSuccess() (v *GetHistoryRes) {
	if !p.IsSetSuccess() {
		return ChatServiceGetHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetHistoryRes)
}

func (p *ChatServiceGetHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetHistoryResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetHistoryResult = map[int16]string{
	0: "success",
}

type ChatServiceCreateConversationArgs struct {
	Req *CreateConversationReq `thrift:"req,1" frugal:"1,default,CreateConversationReq" json:"req"`
}

func NewChatServiceCreateConversationArgs() *ChatServiceCreateConversationArgs {
	return &ChatServiceCreateConversationArgs{}
}

func (p *ChatServiceCreateConversationArgs) InitDefault() {
}

var ChatServiceCreateConversationArgs_Req_DEFAULT *CreateConversationReq

func (p *ChatServiceCreateConversationArgs) GetReq() (v *CreateConversationReq) {
	if !p.IsSetReq() {
		return ChatServiceCreateConversationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceCreateConversationArgs) SetReq(val *CreateConversationReq) {
	p.Req = val
}

func (p *ChatServiceCreateConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceCreateConversationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceCreateConversationArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceCreateConversationArgs = map[int16]string{
	1: "req",
}

type ChatServiceCreateConversationResult struct {
	Success *CreateConversationRes `thrift:"success,0,optional" frugal:"0,optional,CreateConversationRes" json:"success,omitempty"`
}

func NewChatServiceCreateConversationResult() *ChatServiceCreateConversationResult {
	return &ChatServiceCreateConversationResult{}
}

func (p *ChatServiceCreateConversationResult) InitDefault() {
}

var ChatServiceCreateConversationResult_Success_DEFAULT *CreateConversationRes

func (p *ChatServiceCreateConversationResult) GetSuccess() (v *CreateConversationRes) {
	if !p.IsSetSuccess() {
		return ChatServiceCreateConversationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceCreateConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateConversationRes)
}

func (p *ChatServiceCreateConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceCreateConversationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceCreateConversationResult(%+v)", *p)
}

var fieldIDToName_ChatServiceCreateConversationResult = map[int16]string{
	0: "success",
}

type ChatServiceGetConversationsArgs struct {
	Req *GetConversationsReq `thrift:"req,1" frugal:"1,default,GetConversationsReq" json:"req"`
}

func NewChatServiceGetConversationsArgs() *ChatServiceGetConversationsArgs {
	return &ChatServiceGetConversationsArgs{}
}

func (p *ChatServiceGetConversationsArgs) InitDefault() {
}

var ChatServiceGetConversationsArgs_Req_DEFAULT *GetConversationsReq

func (p *ChatServiceGetConversationsArgs) GetReq() (v *GetConversationsReq) {
	if !p.IsSetReq() {
		return ChatServiceGetConversationsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetConversationsArgs) SetReq(val *GetConversationsReq) {
	p.Req = val
}

func (p *ChatServiceGetConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetConversationsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetConversationsArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetConversationsArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetConversationsResult struct {
	Success *GetConversationsRes `thrift:"success,0,optional" frugal:"0,optional,GetConversationsRes" json:"success,omitempty"`
}

func NewChatServiceGetConversationsResult() *ChatServiceGetConversationsResult {
	return &ChatServiceGetConversationsResult{}
}

func (p *ChatServiceGetConversationsResult) InitDefault() {
}

var ChatServiceGetConversationsResult_Success_DEFAULT *GetConversationsRes

func (p *ChatServiceGetConversationsResult) GetSuccess() (v *GetConversationsRes) {
	if !p.IsSetSuccess() {
		return ChatServiceGetConversationsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetConversationsRes)
}

func (p *ChatServiceGetConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetConversationsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetConversationsResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetConversationsResult = map[int16]string{
	0: "success",
}

type ChatServiceSetOnlineArgs struct {
	Req *SetOnlineReq `thrift:"req,1" frugal:"1,default,SetOnlineReq" json:"req"`
}

func NewChatServiceSetOnlineArgs() *ChatServiceSetOnlineArgs {
	return &ChatServiceSetOnlineArgs{}
}

func (p *ChatServiceSetOnlineArgs) InitDefault() {
}

var ChatServiceSetOnlineArgs_Req_DEFAULT *SetOnlineReq

func (p *ChatServiceSetOnlineArgs) GetReq() (v *SetOnlineReq) {
	if !p.IsSetReq() {
		return ChatServiceSetOnlineArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceSetOnlineArgs) SetReq(val *SetOnlineReq) {
	p.Req = val
}

func (p *ChatServiceSetOnlineArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceSetOnlineArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSetOnlineArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceSetOnlineArgs = map[int16]string{
	1: "req",
}

type ChatServiceSetOnlineResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewChatServiceSetOnlineResult() *ChatServiceSetOnlineResult {
	return &ChatServiceSetOnlineResult{}
}

func (p *ChatServiceSetOnlineResult) InitDefault() {
}

var ChatServiceSetOnlineResult_Success_DEFAULT *CommonRes

func (p *ChatServiceSetOnlineResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return ChatServiceSetOnlineResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceSetOnlineResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *ChatServiceSetOnlineResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceSetOnlineResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSetOnlineResult(%+v)", *p)
}

var fieldIDToName_ChatServiceSetOnlineResult = map[int16]string{
	0: "success",
}

type ChatServiceSetOfflineArgs struct {
	Req *SetOfflineReq `thrift:"req,1" frugal:"1,default,SetOfflineReq" json:"req"`
}

func NewChatServiceSetOfflineArgs() *ChatServiceSetOfflineArgs {
	return &ChatServiceSetOfflineArgs{}
}

func (p *ChatServiceSetOfflineArgs) InitDefault() {
}

var ChatServiceSetOfflineArgs_Req_DEFAULT *SetOfflineReq

func (p *ChatServiceSetOfflineArgs) GetReq() (v *SetOfflineReq) {
	if !p.IsSetReq() {
		return ChatServiceSetOfflineArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceSetOfflineArgs) SetReq(val *SetOfflineReq) {
	p.Req = val
}

func (p *ChatServiceSetOfflineArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceSetOfflineArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSetOfflineArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceSetOfflineArgs = map[int16]string{
	1: "req",
}

type ChatServiceSetOfflineResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewChatServiceSetOfflineResult() *ChatServiceSetOfflineResult {
	return &ChatServiceSetOfflineResult{}
}

func (p *ChatServiceSetOfflineResult) InitDefault() {
}

var ChatServiceSetOfflineResult_Success_DEFAULT *CommonRes

func (p *ChatServiceSetOfflineResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return ChatServiceSetOfflineResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceSetOfflineResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *ChatServiceSetOfflineResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceSetOfflineResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSetOfflineResult(%+v)", *p)
}

var fieldIDToName_ChatServiceSetOfflineResult = map[int16]string{
	0: "success",
}

type ChatServiceRenewOnlineArgs struct {
	Req *RenewOnlineReq `thrift:"req,1" frugal:"1,default,RenewOnlineReq" json:"req"`
}

func NewChatServiceRenewOnlineArgs() *ChatServiceRenewOnlineArgs {
	return &ChatServiceRenewOnlineArgs{}
}

func (p *ChatServiceRenewOnlineArgs) InitDefault() {
}

var ChatServiceRenewOnlineArgs_Req_DEFAULT *RenewOnlineReq

func (p *ChatServiceRenewOnlineArgs) GetReq() (v *RenewOnlineReq) {
	if !p.IsSetReq() {
		return ChatServiceRenewOnlineArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceRenewOnlineArgs) SetReq(val *RenewOnlineReq) {
	p.Req = val
}

func (p *ChatServiceRenewOnlineArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceRenewOnlineArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceRenewOnlineArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceRenewOnlineArgs = map[int16]string{
	1: "req",
}

type ChatServiceRenewOnlineResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewChatServiceRenewOnlineResult() *ChatServiceRenewOnlineResult {
	return &ChatServiceRenewOnlineResult{}
}

func (p *ChatServiceRenewOnlineResult) InitDefault() {
}

var ChatServiceRenewOnlineResult_Success_DEFAULT *CommonRes

func (p *ChatServiceRenewOnlineResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return ChatServiceRenewOnlineResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceRenewOnlineResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *ChatServiceRenewOnlineResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceRenewOnlineResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceRenewOnlineResult(%+v)", *p)
}

var fieldIDToName_ChatServiceRenewOnlineResult = map[int16]string{
	0: "success",
}

type ChatServiceGetOnlineStatusArgs struct {
	Req *GetOnlineStatusReq `thrift:"req,1" frugal:"1,default,GetOnlineStatusReq" json:"req"`
}

func NewChatServiceGetOnlineStatusArgs() *ChatServiceGetOnlineStatusArgs {
	return &ChatServiceGetOnlineStatusArgs{}
}

func (p *ChatServiceGetOnlineStatusArgs) InitDefault() {
}

var ChatServiceGetOnlineStatusArgs_Req_DEFAULT *GetOnlineStatusReq

func (p *ChatServiceGetOnlineStatusArgs) GetReq() (v *GetOnlineStatusReq) {
	if !p.IsSetReq() {
		return ChatServiceGetOnlineStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetOnlineStatusArgs) SetReq(val *GetOnlineStatusReq) {
	p.Req = val
}

func (p *ChatServiceGetOnlineStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetOnlineStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetOnlineStatusArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetOnlineStatusArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetOnlineStatusResult struct {
	Success *GetOnlineStatusRes `thrift:"success,0,optional" frugal:"0,optional,GetOnlineStatusRes" json:"success,omitempty"`
}

func NewChatServiceGetOnlineStatusResult() *ChatServiceGetOnlineStatusResult {
	return &ChatServiceGetOnlineStatusResult{}
}

func (p *ChatServiceGetOnlineStatusResult) InitDefault() {
}

var ChatServiceGetOnlineStatusResult_Success_DEFAULT *GetOnlineStatusRes

func (p *ChatServiceGetOnlineStatusResult) GetSuccess() (v *GetOnlineStatusRes) {
	if !p.IsSetSuccess() {
		return ChatServiceGetOnlineStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetOnlineStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOnlineStatusRes)
}

func (p *ChatServiceGetOnlineStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetOnlineStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetOnlineStatusResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetOnlineStatusResult = map[int16]string{
	0: "success",
}

type ChatServiceAddConversationMembersArgs struct {
	Req *AddConversationMembersReq `thrift:"req,1" frugal:"1,default,AddConversationMembersReq" json:"req"`
}

func NewChatServiceAddConversationMembersArgs() *ChatServiceAddConversationMembersArgs {
	return &ChatServiceAddConversationMembersArgs{}
}

func (p *ChatServiceAddConversationMembersArgs) InitDefault() {
}

var ChatServiceAddConversationMembersArgs_Req_DEFAULT *AddConversationMembersReq

func (p *ChatServiceAddConversationMembersArgs) GetReq() (v *AddConversationMembersReq) {
	if !p.IsSetReq() {
		return ChatServiceAddConversationMembersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceAddConversationMembersArgs) SetReq(val *AddConversationMembersReq) {
	p.Req = val
}

func (p *ChatServiceAddConversationMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceAddConversationMembersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceAddConversationMembersArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceAddConversationMembersArgs = map[int16]string{
	1: "req",
}

type ChatServiceAddConversationMembersResult struct {
	Success *AddConversationMembersRes `thrift:"success,0,optional" frugal:"0,optional,AddConversationMembersRes" json:"success,omitempty"`
}

func NewChatServiceAddConversationMembersResult() *ChatServiceAddConversationMembersResult {
	return &ChatServiceAddConversationMembersResult{}
}

func (p *ChatServiceAddConversationMembersResult) InitDefault() {
}

var ChatServiceAddConversationMembersResult_Success_DEFAULT *AddConversationMembersRes

func (p *ChatServiceAddConversationMembersResult) GetSuccess() (v *AddConversationMembersRes) {
	if !p.IsSetSuccess() {
		return ChatServiceAddConversationMembersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceAddConversationMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddConversationMembersRes)
}

func (p *ChatServiceAddConversationMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceAddConversationMembersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceAddConversationMembersResult(%+v)", *p)
}

var fieldIDToName_ChatServiceAddConversationMembersResult = map[int16]string{
	0: "success",
}

type ChatServiceRemoveConversationMembersArgs struct {
	Req *RemoveConversationMembersReq `thrift:"req,1" frugal:"1,default,RemoveConversationMembersReq" json:"req"`
}

func NewChatServiceRemoveConversationMembersArgs() *ChatServiceRemoveConversationMembersArgs {
	return &ChatServiceRemoveConversationMembersArgs{}
}

func (p *ChatServiceRemoveConversationMembersArgs) InitDefault() {
}

var ChatServiceRemoveConversationMembersArgs_Req_DEFAULT *RemoveConversationMembersReq

func (p *ChatServiceRemoveConversationMembersArgs) GetReq() (v *RemoveConversationMembersReq) {
	if !p.IsSetReq() {
		return ChatServiceRemoveConversationMembersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceRemoveConversationMembersArgs) SetReq(val *RemoveConversationMembersReq) {
	p.Req = val
}

func (p *ChatServiceRemoveConversationMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceRemoveConversationMembersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceRemoveConversationMembersArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceRemoveConversationMembersArgs = map[int16]string{
	1: "req",
}

type ChatServiceRemoveConversationMembersResult struct {
	Success *RemoveConversationMembersRes `thrift:"success,0,optional" frugal:"0,optional,RemoveConversationMembersRes" json:"success,omitempty"`
}

func NewChatServiceRemoveConversationMembersResult() *ChatServiceRemoveConversationMembersResult {
	return &ChatServiceRemoveConversationMembersResult{}
}

func (p *ChatServiceRemoveConversationMembersResult) InitDefault() {
}

var ChatServiceRemoveConversationMembersResult_Success_DEFAULT *RemoveConversationMembersRes

func (p *ChatServiceRemoveConversationMembersResult) GetSuccess() (v *RemoveConversationMembersRes) {
	if !p.IsSetSuccess() {
		return ChatServiceRemoveConversationMembersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceRemoveConversationMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*RemoveConversationMembersRes)
}

func (p *ChatServiceRemoveConversationMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceRemoveConversationMembersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceRemoveConversationMembersResult(%+v)", *p)
}

var fieldIDToName_ChatServiceRemoveConversationMembersResult = map[int16]string{
	0: "success",
}

type ChatServiceDeleteConversationArgs struct {
	Req *DeleteConversationReq `thrift:"req,1" frugal:"1,default,DeleteConversationReq" json:"req"`
}

func NewChatServiceDeleteConversationArgs() *ChatServiceDeleteConversationArgs {
	return &ChatServiceDeleteConversationArgs{}
}

func (p *ChatServiceDeleteConversationArgs) InitDefault() {
}

var ChatServiceDeleteConversationArgs_Req_DEFAULT *DeleteConversationReq

func (p *ChatServiceDeleteConversationArgs) GetReq() (v *DeleteConversationReq) {
	if !p.IsSetReq() {
		return ChatServiceDeleteConversationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceDeleteConversationArgs) SetReq(val *DeleteConversationReq) {
	p.Req = val
}

func (p *ChatServiceDeleteConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceDeleteConversationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceDeleteConversationArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceDeleteConversationArgs = map[int16]string{
	1: "req",
}

type ChatServiceDeleteConversationResult struct {
	Success *DeleteConversationRes `thrift:"success,0,optional" frugal:"0,optional,DeleteConversationRes" json:"success,omitempty"`
}

func NewChatServiceDeleteConversationResult() *ChatServiceDeleteConversationResult {
	return &ChatServiceDeleteConversationResult{}
}

func (p *ChatServiceDeleteConversationResult) InitDefault() {
}

var ChatServiceDeleteConversationResult_Success_DEFAULT *DeleteConversationRes

func (p *ChatServiceDeleteConversationResult) GetSuccess() (v *DeleteConversationRes) {
	if !p.IsSetSuccess() {
		return ChatServiceDeleteConversationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceDeleteConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteConversationRes)
}

func (p *ChatServiceDeleteConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceDeleteConversationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceDeleteConversationResult(%+v)", *p)
}

var fieldIDToName_ChatServiceDeleteConversationResult = map[int16]string{
	0: "success",
}

type ChatServiceMarkReadArgs struct {
	Req *MarkReadReq `thrift:"req,1" frugal:"1,default,MarkReadReq" json:"req"`
}

func NewChatServiceMarkReadArgs() *ChatServiceMarkReadArgs {
	return &ChatServiceMarkReadArgs{}
}

func (p *ChatServiceMarkReadArgs) InitDefault() {
}

var ChatServiceMarkReadArgs_Req_DEFAULT *MarkReadReq

func (p *ChatServiceMarkReadArgs) GetReq() (v *MarkReadReq) {
	if !p.IsSetReq() {
		return ChatServiceMarkReadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceMarkReadArgs) SetReq(val *MarkReadReq) {
	p.Req = val
}

func (p *ChatServiceMarkReadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceMarkReadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceMarkReadArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceMarkReadArgs = map[int16]string{
	1: "req",
}

type ChatServiceMarkReadResult struct {
	Success *MarkReadRes `thrift:"success,0,optional" frugal:"0,optional,MarkReadRes" json:"success,omitempty"`
}

func NewChatServiceMarkReadResult() *ChatServiceMarkReadResult {
	return &ChatServiceMarkReadResult{}
}

func (p *ChatServiceMarkReadResult) InitDefault() {
}

var ChatServiceMarkReadResult_Success_DEFAULT *MarkReadRes

func (p *ChatServiceMarkReadResult) GetSuccess() (v *MarkReadRes) {
	if !p.IsSetSuccess() {
		return ChatServiceMarkReadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceMarkReadResult) SetSuccess(x interface{}) {
	p.Success = x.(*MarkReadRes)
}

func (p *ChatServiceMarkReadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceMarkReadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceMarkReadResult(%+v)", *p)
}

var fieldIDToName_ChatServiceMarkReadResult = map[int16]string{
	0: "success",
}

type ChatServiceGetConversationMembersArgs struct {
	Req *GetConversationMembersReq `thrift:"req,1" frugal:"1,default,GetConversationMembersReq" json:"req"`
}

func NewChatServiceGetConversationMembersArgs() *ChatServiceGetConversationMembersArgs {
	return &ChatServiceGetConversationMembersArgs{}
}

func (p *ChatServiceGetConversationMembersArgs) InitDefault() {
}

var ChatServiceGetConversationMembersArgs_Req_DEFAULT *GetConversationMembersReq

func (p *ChatServiceGetConversationMembersArgs) GetReq() (v *GetConversationMembersReq) {
	if !p.IsSetReq() {
		return ChatServiceGetConversationMembersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetConversationMembersArgs) SetReq(val *GetConversationMembersReq) {
	p.Req = val
}

func (p *ChatServiceGetConversationMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetConversationMembersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetConversationMembersArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetConversationMembersArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetConversationMembersResult struct {
	Success *GetConversationMembersRes `thrift:"success,0,optional" frugal:"0,optional,GetConversationMembersRes" json:"success,omitempty"`
}

func NewChatServiceGetConversationMembersResult() *ChatServiceGetConversationMembersResult {
	return &ChatServiceGetConversationMembersResult{}
}

func (p *ChatServiceGetConversationMembersResult) InitDefault() {
}

var ChatServiceGetConversationMembersResult_Success_DEFAULT *GetConversationMembersRes

func (p *ChatServiceGetConversationMembersResult) GetSuccess() (v *GetConversationMembersRes) {
	if !p.IsSetSuccess() {
		return ChatServiceGetConversationMembersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetConversationMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetConversationMembersRes)
}

func (p *ChatServiceGetConversationMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetConversationMembersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetConversationMembersResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetConversationMembersResult = map[int16]string{
	0: "success",
}

type ChatServiceGetOrCreatePrivateConversationArgs struct {
	Req *GetOrCreatePrivateConversationReq `thrift:"req,1" frugal:"1,default,GetOrCreatePrivateConversationReq" json:"req"`
}

func NewChatServiceGetOrCreatePrivateConversationArgs() *ChatServiceGetOrCreatePrivateConversationArgs {
	return &ChatServiceGetOrCreatePrivateConversationArgs{}
}

func (p *ChatServiceGetOrCreatePrivateConversationArgs) InitDefault() {
}

var ChatServiceGetOrCreatePrivateConversationArgs_Req_DEFAULT *GetOrCreatePrivateConversationReq

func (p *ChatServiceGetOrCreatePrivateConversationArgs) GetReq() (v *GetOrCreatePrivateConversationReq) {
	if !p.IsSetReq() {
		return ChatServiceGetOrCreatePrivateConversationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetOrCreatePrivateConversationArgs) SetReq(val *GetOrCreatePrivateConversationReq) {
	p.Req = val
}

func (p *ChatServiceGetOrCreatePrivateConversationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetOrCreatePrivateConversationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetOrCreatePrivateConversationArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetOrCreatePrivateConversationArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetOrCreatePrivateConversationResult struct {
	Success *GetOrCreatePrivateConversationRes `thrift:"success,0,optional" frugal:"0,optional,GetOrCreatePrivateConversationRes" json:"success,omitempty"`
}

func NewChatServiceGetOrCreatePrivateConversationResult() *ChatServiceGetOrCreatePrivateConversationResult {
	return &ChatServiceGetOrCreatePrivateConversationResult{}
}

func (p *ChatServiceGetOrCreatePrivateConversationResult) InitDefault() {
}

var ChatServiceGetOrCreatePrivateConversationResult_Success_DEFAULT *GetOrCreatePrivateConversationRes

func (p *ChatServiceGetOrCreatePrivateConversationResult) GetSuccess() (v *GetOrCreatePrivateConversationRes) {
	if !p.IsSetSuccess() {
		return ChatServiceGetOrCreatePrivateConversationResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetOrCreatePrivateConversationResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrCreatePrivateConversationRes)
}

func (p *ChatServiceGetOrCreatePrivateConversationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetOrCreatePrivateConversationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetOrCreatePrivateConversationResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetOrCreatePrivateConversationResult = map[int16]string{
	0: "success",
}

type ChatServiceRecallMessageArgs struct {
	Req *RecallMessageReq `thrift:"req,1" frugal:"1,default,RecallMessageReq" json:"req"`
}

func NewChatServiceRecallMessageArgs() *ChatServiceRecallMessageArgs {
	return &ChatServiceRecallMessageArgs{}
}

func (p *ChatServiceRecallMessageArgs) InitDefault() {
}

var ChatServiceRecallMessageArgs_Req_DEFAULT *RecallMessageReq

func (p *ChatServiceRecallMessageArgs) GetReq() (v *RecallMessageReq) {
	if !p.IsSetReq() {
		return ChatServiceRecallMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceRecallMessageArgs) SetReq(val *RecallMessageReq) {
	p.Req = val
}

func (p *ChatServiceRecallMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceRecallMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceRecallMessageArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceRecallMessageArgs = map[int16]string{
	1: "req",
}

type ChatServiceRecallMessageResult struct {
	Success *RecallMessageRes `thrift:"success,0,optional" frugal:"0,optional,RecallMessageRes" json:"success,omitempty"`
}

func NewChatServiceRecallMessageResult() *ChatServiceRecallMessageResult {
	return &ChatServiceRecallMessageResult{}
}

func (p *ChatServiceRecallMessageResult) InitDefault() {
}

var ChatServiceRecallMessageResult_Success_DEFAULT *RecallMessageRes

func (p *ChatServiceRecallMessageResult) GetSuccess() (v *RecallMessageRes) {
	if !p.IsSetSuccess() {
		return ChatServiceRecallMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceRecallMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*RecallMessageRes)
}

func (p *ChatServiceRecallMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceRecallMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceRecallMessageResult(%+v)", *p)
}

var fieldIDToName_ChatServiceRecallMessageResult = map[int16]string{
	0: "success",
}

type ChatServiceEditMessageArgs struct {
	Req *EditMessageReq `thrift:"req,1" frugal:"1,default,EditMessageReq" json:"req"`
}

func NewChatServiceEditMessageArgs() *ChatServiceEditMessageArgs {
	return &ChatServiceEditMessageArgs{}
}

func (p *ChatServiceEditMessageArgs) InitDefault() {
}

var ChatServiceEditMessageArgs_Req_DEFAULT *EditMessageReq

func (p *ChatServiceEditMessageArgs) GetReq() (v *EditMessageReq) {
	if !p.IsSetReq() {
		return ChatServiceEditMessageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceEditMessageArgs) SetReq(val *EditMessageReq) {
	p.Req = val
}

func (p *ChatServiceEditMessageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceEditMessageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceEditMessageArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceEditMessageArgs = map[int16]string{
	1: "req",
}

type ChatServiceEditMessageResult struct {
	Success *EditMessageRes `thrift:"success,0,optional" frugal:"0,optional,EditMessageRes" json:"success,omitempty"`
}

func NewChatServiceEditMessageResult() *ChatServiceEditMessageResult {
	return &ChatServiceEditMessageResult{}
}

func (p *ChatServiceEditMessageResult) InitDefault() {
}

var ChatServiceEditMessageResult_Success_DEFAULT *EditMessageRes

func (p *ChatServiceEditMessageResult) GetSuccess() (v *EditMessageRes) {
	if !p.IsSetSuccess() {
		return ChatServiceEditMessageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceEditMessageResult) SetSuccess(x interface{}) {
	p.Success = x.(*EditMessageRes)
}

func (p *ChatServiceEditMessageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceEditMessageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceEditMessageResult(%+v)", *p)
}

var fieldIDToName_ChatServiceEditMessageResult = map[int16]string{
	0: "success",
}

type ChatServiceGetEditHistoryArgs struct {
	Req *GetEditHistoryReq `thrift:"req,1" frugal:"1,default,GetEditHistoryReq" json:"req"`
}

func NewChatServiceGetEditHistoryArgs() *ChatServiceGetEditHistoryArgs {
	return &ChatServiceGetEditHistoryArgs{}
}

func (p *ChatServiceGetEditHistoryArgs) InitDefault() {
}

var ChatServiceGetEditHistoryArgs_Req_DEFAULT *GetEditHistoryReq

func (p *ChatServiceGetEditHistoryArgs) GetReq() (v *GetEditHistoryReq) {
	if !p.IsSetReq() {
		return ChatServiceGetEditHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceGetEditHistoryArgs) SetReq(val *GetEditHistoryReq) {
	p.Req = val
}

func (p *ChatServiceGetEditHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceGetEditHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetEditHistoryArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceGetEditHistoryArgs = map[int16]string{
	1: "req",
}

type ChatServiceGetEditHistoryResult struct {
	Success *GetEditHistoryRes `thrift:"success,0,optional" frugal:"0,optional,GetEditHistoryRes" json:"success,omitempty"`
}

func NewChatServiceGetEditHistoryResult() *ChatServiceGetEditHistoryResult {
	return &ChatServiceGetEditHistoryResult{}
}

func (p *ChatServiceGetEditHistoryResult) InitDefault() {
}

var ChatServiceGetEditHistoryResult_Success_DEFAULT *GetEditHistoryRes

func (p *ChatServiceGetEditHistoryResult) GetSuccess() (v *GetEditHistoryRes) {
	if !p.IsSetSuccess() {
		return ChatServiceGetEditHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceGetEditHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetEditHistoryRes)
}

func (p *ChatServiceGetEditHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceGetEditHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceGetEditHistoryResult(%+v)", *p)
}

var fieldIDToName_ChatServiceGetEditHistoryResult = map[int16]string{
	0: "success",
}

type ChatServiceSyncMessagesArgs struct {
	Req *SyncMessagesReq `thrift:"req,1" frugal:"1,default,SyncMessagesReq" json:"req"`
}

func NewChatServiceSyncMessagesArgs() *ChatServiceSyncMessagesArgs {
	return &ChatServiceSyncMessagesArgs{}
}

func (p *ChatServiceSyncMessagesArgs) InitDefault() {
}

var ChatServiceSyncMessagesArgs_Req_DEFAULT *SyncMessagesReq

func (p *ChatServiceSyncMessagesArgs) GetReq() (v *SyncMessagesReq) {
	if !p.IsSetReq() {
		return ChatServiceSyncMessagesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatServiceSyncMessagesArgs) SetReq(val *SyncMessagesReq) {
	p.Req = val
}

func (p *ChatServiceSyncMessagesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatServiceSyncMessagesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSyncMessagesArgs(%+v)", *p)
}

var fieldIDToName_ChatServiceSyncMessagesArgs = map[int16]string{
	1: "req",
}

type ChatServiceSyncMessagesResult struct {
	Success *SyncMessagesRes `thrift:"success,0,optional" frugal:"0,optional,SyncMessagesRes" json:"success,omitempty"`
}

func NewChatServiceSyncMessagesResult() *ChatServiceSyncMessagesResult {
	return &ChatServiceSyncMessagesResult{}
}

func (p *ChatServiceSyncMessagesResult) InitDefault() {
}

var ChatServiceSyncMessagesResult_Success_DEFAULT *SyncMessagesRes

func (p *ChatServiceSyncMessagesResult) GetSuccess() (v *SyncMessagesRes) {
	if !p.IsSetSuccess() {
		return ChatServiceSyncMessagesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatServiceSyncMessagesResult) SetSuccess(x interface{}) {
	p.Success = x.(*SyncMessagesRes)
}

func (p *ChatServiceSyncMessagesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatServiceSyncMessagesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatServiceSyncMessagesResult(%+v)", *p)
}

var fieldIDToName_ChatServiceSyncMessagesResult = map[int16]string{
	0: "success",
}
