// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package chat

import (
	"context"
	"fmt"
)

type ChatReq struct {
	Id        int16  `thrift:"id,1" frugal:"1,default,i16" json:"id"`
	SessionId int16  `thrift:"sessionId,2" frugal:"2,default,i16" json:"sessionId"`
	Content   string `thrift:"content,3" frugal:"3,default,string" json:"content"`
	Role      string `thrift:"role,4" frugal:"4,default,string" json:"role"`
}

func NewChatReq() *ChatReq {
	return &ChatReq{}
}

func (p *ChatReq) InitDefault() {
}

func (p *ChatReq) GetId() (v int16) {
	return p.Id
}

func (p *ChatReq) GetSessionId() (v int16) {
	return p.SessionId
}

func (p *ChatReq) GetContent() (v string) {
	return p.Content
}

func (p *ChatReq) GetRole() (v string) {
	return p.Role
}
func (p *ChatReq) SetId(val int16) {
	p.Id = val
}
func (p *ChatReq) SetSessionId(val int16) {
	p.SessionId = val
}
func (p *ChatReq) SetContent(val string) {
	p.Content = val
}
func (p *ChatReq) SetRole(val string) {
	p.Role = val
}

func (p *ChatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatReq(%+v)", *p)
}

var fieldIDToName_ChatReq = map[int16]string{
	1: "id",
	2: "sessionId",
	3: "content",
	4: "role",
}

type ChatHistory struct {
	Id        int16 `thrift:"id,1" frugal:"1,default,i16" json:"id"`
	SessionId int16 `thrift:"sessionId,2" frugal:"2,default,i16" json:"sessionId"`
}

func NewChatHistory() *ChatHistory {
	return &ChatHistory{}
}

func (p *ChatHistory) InitDefault() {
}

func (p *ChatHistory) GetId() (v int16) {
	return p.Id
}

func (p *ChatHistory) GetSessionId() (v int16) {
	return p.SessionId
}
func (p *ChatHistory) SetId(val int16) {
	p.Id = val
}
func (p *ChatHistory) SetSessionId(val int16) {
	p.SessionId = val
}

func (p *ChatHistory) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatHistory(%+v)", *p)
}

var fieldIDToName_ChatHistory = map[int16]string{
	1: "id",
	2: "sessionId",
}

type ChatRecord struct {
	Id        int16  `thrift:"id,1" frugal:"1,default,i16" json:"id"`
	SessionId int16  `thrift:"sessionId,2" frugal:"2,default,i16" json:"sessionId"`
	Question  string `thrift:"question,3" frugal:"3,default,string" json:"question"`
	Answer    string `thrift:"answer,4" frugal:"4,default,string" json:"answer"`
	Time      int64  `thrift:"time,5" frugal:"5,default,i64" json:"time"`
}

func NewChatRecord() *ChatRecord {
	return &ChatRecord{}
}

func (p *ChatRecord) InitDefault() {
}

func (p *ChatRecord) GetId() (v int16) {
	return p.Id
}

func (p *ChatRecord) GetSessionId() (v int16) {
	return p.SessionId
}

func (p *ChatRecord) GetQuestion() (v string) {
	return p.Question
}

func (p *ChatRecord) GetAnswer() (v string) {
	return p.Answer
}

func (p *ChatRecord) GetTime() (v int64) {
	return p.Time
}
func (p *ChatRecord) SetId(val int16) {
	p.Id = val
}
func (p *ChatRecord) SetSessionId(val int16) {
	p.SessionId = val
}
func (p *ChatRecord) SetQuestion(val string) {
	p.Question = val
}
func (p *ChatRecord) SetAnswer(val string) {
	p.Answer = val
}
func (p *ChatRecord) SetTime(val int64) {
	p.Time = val
}

func (p *ChatRecord) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatRecord(%+v)", *p)
}

var fieldIDToName_ChatRecord = map[int16]string{
	1: "id",
	2: "sessionId",
	3: "question",
	4: "answer",
	5: "time",
}

type ChatHistoryRes struct {
	Records     []*ChatRecord `thrift:"records,1" frugal:"1,default,list<ChatRecord>" json:"records"`
	RoleSetting string        `thrift:"role_setting,2" frugal:"2,default,string" json:"role_setting"`
	Title       string        `thrift:"title,3" frugal:"3,default,string" json:"title"`
}

func NewChatHistoryRes() *ChatHistoryRes {
	return &ChatHistoryRes{}
}

func (p *ChatHistoryRes) InitDefault() {
}

func (p *ChatHistoryRes) GetRecords() (v []*ChatRecord) {
	return p.Records
}

func (p *ChatHistoryRes) GetRoleSetting() (v string) {
	return p.RoleSetting
}

func (p *ChatHistoryRes) GetTitle() (v string) {
	return p.Title
}
func (p *ChatHistoryRes) SetRecords(val []*ChatRecord) {
	p.Records = val
}
func (p *ChatHistoryRes) SetRoleSetting(val string) {
	p.RoleSetting = val
}
func (p *ChatHistoryRes) SetTitle(val string) {
	p.Title = val
}

func (p *ChatHistoryRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatHistoryRes(%+v)", *p)
}

var fieldIDToName_ChatHistoryRes = map[int16]string{
	1: "records",
	2: "role_setting",
	3: "title",
}

type ChatRes struct {
	Id        int16  `thrift:"id,1" frugal:"1,default,i16" json:"id"`
	SessionId int16  `thrift:"sessionId,2" frugal:"2,default,i16" json:"sessionId"`
	Content   string `thrift:"content,3" frugal:"3,default,string" json:"content"`
}

func NewChatRes() *ChatRes {
	return &ChatRes{}
}

func (p *ChatRes) InitDefault() {
}

func (p *ChatRes) GetId() (v int16) {
	return p.Id
}

func (p *ChatRes) GetSessionId() (v int16) {
	return p.SessionId
}

func (p *ChatRes) GetContent() (v string) {
	return p.Content
}
func (p *ChatRes) SetId(val int16) {
	p.Id = val
}
func (p *ChatRes) SetSessionId(val int16) {
	p.SessionId = val
}
func (p *ChatRes) SetContent(val string) {
	p.Content = val
}

func (p *ChatRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatRes(%+v)", *p)
}

var fieldIDToName_ChatRes = map[int16]string{
	1: "id",
	2: "sessionId",
	3: "content",
}

type Chat interface {
	Chat(ctx context.Context, req *ChatReq) (r *ChatRes, err error)

	ChatHis(ctx context.Context, req *ChatHistory) (r *ChatHistoryRes, err error)
}

type ChatChatArgs struct {
	Req *ChatReq `thrift:"req,1" frugal:"1,default,ChatReq" json:"req"`
}

func NewChatChatArgs() *ChatChatArgs {
	return &ChatChatArgs{}
}

func (p *ChatChatArgs) InitDefault() {
}

var ChatChatArgs_Req_DEFAULT *ChatReq

func (p *ChatChatArgs) GetReq() (v *ChatReq) {
	if !p.IsSetReq() {
		return ChatChatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatChatArgs) SetReq(val *ChatReq) {
	p.Req = val
}

func (p *ChatChatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatChatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatChatArgs(%+v)", *p)
}

var fieldIDToName_ChatChatArgs = map[int16]string{
	1: "req",
}

type ChatChatResult struct {
	Success *ChatRes `thrift:"success,0,optional" frugal:"0,optional,ChatRes" json:"success,omitempty"`
}

func NewChatChatResult() *ChatChatResult {
	return &ChatChatResult{}
}

func (p *ChatChatResult) InitDefault() {
}

var ChatChatResult_Success_DEFAULT *ChatRes

func (p *ChatChatResult) GetSuccess() (v *ChatRes) {
	if !p.IsSetSuccess() {
		return ChatChatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatRes)
}

func (p *ChatChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatChatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatChatResult(%+v)", *p)
}

var fieldIDToName_ChatChatResult = map[int16]string{
	0: "success",
}

type ChatChatHisArgs struct {
	Req *ChatHistory `thrift:"req,1" frugal:"1,default,ChatHistory" json:"req"`
}

func NewChatChatHisArgs() *ChatChatHisArgs {
	return &ChatChatHisArgs{}
}

func (p *ChatChatHisArgs) InitDefault() {
}

var ChatChatHisArgs_Req_DEFAULT *ChatHistory

func (p *ChatChatHisArgs) GetReq() (v *ChatHistory) {
	if !p.IsSetReq() {
		return ChatChatHisArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ChatChatHisArgs) SetReq(val *ChatHistory) {
	p.Req = val
}

func (p *ChatChatHisArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChatChatHisArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatChatHisArgs(%+v)", *p)
}

var fieldIDToName_ChatChatHisArgs = map[int16]string{
	1: "req",
}

type ChatChatHisResult struct {
	Success *ChatHistoryRes `thrift:"success,0,optional" frugal:"0,optional,ChatHistoryRes" json:"success,omitempty"`
}

func NewChatChatHisResult() *ChatChatHisResult {
	return &ChatChatHisResult{}
}

func (p *ChatChatHisResult) InitDefault() {
}

var ChatChatHisResult_Success_DEFAULT *ChatHistoryRes

func (p *ChatChatHisResult) GetSuccess() (v *ChatHistoryRes) {
	if !p.IsSetSuccess() {
		return ChatChatHisResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ChatChatHisResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatHistoryRes)
}

func (p *ChatChatHisResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChatChatHisResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatChatHisResult(%+v)", *p)
}

var fieldIDToName_ChatChatHisResult = map[int16]string{
	0: "success",
}
