// Code generated by Kitex v0.16.2. DO NOT EDIT.

package workservice

import (
	"context"
	"errors"
	work "github.com/Airiseina/answer/kitex_service/work_service/kitex_gen/work"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"HandleMessage": kitex.NewMethodInfo(
		handleMessageHandler,
		newWorkServiceHandleMessageArgs,
		newWorkServiceHandleMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SummarizeConversation": kitex.NewMethodInfo(
		summarizeConversationHandler,
		newWorkServiceSummarizeConversationArgs,
		newWorkServiceSummarizeConversationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SuggestReplies": kitex.NewMethodInfo(
		suggestRepliesHandler,
		newWorkServiceSuggestRepliesArgs,
		newWorkServiceSuggestRepliesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	workServiceServiceInfo                = NewServiceInfo()
	workServiceServiceInfoForClient       = NewServiceInfoForClient()
	workServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkService"
	handlerType := (*work.WorkService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "work",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func handleMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*work.WorkServiceHandleMessageArgs)
	realResult := result.(*work.WorkServiceHandleMessageResult)
	success, err := handler.(work.WorkService).HandleMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkServiceHandleMessageArgs() interface{} {
	return work.NewWorkServiceHandleMessageArgs()
}

func newWorkServiceHandleMessageResult() interface{} {
	return work.NewWorkServiceHandleMessageResult()
}

func summarizeConversationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*work.WorkServiceSummarizeConversationArgs)
	realResult := result.(*work.WorkServiceSummarizeConversationResult)
	success, err := handler.(work.WorkService).SummarizeConversation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkServiceSummarizeConversationArgs() interface{} {
	return work.NewWorkServiceSummarizeConversationArgs()
}

func newWorkServiceSummarizeConversationResult() interface{} {
	return work.NewWorkServiceSummarizeConversationResult()
}

func suggestRepliesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*work.WorkServiceSuggestRepliesArgs)
	realResult := result.(*work.WorkServiceSuggestRepliesResult)
	success, err := handler.(work.WorkService).SuggestReplies(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newWorkServiceSuggestRepliesArgs() interface{} {
	return work.NewWorkServiceSuggestRepliesArgs()
}

func newWorkServiceSuggestRepliesResult() interface{} {
	return work.NewWorkServiceSuggestRepliesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) HandleMessage(ctx context.Context, req *work.HandleMessageReq) (r *work.HandleMessageRes, err error) {
	var _args work.WorkServiceHandleMessageArgs
	_args.Req = req
	var _result work.WorkServiceHandleMessageResult
	if err = p.c.Call(ctx, "HandleMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SummarizeConversation(ctx context.Context, req *work.SummarizeConversationReq) (r *work.SummarizeConversationRes, err error) {
	var _args work.WorkServiceSummarizeConversationArgs
	_args.Req = req
	var _result work.WorkServiceSummarizeConversationResult
	if err = p.c.Call(ctx, "SummarizeConversation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SuggestReplies(ctx context.Context, req *work.SuggestRepliesReq) (r *work.SuggestRepliesRes, err error) {
	var _args work.WorkServiceSuggestRepliesArgs
	_args.Req = req
	var _result work.WorkServiceSuggestRepliesResult
	if err = p.c.Call(ctx, "SuggestReplies", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
