// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package group

import (
	"context"
	"fmt"
)

type Group struct {
	GroupId     int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	Name        string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	OwnerId     int64  `thrift:"owner_id,3" frugal:"3,default,i64" json:"owner_id"`
	OwnerName   string `thrift:"owner_name,4" frugal:"4,default,string" json:"owner_name"`
	Notice      string `thrift:"notice,5" frugal:"5,default,string" json:"notice"`
	CreateTime  int64  `thrift:"create_time,6" frugal:"6,default,i64" json:"create_time"`
	GroupNumber int64  `thrift:"group_number,7" frugal:"7,default,i64" json:"group_number"`
}

func NewGroup() *Group {
	return &Group{}
}

func (p *Group) InitDefault() {
}

func (p *Group) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *Group) GetName() (v string) {
	return p.Name
}

func (p *Group) GetOwnerId() (v int64) {
	return p.OwnerId
}

func (p *Group) GetOwnerName() (v string) {
	return p.OwnerName
}

func (p *Group) GetNotice() (v string) {
	return p.Notice
}

func (p *Group) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *Group) GetGroupNumber() (v int64) {
	return p.GroupNumber
}
func (p *Group) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *Group) SetName(val string) {
	p.Name = val
}
func (p *Group) SetOwnerId(val int64) {
	p.OwnerId = val
}
func (p *Group) SetOwnerName(val string) {
	p.OwnerName = val
}
func (p *Group) SetNotice(val string) {
	p.Notice = val
}
func (p *Group) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *Group) SetGroupNumber(val int64) {
	p.GroupNumber = val
}

func (p *Group) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Group(%+v)", *p)
}

var fieldIDToName_Group = map[int16]string{
	1: "group_id",
	2: "name",
	3: "owner_id",
	4: "owner_name",
	5: "notice",
	6: "create_time",
	7: "group_number",
}

type GroupMember struct {
	GroupId  int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	UserId   int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Role     int64  `thrift:"role,3" frugal:"3,default,i64" json:"role"`
	IsMuted  bool   `thrift:"is_muted,4" frugal:"4,default,bool" json:"is_muted"`
	JoinTime int64  `thrift:"join_time,5" frugal:"5,default,i64" json:"join_time"`
	Name     string `thrift:"name,6" frugal:"6,default,string" json:"name"`
}

func NewGroupMember() *GroupMember {
	return &GroupMember{}
}

func (p *GroupMember) InitDefault() {
}

func (p *GroupMember) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *GroupMember) GetUserId() (v int64) {
	return p.UserId
}

func (p *GroupMember) GetRole() (v int64) {
	return p.Role
}

func (p *GroupMember) GetIsMuted() (v bool) {
	return p.IsMuted
}

func (p *GroupMember) GetJoinTime() (v int64) {
	return p.JoinTime
}

func (p *GroupMember) GetName() (v string) {
	return p.Name
}
func (p *GroupMember) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *GroupMember) SetUserId(val int64) {
	p.UserId = val
}
func (p *GroupMember) SetRole(val int64) {
	p.Role = val
}
func (p *GroupMember) SetIsMuted(val bool) {
	p.IsMuted = val
}
func (p *GroupMember) SetJoinTime(val int64) {
	p.JoinTime = val
}
func (p *GroupMember) SetName(val string) {
	p.Name = val
}

func (p *GroupMember) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupMember(%+v)", *p)
}

var fieldIDToName_GroupMember = map[int16]string{
	1: "group_id",
	2: "user_id",
	3: "role",
	4: "is_muted",
	5: "join_time",
	6: "name",
}

type CommonRes struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewCommonRes() *CommonRes {
	return &CommonRes{}
}

func (p *CommonRes) InitDefault() {
}

func (p *CommonRes) GetSuccess() (v bool) {
	return p.Success
}
func (p *CommonRes) SetSuccess(val bool) {
	p.Success = val
}

func (p *CommonRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonRes(%+v)", *p)
}

var fieldIDToName_CommonRes = map[int16]string{
	1: "success",
}

type CreateGroupReq struct {
	CreatorId      int64   `thrift:"creator_id,1" frugal:"1,default,i64" json:"creator_id"`
	Name           string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	InitialMembers []int64 `thrift:"initial_members,3" frugal:"3,default,list<i64>" json:"initial_members"`
}

func NewCreateGroupReq() *CreateGroupReq {
	return &CreateGroupReq{}
}

func (p *CreateGroupReq) InitDefault() {
}

func (p *CreateGroupReq) GetCreatorId() (v int64) {
	return p.CreatorId
}

func (p *CreateGroupReq) GetName() (v string) {
	return p.Name
}

func (p *CreateGroupReq) GetInitialMembers() (v []int64) {
	return p.InitialMembers
}
func (p *CreateGroupReq) SetCreatorId(val int64) {
	p.CreatorId = val
}
func (p *CreateGroupReq) SetName(val string) {
	p.Name = val
}
func (p *CreateGroupReq) SetInitialMembers(val []int64) {
	p.InitialMembers = val
}

func (p *CreateGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateGroupReq(%+v)", *p)
}

var fieldIDToName_CreateGroupReq = map[int16]string{
	1: "creator_id",
	2: "name",
	3: "initial_members",
}

type CreateGroupRes struct {
	GroupId     int64 `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	GroupNumber int64 `thrift:"group_number,2" frugal:"2,default,i64" json:"group_number"`
}

func NewCreateGroupRes() *CreateGroupRes {
	return &CreateGroupRes{}
}

func (p *CreateGroupRes) InitDefault() {
}

func (p *CreateGroupRes) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *CreateGroupRes) GetGroupNumber() (v int64) {
	return p.GroupNumber
}
func (p *CreateGroupRes) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *CreateGroupRes) SetGroupNumber(val int64) {
	p.GroupNumber = val
}

func (p *CreateGroupRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateGroupRes(%+v)", *p)
}

var fieldIDToName_CreateGroupRes = map[int16]string{
	1: "group_id",
	2: "group_number",
}

type InviteMembersReq struct {
	InviterId int64   `thrift:"inviter_id,1" frugal:"1,default,i64" json:"inviter_id"`
	GroupId   int64   `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserIds   []int64 `thrift:"user_ids,3" frugal:"3,default,list<i64>" json:"user_ids"`
}

func NewInviteMembersReq() *InviteMembersReq {
	return &InviteMembersReq{}
}

func (p *InviteMembersReq) InitDefault() {
}

func (p *InviteMembersReq) GetInviterId() (v int64) {
	return p.InviterId
}

func (p *InviteMembersReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *InviteMembersReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *InviteMembersReq) SetInviterId(val int64) {
	p.InviterId = val
}
func (p *InviteMembersReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *InviteMembersReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *InviteMembersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InviteMembersReq(%+v)", *p)
}

var fieldIDToName_InviteMembersReq = map[int16]string{
	1: "inviter_id",
	2: "group_id",
	3: "user_ids",
}

type KickMembersReq struct {
	OperatorId int64   `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	GroupId    int64   `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserIds    []int64 `thrift:"user_ids,3" frugal:"3,default,list<i64>" json:"user_ids"`
}

func NewKickMembersReq() *KickMembersReq {
	return &KickMembersReq{}
}

func (p *KickMembersReq) InitDefault() {
}

func (p *KickMembersReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *KickMembersReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *KickMembersReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *KickMembersReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *KickMembersReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *KickMembersReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *KickMembersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KickMembersReq(%+v)", *p)
}

var fieldIDToName_KickMembersReq = map[int16]string{
	1: "operator_id",
	2: "group_id",
	3: "user_ids",
}

type GetGroupInfoReq struct {
	GroupId int64 `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
}

func NewGetGroupInfoReq() *GetGroupInfoReq {
	return &GetGroupInfoReq{}
}

func (p *GetGroupInfoReq) InitDefault() {
}

func (p *GetGroupInfoReq) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *GetGroupInfoReq) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *GetGroupInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGroupInfoReq(%+v)", *p)
}

var fieldIDToName_GetGroupInfoReq = map[int16]string{
	1: "group_id",
}

type GetGroupInfoRes struct {
	Group   *Group         `thrift:"group,1" frugal:"1,default,Group" json:"group"`
	Members []*GroupMember `thrift:"members,2" frugal:"2,default,list<GroupMember>" json:"members"`
}

func NewGetGroupInfoRes() *GetGroupInfoRes {
	return &GetGroupInfoRes{}
}

func (p *GetGroupInfoRes) InitDefault() {
}

var GetGroupInfoRes_Group_DEFAULT *Group

func (p *GetGroupInfoRes) GetGroup() (v *Group) {
	if !p.IsSetGroup() {
		return GetGroupInfoRes_Group_DEFAULT
	}
	return p.Group
}

func (p *GetGroupInfoRes) GetMembers() (v []*GroupMember) {
	return p.Members
}
func (p *GetGroupInfoRes) SetGroup(val *Group) {
	p.Group = val
}
func (p *GetGroupInfoRes) SetMembers(val []*GroupMember) {
	p.Members = val
}

func (p *GetGroupInfoRes) IsSetGroup() bool {
	return p.Group != nil
}

func (p *GetGroupInfoRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetGroupInfoRes(%+v)", *p)
}

var fieldIDToName_GetGroupInfoRes = map[int16]string{
	1: "group",
	2: "members",
}

type ChangeOwnerReq struct {
	OldId   int64 `thrift:"old_id,1" frugal:"1,default,i64" json:"old_id"`
	NewId_  int64 `thrift:"new_id,2" frugal:"2,default,i64" json:"new_id"`
	GroupId int64 `thrift:"group_id,3" frugal:"3,default,i64" json:"group_id"`
}

func NewChangeOwnerReq() *ChangeOwnerReq {
	return &ChangeOwnerReq{}
}

func (p *ChangeOwnerReq) InitDefault() {
}

func (p *ChangeOwnerReq) GetOldId() (v int64) {
	return p.OldId
}

func (p *ChangeOwnerReq) GetNewId_() (v int64) {
	return p.NewId_
}

func (p *ChangeOwnerReq) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *ChangeOwnerReq) SetOldId(val int64) {
	p.OldId = val
}
func (p *ChangeOwnerReq) SetNewId_(val int64) {
	p.NewId_ = val
}
func (p *ChangeOwnerReq) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *ChangeOwnerReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeOwnerReq(%+v)", *p)
}

var fieldIDToName_ChangeOwnerReq = map[int16]string{
	1: "old_id",
	2: "new_id",
	3: "group_id",
}

type ChangeNoticeReq struct {
	OperatorId int64  `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	GroupId    int64  `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	Notice     string `thrift:"notice,3" frugal:"3,default,string" json:"notice"`
}

func NewChangeNoticeReq() *ChangeNoticeReq {
	return &ChangeNoticeReq{}
}

func (p *ChangeNoticeReq) InitDefault() {
}

func (p *ChangeNoticeReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *ChangeNoticeReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *ChangeNoticeReq) GetNotice() (v string) {
	return p.Notice
}
func (p *ChangeNoticeReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *ChangeNoticeReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *ChangeNoticeReq) SetNotice(val string) {
	p.Notice = val
}

func (p *ChangeNoticeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeNoticeReq(%+v)", *p)
}

var fieldIDToName_ChangeNoticeReq = map[int16]string{
	1: "operator_id",
	2: "group_id",
	3: "notice",
}

type MutedReq struct {
	OperatorId int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	GroupId    int64 `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	MutedId    int64 `thrift:"muted_id,3" frugal:"3,default,i64" json:"muted_id"`
	IsMuted    bool  `thrift:"is_muted,4" frugal:"4,default,bool" json:"is_muted"`
}

func NewMutedReq() *MutedReq {
	return &MutedReq{}
}

func (p *MutedReq) InitDefault() {
}

func (p *MutedReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *MutedReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *MutedReq) GetMutedId() (v int64) {
	return p.MutedId
}

func (p *MutedReq) GetIsMuted() (v bool) {
	return p.IsMuted
}
func (p *MutedReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *MutedReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *MutedReq) SetMutedId(val int64) {
	p.MutedId = val
}
func (p *MutedReq) SetIsMuted(val bool) {
	p.IsMuted = val
}

func (p *MutedReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MutedReq(%+v)", *p)
}

var fieldIDToName_MutedReq = map[int16]string{
	1: "operator_id",
	2: "group_id",
	3: "muted_id",
	4: "is_muted",
}

type SetAdminReq struct {
	OperatorId int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	GroupId    int64 `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	TargetId   int64 `thrift:"target_id,3" frugal:"3,default,i64" json:"target_id"`
	Role       int64 `thrift:"role,4" frugal:"4,default,i64" json:"role"`
}

func NewSetAdminReq() *SetAdminReq {
	return &SetAdminReq{}
}

func (p *SetAdminReq) InitDefault() {
}

func (p *SetAdminReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *SetAdminReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *SetAdminReq) GetTargetId() (v int64) {
	return p.TargetId
}

func (p *SetAdminReq) GetRole() (v int64) {
	return p.Role
}
func (p *SetAdminReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *SetAdminReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *SetAdminReq) SetTargetId(val int64) {
	p.TargetId = val
}
func (p *SetAdminReq) SetRole(val int64) {
	p.Role = val
}

func (p *SetAdminReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetAdminReq(%+v)", *p)
}

var fieldIDToName_SetAdminReq = map[int16]string{
	1: "operator_id",
	2: "group_id",
	3: "target_id",
	4: "role",
}

type GetUserGroupsReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserGroupsReq() *GetUserGroupsReq {
	return &GetUserGroupsReq{}
}

func (p *GetUserGroupsReq) InitDefault() {
}

func (p *GetUserGroupsReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserGroupsReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserGroupsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserGroupsReq(%+v)", *p)
}

var fieldIDToName_GetUserGroupsReq = map[int16]string{
	1: "user_id",
}

type UserGroupInfo struct {
	GroupId     int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	Name        string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	GroupNumber int64  `thrift:"group_number,3" frugal:"3,default,i64" json:"group_number"`
}

func NewUserGroupInfo() *UserGroupInfo {
	return &UserGroupInfo{}
}

func (p *UserGroupInfo) InitDefault() {
}

func (p *UserGroupInfo) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *UserGroupInfo) GetName() (v string) {
	return p.Name
}

func (p *UserGroupInfo) GetGroupNumber() (v int64) {
	return p.GroupNumber
}
func (p *UserGroupInfo) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *UserGroupInfo) SetName(val string) {
	p.Name = val
}
func (p *UserGroupInfo) SetGroupNumber(val int64) {
	p.GroupNumber = val
}

func (p *UserGroupInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserGroupInfo(%+v)", *p)
}

var fieldIDToName_UserGroupInfo = map[int16]string{
	1: "group_id",
	2: "name",
	3: "group_number",
}

type GetUserGroupsRes struct {
	Groups []*UserGroupInfo `thrift:"groups,1" frugal:"1,default,list<UserGroupInfo>" json:"groups"`
}

func NewGetUserGroupsRes() *GetUserGroupsRes {
	return &GetUserGroupsRes{}
}

func (p *GetUserGroupsRes) InitDefault() {
}

func (p *GetUserGroupsRes) GetGroups() (v []*UserGroupInfo) {
	return p.Groups
}
func (p *GetUserGroupsRes) SetGroups(val []*UserGroupInfo) {
	p.Groups = val
}

func (p *GetUserGroupsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserGroupsRes(%+v)", *p)
}

var fieldIDToName_GetUserGroupsRes = map[int16]string{
	1: "groups",
}

type SearchGroupByNumberReq struct {
	GroupNumber int64 `thrift:"group_number,1" frugal:"1,default,i64" json:"group_number"`
}

func NewSearchGroupByNumberReq() *SearchGroupByNumberReq {
	return &SearchGroupByNumberReq{}
}

func (p *SearchGroupByNumberReq) InitDefault() {
}

func (p *SearchGroupByNumberReq) GetGroupNumber() (v int64) {
	return p.GroupNumber
}
func (p *SearchGroupByNumberReq) SetGroupNumber(val int64) {
	p.GroupNumber = val
}

func (p *SearchGroupByNumberReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchGroupByNumberReq(%+v)", *p)
}

var fieldIDToName_SearchGroupByNumberReq = map[int16]string{
	1: "group_number",
}

type GroupSearchResult_ struct {
	GroupId     int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	Name        string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	OwnerName   string `thrift:"owner_name,3" frugal:"3,default,string" json:"owner_name"`
	GroupNumber int64  `thrift:"group_number,4" frugal:"4,default,i64" json:"group_number"`
}

func NewGroupSearchResult_() *GroupSearchResult_ {
	return &GroupSearchResult_{}
}

func (p *GroupSearchResult_) InitDefault() {
}

func (p *GroupSearchResult_) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *GroupSearchResult_) GetName() (v string) {
	return p.Name
}

func (p *GroupSearchResult_) GetOwnerName() (v string) {
	return p.OwnerName
}

func (p *GroupSearchResult_) GetGroupNumber() (v int64) {
	return p.GroupNumber
}
func (p *GroupSearchResult_) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *GroupSearchResult_) SetName(val string) {
	p.Name = val
}
func (p *GroupSearchResult_) SetOwnerName(val string) {
	p.OwnerName = val
}
func (p *GroupSearchResult_) SetGroupNumber(val int64) {
	p.GroupNumber = val
}

func (p *GroupSearchResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupSearchResult_(%+v)", *p)
}

var fieldIDToName_GroupSearchResult_ = map[int16]string{
	1: "group_id",
	2: "name",
	3: "owner_name",
	4: "group_number",
}

type SearchGroupByNumberRes struct {
	GroupInfo *GroupSearchResult_ `thrift:"group_info,1" frugal:"1,default,GroupSearchResult_" json:"group_info"`
}

func NewSearchGroupByNumberRes() *SearchGroupByNumberRes {
	return &SearchGroupByNumberRes{}
}

func (p *SearchGroupByNumberRes) InitDefault() {
}

var SearchGroupByNumberRes_GroupInfo_DEFAULT *GroupSearchResult_

func (p *SearchGroupByNumberRes) GetGroupInfo() (v *GroupSearchResult_) {
	if !p.IsSetGroupInfo() {
		return SearchGroupByNumberRes_GroupInfo_DEFAULT
	}
	return p.GroupInfo
}
func (p *SearchGroupByNumberRes) SetGroupInfo(val *GroupSearchResult_) {
	p.GroupInfo = val
}

func (p *SearchGroupByNumberRes) IsSetGroupInfo() bool {
	return p.GroupInfo != nil
}

func (p *SearchGroupByNumberRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchGroupByNumberRes(%+v)", *p)
}

var fieldIDToName_SearchGroupByNumberRes = map[int16]string{
	1: "group_info",
}

type JoinGroupReq struct {
	UserId      int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	GroupNumber int64  `thrift:"group_number,2" frugal:"2,default,i64" json:"group_number"`
	Message     string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewJoinGroupReq() *JoinGroupReq {
	return &JoinGroupReq{}
}

func (p *JoinGroupReq) InitDefault() {
}

func (p *JoinGroupReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *JoinGroupReq) GetGroupNumber() (v int64) {
	return p.GroupNumber
}

func (p *JoinGroupReq) GetMessage() (v string) {
	return p.Message
}
func (p *JoinGroupReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *JoinGroupReq) SetGroupNumber(val int64) {
	p.GroupNumber = val
}
func (p *JoinGroupReq) SetMessage(val string) {
	p.Message = val
}

func (p *JoinGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JoinGroupReq(%+v)", *p)
}

var fieldIDToName_JoinGroupReq = map[int16]string{
	1: "user_id",
	2: "group_number",
	3: "message",
}

type HandleJoinReqReq struct {
	OperatorId int64 `thrift:"operator_id,1" frugal:"1,default,i64" json:"operator_id"`
	GroupId    int64 `thrift:"group_id,2" frugal:"2,default,i64" json:"group_id"`
	UserId     int64 `thrift:"user_id,3" frugal:"3,default,i64" json:"user_id"`
	Accept     bool  `thrift:"accept,4" frugal:"4,default,bool" json:"accept"`
}

func NewHandleJoinReqReq() *HandleJoinReqReq {
	return &HandleJoinReqReq{}
}

func (p *HandleJoinReqReq) InitDefault() {
}

func (p *HandleJoinReqReq) GetOperatorId() (v int64) {
	return p.OperatorId
}

func (p *HandleJoinReqReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *HandleJoinReqReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *HandleJoinReqReq) GetAccept() (v bool) {
	return p.Accept
}
func (p *HandleJoinReqReq) SetOperatorId(val int64) {
	p.OperatorId = val
}
func (p *HandleJoinReqReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *HandleJoinReqReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *HandleJoinReqReq) SetAccept(val bool) {
	p.Accept = val
}

func (p *HandleJoinReqReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HandleJoinReqReq(%+v)", *p)
}

var fieldIDToName_HandleJoinReqReq = map[int16]string{
	1: "operator_id",
	2: "group_id",
	3: "user_id",
	4: "accept",
}

type GetJoinRequestsReq struct {
	GroupId int64 `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
}

func NewGetJoinRequestsReq() *GetJoinRequestsReq {
	return &GetJoinRequestsReq{}
}

func (p *GetJoinRequestsReq) InitDefault() {
}

func (p *GetJoinRequestsReq) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *GetJoinRequestsReq) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *GetJoinRequestsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetJoinRequestsReq(%+v)", *p)
}

var fieldIDToName_GetJoinRequestsReq = map[int16]string{
	1: "group_id",
}

type JoinRequestInfo struct {
	UserId  int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name    string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
	Status  int64  `thrift:"status,4" frugal:"4,default,i64" json:"status"`
}

func NewJoinRequestInfo() *JoinRequestInfo {
	return &JoinRequestInfo{}
}

func (p *JoinRequestInfo) InitDefault() {
}

func (p *JoinRequestInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *JoinRequestInfo) GetName() (v string) {
	return p.Name
}

func (p *JoinRequestInfo) GetMessage() (v string) {
	return p.Message
}

func (p *JoinRequestInfo) GetStatus() (v int64) {
	return p.Status
}
func (p *JoinRequestInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *JoinRequestInfo) SetName(val string) {
	p.Name = val
}
func (p *JoinRequestInfo) SetMessage(val string) {
	p.Message = val
}
func (p *JoinRequestInfo) SetStatus(val int64) {
	p.Status = val
}

func (p *JoinRequestInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JoinRequestInfo(%+v)", *p)
}

var fieldIDToName_JoinRequestInfo = map[int16]string{
	1: "user_id",
	2: "name",
	3: "message",
	4: "status",
}

type GetJoinRequestsRes struct {
	Requests []*JoinRequestInfo `thrift:"requests,1" frugal:"1,default,list<JoinRequestInfo>" json:"requests"`
}

func NewGetJoinRequestsRes() *GetJoinRequestsRes {
	return &GetJoinRequestsRes{}
}

func (p *GetJoinRequestsRes) InitDefault() {
}

func (p *GetJoinRequestsRes) GetRequests() (v []*JoinRequestInfo) {
	return p.Requests
}
func (p *GetJoinRequestsRes) SetRequests(val []*JoinRequestInfo) {
	p.Requests = val
}

func (p *GetJoinRequestsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetJoinRequestsRes(%+v)", *p)
}

var fieldIDToName_GetJoinRequestsRes = map[int16]string{
	1: "requests",
}

type GroupService interface {
	CreateGroup(ctx context.Context, req *CreateGroupReq) (r *CreateGroupRes, err error)

	InviteMembers(ctx context.Context, req *InviteMembersReq) (r *CommonRes, err error)

	KickMembers(ctx context.Context, req *KickMembersReq) (r *CommonRes, err error)

	GetGroupInfo(ctx context.Context, req *GetGroupInfoReq) (r *GetGroupInfoRes, err error)

	ChangeOwner(ctx context.Context, req *ChangeOwnerReq) (r *CommonRes, err error)

	ChangeNotice(ctx context.Context, req *ChangeNoticeReq) (r *CommonRes, err error)

	Muted(ctx context.Context, req *MutedReq) (r *CommonRes, err error)

	SetAdmin(ctx context.Context, req *SetAdminReq) (r *CommonRes, err error)

	GetUserGroups(ctx context.Context, req *GetUserGroupsReq) (r *GetUserGroupsRes, err error)

	SearchGroupByNumber(ctx context.Context, req *SearchGroupByNumberReq) (r *SearchGroupByNumberRes, err error)

	JoinGroup(ctx context.Context, req *JoinGroupReq) (r *CommonRes, err error)

	HandleJoinReq(ctx context.Context, req *HandleJoinReqReq) (r *CommonRes, err error)

	GetJoinRequests(ctx context.Context, req *GetJoinRequestsReq) (r *GetJoinRequestsRes, err error)
}

type GroupServiceCreateGroupArgs struct {
	Req *CreateGroupReq `thrift:"req,1" frugal:"1,default,CreateGroupReq" json:"req"`
}

func NewGroupServiceCreateGroupArgs() *GroupServiceCreateGroupArgs {
	return &GroupServiceCreateGroupArgs{}
}

func (p *GroupServiceCreateGroupArgs) InitDefault() {
}

var GroupServiceCreateGroupArgs_Req_DEFAULT *CreateGroupReq

func (p *GroupServiceCreateGroupArgs) GetReq() (v *CreateGroupReq) {
	if !p.IsSetReq() {
		return GroupServiceCreateGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceCreateGroupArgs) SetReq(val *CreateGroupReq) {
	p.Req = val
}

func (p *GroupServiceCreateGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceCreateGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceCreateGroupArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceCreateGroupArgs = map[int16]string{
	1: "req",
}

type GroupServiceCreateGroupResult struct {
	Success *CreateGroupRes `thrift:"success,0,optional" frugal:"0,optional,CreateGroupRes" json:"success,omitempty"`
}

func NewGroupServiceCreateGroupResult() *GroupServiceCreateGroupResult {
	return &GroupServiceCreateGroupResult{}
}

func (p *GroupServiceCreateGroupResult) InitDefault() {
}

var GroupServiceCreateGroupResult_Success_DEFAULT *CreateGroupRes

func (p *GroupServiceCreateGroupResult) GetSuccess() (v *CreateGroupRes) {
	if !p.IsSetSuccess() {
		return GroupServiceCreateGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceCreateGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateGroupRes)
}

func (p *GroupServiceCreateGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceCreateGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceCreateGroupResult(%+v)", *p)
}

var fieldIDToName_GroupServiceCreateGroupResult = map[int16]string{
	0: "success",
}

type GroupServiceInviteMembersArgs struct {
	Req *InviteMembersReq `thrift:"req,1" frugal:"1,default,InviteMembersReq" json:"req"`
}

func NewGroupServiceInviteMembersArgs() *GroupServiceInviteMembersArgs {
	return &GroupServiceInviteMembersArgs{}
}

func (p *GroupServiceInviteMembersArgs) InitDefault() {
}

var GroupServiceInviteMembersArgs_Req_DEFAULT *InviteMembersReq

func (p *GroupServiceInviteMembersArgs) GetReq() (v *InviteMembersReq) {
	if !p.IsSetReq() {
		return GroupServiceInviteMembersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceInviteMembersArgs) SetReq(val *InviteMembersReq) {
	p.Req = val
}

func (p *GroupServiceInviteMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceInviteMembersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceInviteMembersArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceInviteMembersArgs = map[int16]string{
	1: "req",
}

type GroupServiceInviteMembersResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceInviteMembersResult() *GroupServiceInviteMembersResult {
	return &GroupServiceInviteMembersResult{}
}

func (p *GroupServiceInviteMembersResult) InitDefault() {
}

var GroupServiceInviteMembersResult_Success_DEFAULT *CommonRes

func (p *GroupServiceInviteMembersResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceInviteMembersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceInviteMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceInviteMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceInviteMembersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceInviteMembersResult(%+v)", *p)
}

var fieldIDToName_GroupServiceInviteMembersResult = map[int16]string{
	0: "success",
}

type GroupServiceKickMembersArgs struct {
	Req *KickMembersReq `thrift:"req,1" frugal:"1,default,KickMembersReq" json:"req"`
}

func NewGroupServiceKickMembersArgs() *GroupServiceKickMembersArgs {
	return &GroupServiceKickMembersArgs{}
}

func (p *GroupServiceKickMembersArgs) InitDefault() {
}

var GroupServiceKickMembersArgs_Req_DEFAULT *KickMembersReq

func (p *GroupServiceKickMembersArgs) GetReq() (v *KickMembersReq) {
	if !p.IsSetReq() {
		return GroupServiceKickMembersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceKickMembersArgs) SetReq(val *KickMembersReq) {
	p.Req = val
}

func (p *GroupServiceKickMembersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceKickMembersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceKickMembersArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceKickMembersArgs = map[int16]string{
	1: "req",
}

type GroupServiceKickMembersResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceKickMembersResult() *GroupServiceKickMembersResult {
	return &GroupServiceKickMembersResult{}
}

func (p *GroupServiceKickMembersResult) InitDefault() {
}

var GroupServiceKickMembersResult_Success_DEFAULT *CommonRes

func (p *GroupServiceKickMembersResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceKickMembersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceKickMembersResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceKickMembersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceKickMembersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceKickMembersResult(%+v)", *p)
}

var fieldIDToName_GroupServiceKickMembersResult = map[int16]string{
	0: "success",
}

type GroupServiceGetGroupInfoArgs struct {
	Req *GetGroupInfoReq `thrift:"req,1" frugal:"1,default,GetGroupInfoReq" json:"req"`
}

func NewGroupServiceGetGroupInfoArgs() *GroupServiceGetGroupInfoArgs {
	return &GroupServiceGetGroupInfoArgs{}
}

func (p *GroupServiceGetGroupInfoArgs) InitDefault() {
}

var GroupServiceGetGroupInfoArgs_Req_DEFAULT *GetGroupInfoReq

func (p *GroupServiceGetGroupInfoArgs) GetReq() (v *GetGroupInfoReq) {
	if !p.IsSetReq() {
		return GroupServiceGetGroupInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceGetGroupInfoArgs) SetReq(val *GetGroupInfoReq) {
	p.Req = val
}

func (p *GroupServiceGetGroupInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceGetGroupInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceGetGroupInfoArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceGetGroupInfoArgs = map[int16]string{
	1: "req",
}

type GroupServiceGetGroupInfoResult struct {
	Success *GetGroupInfoRes `thrift:"success,0,optional" frugal:"0,optional,GetGroupInfoRes" json:"success,omitempty"`
}

func NewGroupServiceGetGroupInfoResult() *GroupServiceGetGroupInfoResult {
	return &GroupServiceGetGroupInfoResult{}
}

func (p *GroupServiceGetGroupInfoResult) InitDefault() {
}

var GroupServiceGetGroupInfoResult_Success_DEFAULT *GetGroupInfoRes

func (p *GroupServiceGetGroupInfoResult) GetSuccess() (v *GetGroupInfoRes) {
	if !p.IsSetSuccess() {
		return GroupServiceGetGroupInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceGetGroupInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetGroupInfoRes)
}

func (p *GroupServiceGetGroupInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceGetGroupInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceGetGroupInfoResult(%+v)", *p)
}

var fieldIDToName_GroupServiceGetGroupInfoResult = map[int16]string{
	0: "success",
}

type GroupServiceChangeOwnerArgs struct {
	Req *ChangeOwnerReq `thrift:"req,1" frugal:"1,default,ChangeOwnerReq" json:"req"`
}

func NewGroupServiceChangeOwnerArgs() *GroupServiceChangeOwnerArgs {
	return &GroupServiceChangeOwnerArgs{}
}

func (p *GroupServiceChangeOwnerArgs) InitDefault() {
}

var GroupServiceChangeOwnerArgs_Req_DEFAULT *ChangeOwnerReq

func (p *GroupServiceChangeOwnerArgs) GetReq() (v *ChangeOwnerReq) {
	if !p.IsSetReq() {
		return GroupServiceChangeOwnerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceChangeOwnerArgs) SetReq(val *ChangeOwnerReq) {
	p.Req = val
}

func (p *GroupServiceChangeOwnerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceChangeOwnerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceChangeOwnerArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceChangeOwnerArgs = map[int16]string{
	1: "req",
}

type GroupServiceChangeOwnerResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceChangeOwnerResult() *GroupServiceChangeOwnerResult {
	return &GroupServiceChangeOwnerResult{}
}

func (p *GroupServiceChangeOwnerResult) InitDefault() {
}

var GroupServiceChangeOwnerResult_Success_DEFAULT *CommonRes

func (p *GroupServiceChangeOwnerResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceChangeOwnerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceChangeOwnerResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceChangeOwnerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceChangeOwnerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceChangeOwnerResult(%+v)", *p)
}

var fieldIDToName_GroupServiceChangeOwnerResult = map[int16]string{
	0: "success",
}

type GroupServiceChangeNoticeArgs struct {
	Req *ChangeNoticeReq `thrift:"req,1" frugal:"1,default,ChangeNoticeReq" json:"req"`
}

func NewGroupServiceChangeNoticeArgs() *GroupServiceChangeNoticeArgs {
	return &GroupServiceChangeNoticeArgs{}
}

func (p *GroupServiceChangeNoticeArgs) InitDefault() {
}

var GroupServiceChangeNoticeArgs_Req_DEFAULT *ChangeNoticeReq

func (p *GroupServiceChangeNoticeArgs) GetReq() (v *ChangeNoticeReq) {
	if !p.IsSetReq() {
		return GroupServiceChangeNoticeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceChangeNoticeArgs) SetReq(val *ChangeNoticeReq) {
	p.Req = val
}

func (p *GroupServiceChangeNoticeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceChangeNoticeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceChangeNoticeArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceChangeNoticeArgs = map[int16]string{
	1: "req",
}

type GroupServiceChangeNoticeResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceChangeNoticeResult() *GroupServiceChangeNoticeResult {
	return &GroupServiceChangeNoticeResult{}
}

func (p *GroupServiceChangeNoticeResult) InitDefault() {
}

var GroupServiceChangeNoticeResult_Success_DEFAULT *CommonRes

func (p *GroupServiceChangeNoticeResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceChangeNoticeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceChangeNoticeResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceChangeNoticeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceChangeNoticeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceChangeNoticeResult(%+v)", *p)
}

var fieldIDToName_GroupServiceChangeNoticeResult = map[int16]string{
	0: "success",
}

type GroupServiceMutedArgs struct {
	Req *MutedReq `thrift:"req,1" frugal:"1,default,MutedReq" json:"req"`
}

func NewGroupServiceMutedArgs() *GroupServiceMutedArgs {
	return &GroupServiceMutedArgs{}
}

func (p *GroupServiceMutedArgs) InitDefault() {
}

var GroupServiceMutedArgs_Req_DEFAULT *MutedReq

func (p *GroupServiceMutedArgs) GetReq() (v *MutedReq) {
	if !p.IsSetReq() {
		return GroupServiceMutedArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceMutedArgs) SetReq(val *MutedReq) {
	p.Req = val
}

func (p *GroupServiceMutedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceMutedArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceMutedArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceMutedArgs = map[int16]string{
	1: "req",
}

type GroupServiceMutedResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceMutedResult() *GroupServiceMutedResult {
	return &GroupServiceMutedResult{}
}

func (p *GroupServiceMutedResult) InitDefault() {
}

var GroupServiceMutedResult_Success_DEFAULT *CommonRes

func (p *GroupServiceMutedResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceMutedResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceMutedResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceMutedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceMutedResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceMutedResult(%+v)", *p)
}

var fieldIDToName_GroupServiceMutedResult = map[int16]string{
	0: "success",
}

type GroupServiceSetAdminArgs struct {
	Req *SetAdminReq `thrift:"req,1" frugal:"1,default,SetAdminReq" json:"req"`
}

func NewGroupServiceSetAdminArgs() *GroupServiceSetAdminArgs {
	return &GroupServiceSetAdminArgs{}
}

func (p *GroupServiceSetAdminArgs) InitDefault() {
}

var GroupServiceSetAdminArgs_Req_DEFAULT *SetAdminReq

func (p *GroupServiceSetAdminArgs) GetReq() (v *SetAdminReq) {
	if !p.IsSetReq() {
		return GroupServiceSetAdminArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceSetAdminArgs) SetReq(val *SetAdminReq) {
	p.Req = val
}

func (p *GroupServiceSetAdminArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceSetAdminArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceSetAdminArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceSetAdminArgs = map[int16]string{
	1: "req",
}

type GroupServiceSetAdminResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceSetAdminResult() *GroupServiceSetAdminResult {
	return &GroupServiceSetAdminResult{}
}

func (p *GroupServiceSetAdminResult) InitDefault() {
}

var GroupServiceSetAdminResult_Success_DEFAULT *CommonRes

func (p *GroupServiceSetAdminResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceSetAdminResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceSetAdminResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceSetAdminResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceSetAdminResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceSetAdminResult(%+v)", *p)
}

var fieldIDToName_GroupServiceSetAdminResult = map[int16]string{
	0: "success",
}

type GroupServiceGetUserGroupsArgs struct {
	Req *GetUserGroupsReq `thrift:"req,1" frugal:"1,default,GetUserGroupsReq" json:"req"`
}

func NewGroupServiceGetUserGroupsArgs() *GroupServiceGetUserGroupsArgs {
	return &GroupServiceGetUserGroupsArgs{}
}

func (p *GroupServiceGetUserGroupsArgs) InitDefault() {
}

var GroupServiceGetUserGroupsArgs_Req_DEFAULT *GetUserGroupsReq

func (p *GroupServiceGetUserGroupsArgs) GetReq() (v *GetUserGroupsReq) {
	if !p.IsSetReq() {
		return GroupServiceGetUserGroupsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceGetUserGroupsArgs) SetReq(val *GetUserGroupsReq) {
	p.Req = val
}

func (p *GroupServiceGetUserGroupsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceGetUserGroupsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceGetUserGroupsArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceGetUserGroupsArgs = map[int16]string{
	1: "req",
}

type GroupServiceGetUserGroupsResult struct {
	Success *GetUserGroupsRes `thrift:"success,0,optional" frugal:"0,optional,GetUserGroupsRes" json:"success,omitempty"`
}

func NewGroupServiceGetUserGroupsResult() *GroupServiceGetUserGroupsResult {
	return &GroupServiceGetUserGroupsResult{}
}

func (p *GroupServiceGetUserGroupsResult) InitDefault() {
}

var GroupServiceGetUserGroupsResult_Success_DEFAULT *GetUserGroupsRes

func (p *GroupServiceGetUserGroupsResult) GetSuccess() (v *GetUserGroupsRes) {
	if !p.IsSetSuccess() {
		return GroupServiceGetUserGroupsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceGetUserGroupsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserGroupsRes)
}

func (p *GroupServiceGetUserGroupsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceGetUserGroupsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceGetUserGroupsResult(%+v)", *p)
}

var fieldIDToName_GroupServiceGetUserGroupsResult = map[int16]string{
	0: "success",
}

type GroupServiceSearchGroupByNumberArgs struct {
	Req *SearchGroupByNumberReq `thrift:"req,1" frugal:"1,default,SearchGroupByNumberReq" json:"req"`
}

func NewGroupServiceSearchGroupByNumberArgs() *GroupServiceSearchGroupByNumberArgs {
	return &GroupServiceSearchGroupByNumberArgs{}
}

func (p *GroupServiceSearchGroupByNumberArgs) InitDefault() {
}

var GroupServiceSearchGroupByNumberArgs_Req_DEFAULT *SearchGroupByNumberReq

func (p *GroupServiceSearchGroupByNumberArgs) GetReq() (v *SearchGroupByNumberReq) {
	if !p.IsSetReq() {
		return GroupServiceSearchGroupByNumberArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceSearchGroupByNumberArgs) SetReq(val *SearchGroupByNumberReq) {
	p.Req = val
}

func (p *GroupServiceSearchGroupByNumberArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceSearchGroupByNumberArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceSearchGroupByNumberArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceSearchGroupByNumberArgs = map[int16]string{
	1: "req",
}

type GroupServiceSearchGroupByNumberResult struct {
	Success *SearchGroupByNumberRes `thrift:"success,0,optional" frugal:"0,optional,SearchGroupByNumberRes" json:"success,omitempty"`
}

func NewGroupServiceSearchGroupByNumberResult() *GroupServiceSearchGroupByNumberResult {
	return &GroupServiceSearchGroupByNumberResult{}
}

func (p *GroupServiceSearchGroupByNumberResult) InitDefault() {
}

var GroupServiceSearchGroupByNumberResult_Success_DEFAULT *SearchGroupByNumberRes

func (p *GroupServiceSearchGroupByNumberResult) GetSuccess() (v *SearchGroupByNumberRes) {
	if !p.IsSetSuccess() {
		return GroupServiceSearchGroupByNumberResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceSearchGroupByNumberResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchGroupByNumberRes)
}

func (p *GroupServiceSearchGroupByNumberResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceSearchGroupByNumberResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceSearchGroupByNumberResult(%+v)", *p)
}

var fieldIDToName_GroupServiceSearchGroupByNumberResult = map[int16]string{
	0: "success",
}

type GroupServiceJoinGroupArgs struct {
	Req *JoinGroupReq `thrift:"req,1" frugal:"1,default,JoinGroupReq" json:"req"`
}

func NewGroupServiceJoinGroupArgs() *GroupServiceJoinGroupArgs {
	return &GroupServiceJoinGroupArgs{}
}

func (p *GroupServiceJoinGroupArgs) InitDefault() {
}

var GroupServiceJoinGroupArgs_Req_DEFAULT *JoinGroupReq

func (p *GroupServiceJoinGroupArgs) GetReq() (v *JoinGroupReq) {
	if !p.IsSetReq() {
		return GroupServiceJoinGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceJoinGroupArgs) SetReq(val *JoinGroupReq) {
	p.Req = val
}

func (p *GroupServiceJoinGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceJoinGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceJoinGroupArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceJoinGroupArgs = map[int16]string{
	1: "req",
}

type GroupServiceJoinGroupResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceJoinGroupResult() *GroupServiceJoinGroupResult {
	return &GroupServiceJoinGroupResult{}
}

func (p *GroupServiceJoinGroupResult) InitDefault() {
}

var GroupServiceJoinGroupResult_Success_DEFAULT *CommonRes

func (p *GroupServiceJoinGroupResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceJoinGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceJoinGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceJoinGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceJoinGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceJoinGroupResult(%+v)", *p)
}

var fieldIDToName_GroupServiceJoinGroupResult = map[int16]string{
	0: "success",
}

type GroupServiceHandleJoinReqArgs struct {
	Req *HandleJoinReqReq `thrift:"req,1" frugal:"1,default,HandleJoinReqReq" json:"req"`
}

func NewGroupServiceHandleJoinReqArgs() *GroupServiceHandleJoinReqArgs {
	return &GroupServiceHandleJoinReqArgs{}
}

func (p *GroupServiceHandleJoinReqArgs) InitDefault() {
}

var GroupServiceHandleJoinReqArgs_Req_DEFAULT *HandleJoinReqReq

func (p *GroupServiceHandleJoinReqArgs) GetReq() (v *HandleJoinReqReq) {
	if !p.IsSetReq() {
		return GroupServiceHandleJoinReqArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceHandleJoinReqArgs) SetReq(val *HandleJoinReqReq) {
	p.Req = val
}

func (p *GroupServiceHandleJoinReqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceHandleJoinReqArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceHandleJoinReqArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceHandleJoinReqArgs = map[int16]string{
	1: "req",
}

type GroupServiceHandleJoinReqResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewGroupServiceHandleJoinReqResult() *GroupServiceHandleJoinReqResult {
	return &GroupServiceHandleJoinReqResult{}
}

func (p *GroupServiceHandleJoinReqResult) InitDefault() {
}

var GroupServiceHandleJoinReqResult_Success_DEFAULT *CommonRes

func (p *GroupServiceHandleJoinReqResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return GroupServiceHandleJoinReqResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceHandleJoinReqResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *GroupServiceHandleJoinReqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceHandleJoinReqResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceHandleJoinReqResult(%+v)", *p)
}

var fieldIDToName_GroupServiceHandleJoinReqResult = map[int16]string{
	0: "success",
}

type GroupServiceGetJoinRequestsArgs struct {
	Req *GetJoinRequestsReq `thrift:"req,1" frugal:"1,default,GetJoinRequestsReq" json:"req"`
}

func NewGroupServiceGetJoinRequestsArgs() *GroupServiceGetJoinRequestsArgs {
	return &GroupServiceGetJoinRequestsArgs{}
}

func (p *GroupServiceGetJoinRequestsArgs) InitDefault() {
}

var GroupServiceGetJoinRequestsArgs_Req_DEFAULT *GetJoinRequestsReq

func (p *GroupServiceGetJoinRequestsArgs) GetReq() (v *GetJoinRequestsReq) {
	if !p.IsSetReq() {
		return GroupServiceGetJoinRequestsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *GroupServiceGetJoinRequestsArgs) SetReq(val *GetJoinRequestsReq) {
	p.Req = val
}

func (p *GroupServiceGetJoinRequestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GroupServiceGetJoinRequestsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceGetJoinRequestsArgs(%+v)", *p)
}

var fieldIDToName_GroupServiceGetJoinRequestsArgs = map[int16]string{
	1: "req",
}

type GroupServiceGetJoinRequestsResult struct {
	Success *GetJoinRequestsRes `thrift:"success,0,optional" frugal:"0,optional,GetJoinRequestsRes" json:"success,omitempty"`
}

func NewGroupServiceGetJoinRequestsResult() *GroupServiceGetJoinRequestsResult {
	return &GroupServiceGetJoinRequestsResult{}
}

func (p *GroupServiceGetJoinRequestsResult) InitDefault() {
}

var GroupServiceGetJoinRequestsResult_Success_DEFAULT *GetJoinRequestsRes

func (p *GroupServiceGetJoinRequestsResult) GetSuccess() (v *GetJoinRequestsRes) {
	if !p.IsSetSuccess() {
		return GroupServiceGetJoinRequestsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *GroupServiceGetJoinRequestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetJoinRequestsRes)
}

func (p *GroupServiceGetJoinRequestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GroupServiceGetJoinRequestsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupServiceGetJoinRequestsResult(%+v)", *p)
}

var fieldIDToName_GroupServiceGetJoinRequestsResult = map[int16]string{
	0: "success",
}
