// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type RegisterReq struct {
	Account  string `thrift:"account,1" frugal:"1,default,string" json:"account"`
	Name     string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetAccount() (v string) {
	return p.Account
}

func (p *RegisterReq) GetName() (v string) {
	return p.Name
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterReq) SetAccount(val string) {
	p.Account = val
}
func (p *RegisterReq) SetName(val string) {
	p.Name = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "account",
	2: "name",
	3: "password",
}

type RegisterRes struct {
	IsExit bool `thrift:"isExit,1" frugal:"1,default,bool" json:"isExit"`
}

func NewRegisterRes() *RegisterRes {
	return &RegisterRes{}
}

func (p *RegisterRes) InitDefault() {
}

func (p *RegisterRes) GetIsExit() (v bool) {
	return p.IsExit
}
func (p *RegisterRes) SetIsExit(val bool) {
	p.IsExit = val
}

func (p *RegisterRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRes(%+v)", *p)
}

var fieldIDToName_RegisterRes = map[int16]string{
	1: "isExit",
}

type LoginReq struct {
	Account  string `thrift:"account,1" frugal:"1,default,string" json:"account"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetAccount() (v string) {
	return p.Account
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetAccount(val string) {
	p.Account = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "account",
	2: "password",
}

type LoginRes struct {
	Id      int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Account string `thrift:"account,2" frugal:"2,default,string" json:"account"`
}

func NewLoginRes() *LoginRes {
	return &LoginRes{}
}

func (p *LoginRes) InitDefault() {
}

func (p *LoginRes) GetId() (v int64) {
	return p.Id
}

func (p *LoginRes) GetAccount() (v string) {
	return p.Account
}
func (p *LoginRes) SetId(val int64) {
	p.Id = val
}
func (p *LoginRes) SetAccount(val string) {
	p.Account = val
}

func (p *LoginRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRes(%+v)", *p)
}

var fieldIDToName_LoginRes = map[int16]string{
	1: "id",
	2: "account",
}

type CheckUsersExistReq struct {
	UserIds []int64 `thrift:"userIds,1" frugal:"1,default,list<i64>" json:"userIds"`
}

func NewCheckUsersExistReq() *CheckUsersExistReq {
	return &CheckUsersExistReq{}
}

func (p *CheckUsersExistReq) InitDefault() {
}

func (p *CheckUsersExistReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *CheckUsersExistReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *CheckUsersExistReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckUsersExistReq(%+v)", *p)
}

var fieldIDToName_CheckUsersExistReq = map[int16]string{
	1: "userIds",
}

type CheckUsersExistRes struct {
	AllExist bool `thrift:"allExist,1" frugal:"1,default,bool" json:"allExist"`
}

func NewCheckUsersExistRes() *CheckUsersExistRes {
	return &CheckUsersExistRes{}
}

func (p *CheckUsersExistRes) InitDefault() {
}

func (p *CheckUsersExistRes) GetAllExist() (v bool) {
	return p.AllExist
}
func (p *CheckUsersExistRes) SetAllExist(val bool) {
	p.AllExist = val
}

func (p *CheckUsersExistRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckUsersExistRes(%+v)", *p)
}

var fieldIDToName_CheckUsersExistRes = map[int16]string{
	1: "allExist",
}

type LoginService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterRes, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginRes, err error)

	CheckUsersExist(ctx context.Context, req *CheckUsersExistReq) (r *CheckUsersExistRes, err error)
}

type LoginServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewLoginServiceRegisterArgs() *LoginServiceRegisterArgs {
	return &LoginServiceRegisterArgs{}
}

func (p *LoginServiceRegisterArgs) InitDefault() {
}

var LoginServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *LoginServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return LoginServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *LoginServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceRegisterArgs = map[int16]string{
	1: "req",
}

type LoginServiceRegisterResult struct {
	Success *RegisterRes `thrift:"success,0,optional" frugal:"0,optional,RegisterRes" json:"success,omitempty"`
}

func NewLoginServiceRegisterResult() *LoginServiceRegisterResult {
	return &LoginServiceRegisterResult{}
}

func (p *LoginServiceRegisterResult) InitDefault() {
}

var LoginServiceRegisterResult_Success_DEFAULT *RegisterRes

func (p *LoginServiceRegisterResult) GetSuccess() (v *RegisterRes) {
	if !p.IsSetSuccess() {
		return LoginServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterRes)
}

func (p *LoginServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_LoginServiceRegisterResult = map[int16]string{
	0: "success",
}

type LoginServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewLoginServiceLoginArgs() *LoginServiceLoginArgs {
	return &LoginServiceLoginArgs{}
}

func (p *LoginServiceLoginArgs) InitDefault() {
}

var LoginServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *LoginServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return LoginServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *LoginServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceLoginArgs = map[int16]string{
	1: "req",
}

type LoginServiceLoginResult struct {
	Success *LoginRes `thrift:"success,0,optional" frugal:"0,optional,LoginRes" json:"success,omitempty"`
}

func NewLoginServiceLoginResult() *LoginServiceLoginResult {
	return &LoginServiceLoginResult{}
}

func (p *LoginServiceLoginResult) InitDefault() {
}

var LoginServiceLoginResult_Success_DEFAULT *LoginRes

func (p *LoginServiceLoginResult) GetSuccess() (v *LoginRes) {
	if !p.IsSetSuccess() {
		return LoginServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginRes)
}

func (p *LoginServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceLoginResult(%+v)", *p)
}

var fieldIDToName_LoginServiceLoginResult = map[int16]string{
	0: "success",
}

type LoginServiceCheckUsersExistArgs struct {
	Req *CheckUsersExistReq `thrift:"req,1" frugal:"1,default,CheckUsersExistReq" json:"req"`
}

func NewLoginServiceCheckUsersExistArgs() *LoginServiceCheckUsersExistArgs {
	return &LoginServiceCheckUsersExistArgs{}
}

func (p *LoginServiceCheckUsersExistArgs) InitDefault() {
}

var LoginServiceCheckUsersExistArgs_Req_DEFAULT *CheckUsersExistReq

func (p *LoginServiceCheckUsersExistArgs) GetReq() (v *CheckUsersExistReq) {
	if !p.IsSetReq() {
		return LoginServiceCheckUsersExistArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceCheckUsersExistArgs) SetReq(val *CheckUsersExistReq) {
	p.Req = val
}

func (p *LoginServiceCheckUsersExistArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceCheckUsersExistArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCheckUsersExistArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceCheckUsersExistArgs = map[int16]string{
	1: "req",
}

type LoginServiceCheckUsersExistResult struct {
	Success *CheckUsersExistRes `thrift:"success,0,optional" frugal:"0,optional,CheckUsersExistRes" json:"success,omitempty"`
}

func NewLoginServiceCheckUsersExistResult() *LoginServiceCheckUsersExistResult {
	return &LoginServiceCheckUsersExistResult{}
}

func (p *LoginServiceCheckUsersExistResult) InitDefault() {
}

var LoginServiceCheckUsersExistResult_Success_DEFAULT *CheckUsersExistRes

func (p *LoginServiceCheckUsersExistResult) GetSuccess() (v *CheckUsersExistRes) {
	if !p.IsSetSuccess() {
		return LoginServiceCheckUsersExistResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceCheckUsersExistResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckUsersExistRes)
}

func (p *LoginServiceCheckUsersExistResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceCheckUsersExistResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCheckUsersExistResult(%+v)", *p)
}

var fieldIDToName_LoginServiceCheckUsersExistResult = map[int16]string{
	0: "success",
}
