// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type CommonRes struct {
	Success bool `thrift:"success,1" frugal:"1,default,bool" json:"success"`
}

func NewCommonRes() *CommonRes {
	return &CommonRes{}
}

func (p *CommonRes) InitDefault() {
}

func (p *CommonRes) GetSuccess() (v bool) {
	return p.Success
}
func (p *CommonRes) SetSuccess(val bool) {
	p.Success = val
}

func (p *CommonRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonRes(%+v)", *p)
}

var fieldIDToName_CommonRes = map[int16]string{
	1: "success",
}

type RegisterReq struct {
	Account  string `thrift:"account,1" frugal:"1,default,string" json:"account"`
	Name     string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetAccount() (v string) {
	return p.Account
}

func (p *RegisterReq) GetName() (v string) {
	return p.Name
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterReq) SetAccount(val string) {
	p.Account = val
}
func (p *RegisterReq) SetName(val string) {
	p.Name = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "account",
	2: "name",
	3: "password",
}

type RegisterRes struct {
	IsExit bool `thrift:"isExit,1" frugal:"1,default,bool" json:"isExit"`
}

func NewRegisterRes() *RegisterRes {
	return &RegisterRes{}
}

func (p *RegisterRes) InitDefault() {
}

func (p *RegisterRes) GetIsExit() (v bool) {
	return p.IsExit
}
func (p *RegisterRes) SetIsExit(val bool) {
	p.IsExit = val
}

func (p *RegisterRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRes(%+v)", *p)
}

var fieldIDToName_RegisterRes = map[int16]string{
	1: "isExit",
}

type LoginReq struct {
	Account  string `thrift:"account,1" frugal:"1,default,string" json:"account"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetAccount() (v string) {
	return p.Account
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetAccount(val string) {
	p.Account = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "account",
	2: "password",
}

type LoginRes struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Account   string `thrift:"account,2" frugal:"2,default,string" json:"account"`
	AvatarUrl string `thrift:"avatar_url,3" frugal:"3,default,string" json:"avatar_url"`
}

func NewLoginRes() *LoginRes {
	return &LoginRes{}
}

func (p *LoginRes) InitDefault() {
}

func (p *LoginRes) GetId() (v int64) {
	return p.Id
}

func (p *LoginRes) GetAccount() (v string) {
	return p.Account
}

func (p *LoginRes) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *LoginRes) SetId(val int64) {
	p.Id = val
}
func (p *LoginRes) SetAccount(val string) {
	p.Account = val
}
func (p *LoginRes) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *LoginRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRes(%+v)", *p)
}

var fieldIDToName_LoginRes = map[int16]string{
	1: "id",
	2: "account",
	3: "avatar_url",
}

type CheckUsersExistReq struct {
	UserIds []int64 `thrift:"userIds,1" frugal:"1,default,list<i64>" json:"userIds"`
}

func NewCheckUsersExistReq() *CheckUsersExistReq {
	return &CheckUsersExistReq{}
}

func (p *CheckUsersExistReq) InitDefault() {
}

func (p *CheckUsersExistReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *CheckUsersExistReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *CheckUsersExistReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckUsersExistReq(%+v)", *p)
}

var fieldIDToName_CheckUsersExistReq = map[int16]string{
	1: "userIds",
}

type CheckUsersExistRes struct {
	AllExist bool `thrift:"allExist,1" frugal:"1,default,bool" json:"allExist"`
}

func NewCheckUsersExistRes() *CheckUsersExistRes {
	return &CheckUsersExistRes{}
}

func (p *CheckUsersExistRes) InitDefault() {
}

func (p *CheckUsersExistRes) GetAllExist() (v bool) {
	return p.AllExist
}
func (p *CheckUsersExistRes) SetAllExist(val bool) {
	p.AllExist = val
}

func (p *CheckUsersExistRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckUsersExistRes(%+v)", *p)
}

var fieldIDToName_CheckUsersExistRes = map[int16]string{
	1: "allExist",
}

type AddFriendReq struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Receiver int64  `thrift:"receiver,2" frugal:"2,default,i64" json:"receiver"`
	Message  string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewAddFriendReq() *AddFriendReq {
	return &AddFriendReq{}
}

func (p *AddFriendReq) InitDefault() {
}

func (p *AddFriendReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *AddFriendReq) GetReceiver() (v int64) {
	return p.Receiver
}

func (p *AddFriendReq) GetMessage() (v string) {
	return p.Message
}
func (p *AddFriendReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *AddFriendReq) SetReceiver(val int64) {
	p.Receiver = val
}
func (p *AddFriendReq) SetMessage(val string) {
	p.Message = val
}

func (p *AddFriendReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddFriendReq(%+v)", *p)
}

var fieldIDToName_AddFriendReq = map[int16]string{
	1: "user_id",
	2: "receiver",
	3: "message",
}

type HandleFriendReqReq struct {
	Sender int64 `thrift:"sender,1" frugal:"1,default,i64" json:"sender"`
	UserId int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Accept bool  `thrift:"accept,3" frugal:"3,default,bool" json:"accept"`
}

func NewHandleFriendReqReq() *HandleFriendReqReq {
	return &HandleFriendReqReq{}
}

func (p *HandleFriendReqReq) InitDefault() {
}

func (p *HandleFriendReqReq) GetSender() (v int64) {
	return p.Sender
}

func (p *HandleFriendReqReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *HandleFriendReqReq) GetAccept() (v bool) {
	return p.Accept
}
func (p *HandleFriendReqReq) SetSender(val int64) {
	p.Sender = val
}
func (p *HandleFriendReqReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *HandleFriendReqReq) SetAccept(val bool) {
	p.Accept = val
}

func (p *HandleFriendReqReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HandleFriendReqReq(%+v)", *p)
}

var fieldIDToName_HandleFriendReqReq = map[int16]string{
	1: "sender",
	2: "user_id",
	3: "accept",
}

type DeleteFriendReq struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64 `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
}

func NewDeleteFriendReq() *DeleteFriendReq {
	return &DeleteFriendReq{}
}

func (p *DeleteFriendReq) InitDefault() {
}

func (p *DeleteFriendReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteFriendReq) GetFriendId() (v int64) {
	return p.FriendId
}
func (p *DeleteFriendReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteFriendReq) SetFriendId(val int64) {
	p.FriendId = val
}

func (p *DeleteFriendReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendReq(%+v)", *p)
}

var fieldIDToName_DeleteFriendReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
}

type GetFriendListReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetFriendListReq() *GetFriendListReq {
	return &GetFriendListReq{}
}

func (p *GetFriendListReq) InitDefault() {
}

func (p *GetFriendListReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetFriendListReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetFriendListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendListReq(%+v)", *p)
}

var fieldIDToName_GetFriendListReq = map[int16]string{
	1: "user_id",
}

type FriendInfo struct {
	FriendId int64  `thrift:"friend_id,1" frugal:"1,default,i64" json:"friend_id"`
	Remark   string `thrift:"remark,2" frugal:"2,default,string" json:"remark"`
	GroupId  int64  `thrift:"group_id,3" frugal:"3,default,i64" json:"group_id"`
	Name     string `thrift:"name,4" frugal:"4,default,string" json:"name"`
}

func NewFriendInfo() *FriendInfo {
	return &FriendInfo{}
}

func (p *FriendInfo) InitDefault() {
}

func (p *FriendInfo) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *FriendInfo) GetRemark() (v string) {
	return p.Remark
}

func (p *FriendInfo) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *FriendInfo) GetName() (v string) {
	return p.Name
}
func (p *FriendInfo) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *FriendInfo) SetRemark(val string) {
	p.Remark = val
}
func (p *FriendInfo) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *FriendInfo) SetName(val string) {
	p.Name = val
}

func (p *FriendInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendInfo(%+v)", *p)
}

var fieldIDToName_FriendInfo = map[int16]string{
	1: "friend_id",
	2: "remark",
	3: "group_id",
	4: "name",
}

type GetFriendListRes struct {
	Friends []*FriendInfo `thrift:"friends,1" frugal:"1,default,list<FriendInfo>" json:"friends"`
}

func NewGetFriendListRes() *GetFriendListRes {
	return &GetFriendListRes{}
}

func (p *GetFriendListRes) InitDefault() {
}

func (p *GetFriendListRes) GetFriends() (v []*FriendInfo) {
	return p.Friends
}
func (p *GetFriendListRes) SetFriends(val []*FriendInfo) {
	p.Friends = val
}

func (p *GetFriendListRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendListRes(%+v)", *p)
}

var fieldIDToName_GetFriendListRes = map[int16]string{
	1: "friends",
}

type GetFriendRequestsReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetFriendRequestsReq() *GetFriendRequestsReq {
	return &GetFriendRequestsReq{}
}

func (p *GetFriendRequestsReq) InitDefault() {
}

func (p *GetFriendRequestsReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetFriendRequestsReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetFriendRequestsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendRequestsReq(%+v)", *p)
}

var fieldIDToName_GetFriendRequestsReq = map[int16]string{
	1: "user_id",
}

type FriendRequestInfo struct {
	Sender   int64  `thrift:"sender,1" frugal:"1,default,i64" json:"sender"`
	Receiver int64  `thrift:"receiver,2" frugal:"2,default,i64" json:"receiver"`
	Message  string `thrift:"message,3" frugal:"3,default,string" json:"message"`
	Status   int64  `thrift:"status,4" frugal:"4,default,i64" json:"status"`
}

func NewFriendRequestInfo() *FriendRequestInfo {
	return &FriendRequestInfo{}
}

func (p *FriendRequestInfo) InitDefault() {
}

func (p *FriendRequestInfo) GetSender() (v int64) {
	return p.Sender
}

func (p *FriendRequestInfo) GetReceiver() (v int64) {
	return p.Receiver
}

func (p *FriendRequestInfo) GetMessage() (v string) {
	return p.Message
}

func (p *FriendRequestInfo) GetStatus() (v int64) {
	return p.Status
}
func (p *FriendRequestInfo) SetSender(val int64) {
	p.Sender = val
}
func (p *FriendRequestInfo) SetReceiver(val int64) {
	p.Receiver = val
}
func (p *FriendRequestInfo) SetMessage(val string) {
	p.Message = val
}
func (p *FriendRequestInfo) SetStatus(val int64) {
	p.Status = val
}

func (p *FriendRequestInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendRequestInfo(%+v)", *p)
}

var fieldIDToName_FriendRequestInfo = map[int16]string{
	1: "sender",
	2: "receiver",
	3: "message",
	4: "status",
}

type GetFriendRequestsRes struct {
	Requests []*FriendRequestInfo `thrift:"requests,1" frugal:"1,default,list<FriendRequestInfo>" json:"requests"`
}

func NewGetFriendRequestsRes() *GetFriendRequestsRes {
	return &GetFriendRequestsRes{}
}

func (p *GetFriendRequestsRes) InitDefault() {
}

func (p *GetFriendRequestsRes) GetRequests() (v []*FriendRequestInfo) {
	return p.Requests
}
func (p *GetFriendRequestsRes) SetRequests(val []*FriendRequestInfo) {
	p.Requests = val
}

func (p *GetFriendRequestsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendRequestsRes(%+v)", *p)
}

var fieldIDToName_GetFriendRequestsRes = map[int16]string{
	1: "requests",
}

type CreateFriendGroupReq struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name   string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewCreateFriendGroupReq() *CreateFriendGroupReq {
	return &CreateFriendGroupReq{}
}

func (p *CreateFriendGroupReq) InitDefault() {
}

func (p *CreateFriendGroupReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateFriendGroupReq) GetName() (v string) {
	return p.Name
}
func (p *CreateFriendGroupReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateFriendGroupReq) SetName(val string) {
	p.Name = val
}

func (p *CreateFriendGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFriendGroupReq(%+v)", *p)
}

var fieldIDToName_CreateFriendGroupReq = map[int16]string{
	1: "user_id",
	2: "name",
}

type CreateFriendGroupRes struct {
	GroupId int64 `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
}

func NewCreateFriendGroupRes() *CreateFriendGroupRes {
	return &CreateFriendGroupRes{}
}

func (p *CreateFriendGroupRes) InitDefault() {
}

func (p *CreateFriendGroupRes) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *CreateFriendGroupRes) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *CreateFriendGroupRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateFriendGroupRes(%+v)", *p)
}

var fieldIDToName_CreateFriendGroupRes = map[int16]string{
	1: "group_id",
}

type UpdateFriendGroupReq struct {
	GroupId int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	UserId  int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Name    string `thrift:"name,3" frugal:"3,default,string" json:"name"`
}

func NewUpdateFriendGroupReq() *UpdateFriendGroupReq {
	return &UpdateFriendGroupReq{}
}

func (p *UpdateFriendGroupReq) InitDefault() {
}

func (p *UpdateFriendGroupReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *UpdateFriendGroupReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateFriendGroupReq) GetName() (v string) {
	return p.Name
}
func (p *UpdateFriendGroupReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *UpdateFriendGroupReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateFriendGroupReq) SetName(val string) {
	p.Name = val
}

func (p *UpdateFriendGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendGroupReq(%+v)", *p)
}

var fieldIDToName_UpdateFriendGroupReq = map[int16]string{
	1: "group_id",
	2: "user_id",
	3: "name",
}

type DeleteFriendGroupReq struct {
	GroupId int64 `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	UserId  int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewDeleteFriendGroupReq() *DeleteFriendGroupReq {
	return &DeleteFriendGroupReq{}
}

func (p *DeleteFriendGroupReq) InitDefault() {
}

func (p *DeleteFriendGroupReq) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *DeleteFriendGroupReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteFriendGroupReq) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *DeleteFriendGroupReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteFriendGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFriendGroupReq(%+v)", *p)
}

var fieldIDToName_DeleteFriendGroupReq = map[int16]string{
	1: "group_id",
	2: "user_id",
}

type MoveFriendToGroupReq struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64 `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
	GroupId  int64 `thrift:"group_id,3" frugal:"3,default,i64" json:"group_id"`
}

func NewMoveFriendToGroupReq() *MoveFriendToGroupReq {
	return &MoveFriendToGroupReq{}
}

func (p *MoveFriendToGroupReq) InitDefault() {
}

func (p *MoveFriendToGroupReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *MoveFriendToGroupReq) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *MoveFriendToGroupReq) GetGroupId() (v int64) {
	return p.GroupId
}
func (p *MoveFriendToGroupReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *MoveFriendToGroupReq) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *MoveFriendToGroupReq) SetGroupId(val int64) {
	p.GroupId = val
}

func (p *MoveFriendToGroupReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MoveFriendToGroupReq(%+v)", *p)
}

var fieldIDToName_MoveFriendToGroupReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
	3: "group_id",
}

type UpdateFriendRemarkReq struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FriendId int64  `thrift:"friend_id,2" frugal:"2,default,i64" json:"friend_id"`
	Remark   string `thrift:"remark,3" frugal:"3,default,string" json:"remark"`
}

func NewUpdateFriendRemarkReq() *UpdateFriendRemarkReq {
	return &UpdateFriendRemarkReq{}
}

func (p *UpdateFriendRemarkReq) InitDefault() {
}

func (p *UpdateFriendRemarkReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateFriendRemarkReq) GetFriendId() (v int64) {
	return p.FriendId
}

func (p *UpdateFriendRemarkReq) GetRemark() (v string) {
	return p.Remark
}
func (p *UpdateFriendRemarkReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateFriendRemarkReq) SetFriendId(val int64) {
	p.FriendId = val
}
func (p *UpdateFriendRemarkReq) SetRemark(val string) {
	p.Remark = val
}

func (p *UpdateFriendRemarkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendRemarkReq(%+v)", *p)
}

var fieldIDToName_UpdateFriendRemarkReq = map[int16]string{
	1: "user_id",
	2: "friend_id",
	3: "remark",
}

type GetFriendGroupsReq struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetFriendGroupsReq() *GetFriendGroupsReq {
	return &GetFriendGroupsReq{}
}

func (p *GetFriendGroupsReq) InitDefault() {
}

func (p *GetFriendGroupsReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetFriendGroupsReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetFriendGroupsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendGroupsReq(%+v)", *p)
}

var fieldIDToName_GetFriendGroupsReq = map[int16]string{
	1: "user_id",
}

type FriendGroupInfo struct {
	GroupId int64  `thrift:"group_id,1" frugal:"1,default,i64" json:"group_id"`
	Name    string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewFriendGroupInfo() *FriendGroupInfo {
	return &FriendGroupInfo{}
}

func (p *FriendGroupInfo) InitDefault() {
}

func (p *FriendGroupInfo) GetGroupId() (v int64) {
	return p.GroupId
}

func (p *FriendGroupInfo) GetName() (v string) {
	return p.Name
}
func (p *FriendGroupInfo) SetGroupId(val int64) {
	p.GroupId = val
}
func (p *FriendGroupInfo) SetName(val string) {
	p.Name = val
}

func (p *FriendGroupInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendGroupInfo(%+v)", *p)
}

var fieldIDToName_FriendGroupInfo = map[int16]string{
	1: "group_id",
	2: "name",
}

type GetFriendGroupsRes struct {
	Groups []*FriendGroupInfo `thrift:"groups,1" frugal:"1,default,list<FriendGroupInfo>" json:"groups"`
}

func NewGetFriendGroupsRes() *GetFriendGroupsRes {
	return &GetFriendGroupsRes{}
}

func (p *GetFriendGroupsRes) InitDefault() {
}

func (p *GetFriendGroupsRes) GetGroups() (v []*FriendGroupInfo) {
	return p.Groups
}
func (p *GetFriendGroupsRes) SetGroups(val []*FriendGroupInfo) {
	p.Groups = val
}

func (p *GetFriendGroupsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFriendGroupsRes(%+v)", *p)
}

var fieldIDToName_GetFriendGroupsRes = map[int16]string{
	1: "groups",
}

type SearchUserByAccountReq struct {
	Account string `thrift:"account,1" frugal:"1,default,string" json:"account"`
}

func NewSearchUserByAccountReq() *SearchUserByAccountReq {
	return &SearchUserByAccountReq{}
}

func (p *SearchUserByAccountReq) InitDefault() {
}

func (p *SearchUserByAccountReq) GetAccount() (v string) {
	return p.Account
}
func (p *SearchUserByAccountReq) SetAccount(val string) {
	p.Account = val
}

func (p *SearchUserByAccountReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchUserByAccountReq(%+v)", *p)
}

var fieldIDToName_SearchUserByAccountReq = map[int16]string{
	1: "account",
}

type SearchUserResult_ struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Account   string `thrift:"account,2" frugal:"2,default,string" json:"account"`
	Name      string `thrift:"name,3" frugal:"3,default,string" json:"name"`
	AvatarUrl string `thrift:"avatar_url,4" frugal:"4,default,string" json:"avatar_url"`
}

func NewSearchUserResult_() *SearchUserResult_ {
	return &SearchUserResult_{}
}

func (p *SearchUserResult_) InitDefault() {
}

func (p *SearchUserResult_) GetId() (v int64) {
	return p.Id
}

func (p *SearchUserResult_) GetAccount() (v string) {
	return p.Account
}

func (p *SearchUserResult_) GetName() (v string) {
	return p.Name
}

func (p *SearchUserResult_) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *SearchUserResult_) SetId(val int64) {
	p.Id = val
}
func (p *SearchUserResult_) SetAccount(val string) {
	p.Account = val
}
func (p *SearchUserResult_) SetName(val string) {
	p.Name = val
}
func (p *SearchUserResult_) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *SearchUserResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchUserResult_(%+v)", *p)
}

var fieldIDToName_SearchUserResult_ = map[int16]string{
	1: "id",
	2: "account",
	3: "name",
	4: "avatar_url",
}

type SearchUserByAccountRes struct {
	UserInfo *SearchUserResult_ `thrift:"user_info,1" frugal:"1,default,SearchUserResult_" json:"user_info"`
}

func NewSearchUserByAccountRes() *SearchUserByAccountRes {
	return &SearchUserByAccountRes{}
}

func (p *SearchUserByAccountRes) InitDefault() {
}

var SearchUserByAccountRes_UserInfo_DEFAULT *SearchUserResult_

func (p *SearchUserByAccountRes) GetUserInfo() (v *SearchUserResult_) {
	if !p.IsSetUserInfo() {
		return SearchUserByAccountRes_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *SearchUserByAccountRes) SetUserInfo(val *SearchUserResult_) {
	p.UserInfo = val
}

func (p *SearchUserByAccountRes) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *SearchUserByAccountRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchUserByAccountRes(%+v)", *p)
}

var fieldIDToName_SearchUserByAccountRes = map[int16]string{
	1: "user_info",
}

type GetUserNamesReq struct {
	UserIds []int64 `thrift:"user_ids,1" frugal:"1,default,list<i64>" json:"user_ids"`
}

func NewGetUserNamesReq() *GetUserNamesReq {
	return &GetUserNamesReq{}
}

func (p *GetUserNamesReq) InitDefault() {
}

func (p *GetUserNamesReq) GetUserIds() (v []int64) {
	return p.UserIds
}
func (p *GetUserNamesReq) SetUserIds(val []int64) {
	p.UserIds = val
}

func (p *GetUserNamesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserNamesReq(%+v)", *p)
}

var fieldIDToName_GetUserNamesReq = map[int16]string{
	1: "user_ids",
}

type UserNameInfo struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name      string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Account   string `thrift:"account,3" frugal:"3,default,string" json:"account"`
	AvatarUrl string `thrift:"avatar_url,4" frugal:"4,default,string" json:"avatar_url"`
}

func NewUserNameInfo() *UserNameInfo {
	return &UserNameInfo{}
}

func (p *UserNameInfo) InitDefault() {
}

func (p *UserNameInfo) GetId() (v int64) {
	return p.Id
}

func (p *UserNameInfo) GetName() (v string) {
	return p.Name
}

func (p *UserNameInfo) GetAccount() (v string) {
	return p.Account
}

func (p *UserNameInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *UserNameInfo) SetId(val int64) {
	p.Id = val
}
func (p *UserNameInfo) SetName(val string) {
	p.Name = val
}
func (p *UserNameInfo) SetAccount(val string) {
	p.Account = val
}
func (p *UserNameInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *UserNameInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserNameInfo(%+v)", *p)
}

var fieldIDToName_UserNameInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "account",
	4: "avatar_url",
}

type GetUserNamesRes struct {
	Users []*UserNameInfo `thrift:"users,1" frugal:"1,default,list<UserNameInfo>" json:"users"`
}

func NewGetUserNamesRes() *GetUserNamesRes {
	return &GetUserNamesRes{}
}

func (p *GetUserNamesRes) InitDefault() {
}

func (p *GetUserNamesRes) GetUsers() (v []*UserNameInfo) {
	return p.Users
}
func (p *GetUserNamesRes) SetUsers(val []*UserNameInfo) {
	p.Users = val
}

func (p *GetUserNamesRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserNamesRes(%+v)", *p)
}

var fieldIDToName_GetUserNamesRes = map[int16]string{
	1: "users",
}

type GetUserIdsByAccountsReq struct {
	Accounts []string `thrift:"accounts,1" frugal:"1,default,list<string>" json:"accounts"`
}

func NewGetUserIdsByAccountsReq() *GetUserIdsByAccountsReq {
	return &GetUserIdsByAccountsReq{}
}

func (p *GetUserIdsByAccountsReq) InitDefault() {
}

func (p *GetUserIdsByAccountsReq) GetAccounts() (v []string) {
	return p.Accounts
}
func (p *GetUserIdsByAccountsReq) SetAccounts(val []string) {
	p.Accounts = val
}

func (p *GetUserIdsByAccountsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserIdsByAccountsReq(%+v)", *p)
}

var fieldIDToName_GetUserIdsByAccountsReq = map[int16]string{
	1: "accounts",
}

type UserAccountPair struct {
	Id      int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Account string `thrift:"account,2" frugal:"2,default,string" json:"account"`
}

func NewUserAccountPair() *UserAccountPair {
	return &UserAccountPair{}
}

func (p *UserAccountPair) InitDefault() {
}

func (p *UserAccountPair) GetId() (v int64) {
	return p.Id
}

func (p *UserAccountPair) GetAccount() (v string) {
	return p.Account
}
func (p *UserAccountPair) SetId(val int64) {
	p.Id = val
}
func (p *UserAccountPair) SetAccount(val string) {
	p.Account = val
}

func (p *UserAccountPair) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAccountPair(%+v)", *p)
}

var fieldIDToName_UserAccountPair = map[int16]string{
	1: "id",
	2: "account",
}

type GetUserIdsByAccountsRes struct {
	Users []*UserAccountPair `thrift:"users,1" frugal:"1,default,list<UserAccountPair>" json:"users"`
}

func NewGetUserIdsByAccountsRes() *GetUserIdsByAccountsRes {
	return &GetUserIdsByAccountsRes{}
}

func (p *GetUserIdsByAccountsRes) InitDefault() {
}

func (p *GetUserIdsByAccountsRes) GetUsers() (v []*UserAccountPair) {
	return p.Users
}
func (p *GetUserIdsByAccountsRes) SetUsers(val []*UserAccountPair) {
	p.Users = val
}

func (p *GetUserIdsByAccountsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserIdsByAccountsRes(%+v)", *p)
}

var fieldIDToName_GetUserIdsByAccountsRes = map[int16]string{
	1: "users",
}

type GetUsersInfoByAccountsReq struct {
	Accounts []string `thrift:"accounts,1" frugal:"1,default,list<string>" json:"accounts"`
}

func NewGetUsersInfoByAccountsReq() *GetUsersInfoByAccountsReq {
	return &GetUsersInfoByAccountsReq{}
}

func (p *GetUsersInfoByAccountsReq) InitDefault() {
}

func (p *GetUsersInfoByAccountsReq) GetAccounts() (v []string) {
	return p.Accounts
}
func (p *GetUsersInfoByAccountsReq) SetAccounts(val []string) {
	p.Accounts = val
}

func (p *GetUsersInfoByAccountsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUsersInfoByAccountsReq(%+v)", *p)
}

var fieldIDToName_GetUsersInfoByAccountsReq = map[int16]string{
	1: "accounts",
}

type UserInfoItem struct {
	Account   string `thrift:"account,1" frugal:"1,default,string" json:"account"`
	Name      string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	AvatarUrl string `thrift:"avatar_url,3" frugal:"3,default,string" json:"avatar_url"`
}

func NewUserInfoItem() *UserInfoItem {
	return &UserInfoItem{}
}

func (p *UserInfoItem) InitDefault() {
}

func (p *UserInfoItem) GetAccount() (v string) {
	return p.Account
}

func (p *UserInfoItem) GetName() (v string) {
	return p.Name
}

func (p *UserInfoItem) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *UserInfoItem) SetAccount(val string) {
	p.Account = val
}
func (p *UserInfoItem) SetName(val string) {
	p.Name = val
}
func (p *UserInfoItem) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *UserInfoItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoItem(%+v)", *p)
}

var fieldIDToName_UserInfoItem = map[int16]string{
	1: "account",
	2: "name",
	3: "avatar_url",
}

type GetUsersInfoByAccountsRes struct {
	Users []*UserInfoItem `thrift:"users,1" frugal:"1,default,list<UserInfoItem>" json:"users"`
}

func NewGetUsersInfoByAccountsRes() *GetUsersInfoByAccountsRes {
	return &GetUsersInfoByAccountsRes{}
}

func (p *GetUsersInfoByAccountsRes) InitDefault() {
}

func (p *GetUsersInfoByAccountsRes) GetUsers() (v []*UserInfoItem) {
	return p.Users
}
func (p *GetUsersInfoByAccountsRes) SetUsers(val []*UserInfoItem) {
	p.Users = val
}

func (p *GetUsersInfoByAccountsRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUsersInfoByAccountsRes(%+v)", *p)
}

var fieldIDToName_GetUsersInfoByAccountsRes = map[int16]string{
	1: "users",
}

type UpdateAvatarReq struct {
	UserId    int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	AvatarUrl string `thrift:"avatar_url,2" frugal:"2,default,string" json:"avatar_url"`
}

func NewUpdateAvatarReq() *UpdateAvatarReq {
	return &UpdateAvatarReq{}
}

func (p *UpdateAvatarReq) InitDefault() {
}

func (p *UpdateAvatarReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateAvatarReq) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *UpdateAvatarReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateAvatarReq) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *UpdateAvatarReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAvatarReq(%+v)", *p)
}

var fieldIDToName_UpdateAvatarReq = map[int16]string{
	1: "user_id",
	2: "avatar_url",
}

type CreateBotUserReq struct {
	Name      string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	AvatarUrl string `thrift:"avatar_url,2" frugal:"2,default,string" json:"avatar_url"`
}

func NewCreateBotUserReq() *CreateBotUserReq {
	return &CreateBotUserReq{}
}

func (p *CreateBotUserReq) InitDefault() {
}

func (p *CreateBotUserReq) GetName() (v string) {
	return p.Name
}

func (p *CreateBotUserReq) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *CreateBotUserReq) SetName(val string) {
	p.Name = val
}
func (p *CreateBotUserReq) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *CreateBotUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateBotUserReq(%+v)", *p)
}

var fieldIDToName_CreateBotUserReq = map[int16]string{
	1: "name",
	2: "avatar_url",
}

type CreateBotUserRes struct {
	Success bool  `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	UserId  int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewCreateBotUserRes() *CreateBotUserRes {
	return &CreateBotUserRes{}
}

func (p *CreateBotUserRes) InitDefault() {
}

func (p *CreateBotUserRes) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreateBotUserRes) GetUserId() (v int64) {
	return p.UserId
}
func (p *CreateBotUserRes) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreateBotUserRes) SetUserId(val int64) {
	p.UserId = val
}

func (p *CreateBotUserRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateBotUserRes(%+v)", *p)
}

var fieldIDToName_CreateBotUserRes = map[int16]string{
	1: "success",
	2: "user_id",
}

type UpdateBotUserNameReq struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Name   string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewUpdateBotUserNameReq() *UpdateBotUserNameReq {
	return &UpdateBotUserNameReq{}
}

func (p *UpdateBotUserNameReq) InitDefault() {
}

func (p *UpdateBotUserNameReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateBotUserNameReq) GetName() (v string) {
	return p.Name
}
func (p *UpdateBotUserNameReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateBotUserNameReq) SetName(val string) {
	p.Name = val
}

func (p *UpdateBotUserNameReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateBotUserNameReq(%+v)", *p)
}

var fieldIDToName_UpdateBotUserNameReq = map[int16]string{
	1: "user_id",
	2: "name",
}

type LoginService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterRes, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginRes, err error)

	CheckUsersExist(ctx context.Context, req *CheckUsersExistReq) (r *CheckUsersExistRes, err error)

	AddFriend(ctx context.Context, req *AddFriendReq) (r *CommonRes, err error)

	HandleFriendReq(ctx context.Context, req *HandleFriendReqReq) (r *CommonRes, err error)

	DeleteFriend(ctx context.Context, req *DeleteFriendReq) (r *CommonRes, err error)

	GetFriendList(ctx context.Context, req *GetFriendListReq) (r *GetFriendListRes, err error)

	GetFriendRequests(ctx context.Context, req *GetFriendRequestsReq) (r *GetFriendRequestsRes, err error)

	CreateFriendGroup(ctx context.Context, req *CreateFriendGroupReq) (r *CreateFriendGroupRes, err error)

	UpdateFriendGroup(ctx context.Context, req *UpdateFriendGroupReq) (r *CommonRes, err error)

	DeleteFriendGroup(ctx context.Context, req *DeleteFriendGroupReq) (r *CommonRes, err error)

	MoveFriendToGroup(ctx context.Context, req *MoveFriendToGroupReq) (r *CommonRes, err error)

	UpdateFriendRemark(ctx context.Context, req *UpdateFriendRemarkReq) (r *CommonRes, err error)

	GetFriendGroups(ctx context.Context, req *GetFriendGroupsReq) (r *GetFriendGroupsRes, err error)

	SearchUserByAccount(ctx context.Context, req *SearchUserByAccountReq) (r *SearchUserByAccountRes, err error)

	GetUserNames(ctx context.Context, req *GetUserNamesReq) (r *GetUserNamesRes, err error)

	GetUserIdsByAccounts(ctx context.Context, req *GetUserIdsByAccountsReq) (r *GetUserIdsByAccountsRes, err error)

	GetUsersInfoByAccounts(ctx context.Context, req *GetUsersInfoByAccountsReq) (r *GetUsersInfoByAccountsRes, err error)

	UpdateAvatar(ctx context.Context, req *UpdateAvatarReq) (r *CommonRes, err error)

	CreateBotUser(ctx context.Context, req *CreateBotUserReq) (r *CreateBotUserRes, err error)

	UpdateBotUserName(ctx context.Context, req *UpdateBotUserNameReq) (r *CommonRes, err error)
}

type LoginServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewLoginServiceRegisterArgs() *LoginServiceRegisterArgs {
	return &LoginServiceRegisterArgs{}
}

func (p *LoginServiceRegisterArgs) InitDefault() {
}

var LoginServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *LoginServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return LoginServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *LoginServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceRegisterArgs = map[int16]string{
	1: "req",
}

type LoginServiceRegisterResult struct {
	Success *RegisterRes `thrift:"success,0,optional" frugal:"0,optional,RegisterRes" json:"success,omitempty"`
}

func NewLoginServiceRegisterResult() *LoginServiceRegisterResult {
	return &LoginServiceRegisterResult{}
}

func (p *LoginServiceRegisterResult) InitDefault() {
}

var LoginServiceRegisterResult_Success_DEFAULT *RegisterRes

func (p *LoginServiceRegisterResult) GetSuccess() (v *RegisterRes) {
	if !p.IsSetSuccess() {
		return LoginServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterRes)
}

func (p *LoginServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_LoginServiceRegisterResult = map[int16]string{
	0: "success",
}

type LoginServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewLoginServiceLoginArgs() *LoginServiceLoginArgs {
	return &LoginServiceLoginArgs{}
}

func (p *LoginServiceLoginArgs) InitDefault() {
}

var LoginServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *LoginServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return LoginServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *LoginServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceLoginArgs = map[int16]string{
	1: "req",
}

type LoginServiceLoginResult struct {
	Success *LoginRes `thrift:"success,0,optional" frugal:"0,optional,LoginRes" json:"success,omitempty"`
}

func NewLoginServiceLoginResult() *LoginServiceLoginResult {
	return &LoginServiceLoginResult{}
}

func (p *LoginServiceLoginResult) InitDefault() {
}

var LoginServiceLoginResult_Success_DEFAULT *LoginRes

func (p *LoginServiceLoginResult) GetSuccess() (v *LoginRes) {
	if !p.IsSetSuccess() {
		return LoginServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginRes)
}

func (p *LoginServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceLoginResult(%+v)", *p)
}

var fieldIDToName_LoginServiceLoginResult = map[int16]string{
	0: "success",
}

type LoginServiceCheckUsersExistArgs struct {
	Req *CheckUsersExistReq `thrift:"req,1" frugal:"1,default,CheckUsersExistReq" json:"req"`
}

func NewLoginServiceCheckUsersExistArgs() *LoginServiceCheckUsersExistArgs {
	return &LoginServiceCheckUsersExistArgs{}
}

func (p *LoginServiceCheckUsersExistArgs) InitDefault() {
}

var LoginServiceCheckUsersExistArgs_Req_DEFAULT *CheckUsersExistReq

func (p *LoginServiceCheckUsersExistArgs) GetReq() (v *CheckUsersExistReq) {
	if !p.IsSetReq() {
		return LoginServiceCheckUsersExistArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceCheckUsersExistArgs) SetReq(val *CheckUsersExistReq) {
	p.Req = val
}

func (p *LoginServiceCheckUsersExistArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceCheckUsersExistArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCheckUsersExistArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceCheckUsersExistArgs = map[int16]string{
	1: "req",
}

type LoginServiceCheckUsersExistResult struct {
	Success *CheckUsersExistRes `thrift:"success,0,optional" frugal:"0,optional,CheckUsersExistRes" json:"success,omitempty"`
}

func NewLoginServiceCheckUsersExistResult() *LoginServiceCheckUsersExistResult {
	return &LoginServiceCheckUsersExistResult{}
}

func (p *LoginServiceCheckUsersExistResult) InitDefault() {
}

var LoginServiceCheckUsersExistResult_Success_DEFAULT *CheckUsersExistRes

func (p *LoginServiceCheckUsersExistResult) GetSuccess() (v *CheckUsersExistRes) {
	if !p.IsSetSuccess() {
		return LoginServiceCheckUsersExistResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceCheckUsersExistResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckUsersExistRes)
}

func (p *LoginServiceCheckUsersExistResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceCheckUsersExistResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCheckUsersExistResult(%+v)", *p)
}

var fieldIDToName_LoginServiceCheckUsersExistResult = map[int16]string{
	0: "success",
}

type LoginServiceAddFriendArgs struct {
	Req *AddFriendReq `thrift:"req,1" frugal:"1,default,AddFriendReq" json:"req"`
}

func NewLoginServiceAddFriendArgs() *LoginServiceAddFriendArgs {
	return &LoginServiceAddFriendArgs{}
}

func (p *LoginServiceAddFriendArgs) InitDefault() {
}

var LoginServiceAddFriendArgs_Req_DEFAULT *AddFriendReq

func (p *LoginServiceAddFriendArgs) GetReq() (v *AddFriendReq) {
	if !p.IsSetReq() {
		return LoginServiceAddFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceAddFriendArgs) SetReq(val *AddFriendReq) {
	p.Req = val
}

func (p *LoginServiceAddFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceAddFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceAddFriendArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceAddFriendArgs = map[int16]string{
	1: "req",
}

type LoginServiceAddFriendResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceAddFriendResult() *LoginServiceAddFriendResult {
	return &LoginServiceAddFriendResult{}
}

func (p *LoginServiceAddFriendResult) InitDefault() {
}

var LoginServiceAddFriendResult_Success_DEFAULT *CommonRes

func (p *LoginServiceAddFriendResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceAddFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceAddFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceAddFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceAddFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceAddFriendResult(%+v)", *p)
}

var fieldIDToName_LoginServiceAddFriendResult = map[int16]string{
	0: "success",
}

type LoginServiceHandleFriendReqArgs struct {
	Req *HandleFriendReqReq `thrift:"req,1" frugal:"1,default,HandleFriendReqReq" json:"req"`
}

func NewLoginServiceHandleFriendReqArgs() *LoginServiceHandleFriendReqArgs {
	return &LoginServiceHandleFriendReqArgs{}
}

func (p *LoginServiceHandleFriendReqArgs) InitDefault() {
}

var LoginServiceHandleFriendReqArgs_Req_DEFAULT *HandleFriendReqReq

func (p *LoginServiceHandleFriendReqArgs) GetReq() (v *HandleFriendReqReq) {
	if !p.IsSetReq() {
		return LoginServiceHandleFriendReqArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceHandleFriendReqArgs) SetReq(val *HandleFriendReqReq) {
	p.Req = val
}

func (p *LoginServiceHandleFriendReqArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceHandleFriendReqArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceHandleFriendReqArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceHandleFriendReqArgs = map[int16]string{
	1: "req",
}

type LoginServiceHandleFriendReqResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceHandleFriendReqResult() *LoginServiceHandleFriendReqResult {
	return &LoginServiceHandleFriendReqResult{}
}

func (p *LoginServiceHandleFriendReqResult) InitDefault() {
}

var LoginServiceHandleFriendReqResult_Success_DEFAULT *CommonRes

func (p *LoginServiceHandleFriendReqResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceHandleFriendReqResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceHandleFriendReqResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceHandleFriendReqResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceHandleFriendReqResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceHandleFriendReqResult(%+v)", *p)
}

var fieldIDToName_LoginServiceHandleFriendReqResult = map[int16]string{
	0: "success",
}

type LoginServiceDeleteFriendArgs struct {
	Req *DeleteFriendReq `thrift:"req,1" frugal:"1,default,DeleteFriendReq" json:"req"`
}

func NewLoginServiceDeleteFriendArgs() *LoginServiceDeleteFriendArgs {
	return &LoginServiceDeleteFriendArgs{}
}

func (p *LoginServiceDeleteFriendArgs) InitDefault() {
}

var LoginServiceDeleteFriendArgs_Req_DEFAULT *DeleteFriendReq

func (p *LoginServiceDeleteFriendArgs) GetReq() (v *DeleteFriendReq) {
	if !p.IsSetReq() {
		return LoginServiceDeleteFriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceDeleteFriendArgs) SetReq(val *DeleteFriendReq) {
	p.Req = val
}

func (p *LoginServiceDeleteFriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceDeleteFriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceDeleteFriendArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceDeleteFriendArgs = map[int16]string{
	1: "req",
}

type LoginServiceDeleteFriendResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceDeleteFriendResult() *LoginServiceDeleteFriendResult {
	return &LoginServiceDeleteFriendResult{}
}

func (p *LoginServiceDeleteFriendResult) InitDefault() {
}

var LoginServiceDeleteFriendResult_Success_DEFAULT *CommonRes

func (p *LoginServiceDeleteFriendResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceDeleteFriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceDeleteFriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceDeleteFriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceDeleteFriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceDeleteFriendResult(%+v)", *p)
}

var fieldIDToName_LoginServiceDeleteFriendResult = map[int16]string{
	0: "success",
}

type LoginServiceGetFriendListArgs struct {
	Req *GetFriendListReq `thrift:"req,1" frugal:"1,default,GetFriendListReq" json:"req"`
}

func NewLoginServiceGetFriendListArgs() *LoginServiceGetFriendListArgs {
	return &LoginServiceGetFriendListArgs{}
}

func (p *LoginServiceGetFriendListArgs) InitDefault() {
}

var LoginServiceGetFriendListArgs_Req_DEFAULT *GetFriendListReq

func (p *LoginServiceGetFriendListArgs) GetReq() (v *GetFriendListReq) {
	if !p.IsSetReq() {
		return LoginServiceGetFriendListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceGetFriendListArgs) SetReq(val *GetFriendListReq) {
	p.Req = val
}

func (p *LoginServiceGetFriendListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceGetFriendListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetFriendListArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceGetFriendListArgs = map[int16]string{
	1: "req",
}

type LoginServiceGetFriendListResult struct {
	Success *GetFriendListRes `thrift:"success,0,optional" frugal:"0,optional,GetFriendListRes" json:"success,omitempty"`
}

func NewLoginServiceGetFriendListResult() *LoginServiceGetFriendListResult {
	return &LoginServiceGetFriendListResult{}
}

func (p *LoginServiceGetFriendListResult) InitDefault() {
}

var LoginServiceGetFriendListResult_Success_DEFAULT *GetFriendListRes

func (p *LoginServiceGetFriendListResult) GetSuccess() (v *GetFriendListRes) {
	if !p.IsSetSuccess() {
		return LoginServiceGetFriendListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceGetFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendListRes)
}

func (p *LoginServiceGetFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceGetFriendListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetFriendListResult(%+v)", *p)
}

var fieldIDToName_LoginServiceGetFriendListResult = map[int16]string{
	0: "success",
}

type LoginServiceGetFriendRequestsArgs struct {
	Req *GetFriendRequestsReq `thrift:"req,1" frugal:"1,default,GetFriendRequestsReq" json:"req"`
}

func NewLoginServiceGetFriendRequestsArgs() *LoginServiceGetFriendRequestsArgs {
	return &LoginServiceGetFriendRequestsArgs{}
}

func (p *LoginServiceGetFriendRequestsArgs) InitDefault() {
}

var LoginServiceGetFriendRequestsArgs_Req_DEFAULT *GetFriendRequestsReq

func (p *LoginServiceGetFriendRequestsArgs) GetReq() (v *GetFriendRequestsReq) {
	if !p.IsSetReq() {
		return LoginServiceGetFriendRequestsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceGetFriendRequestsArgs) SetReq(val *GetFriendRequestsReq) {
	p.Req = val
}

func (p *LoginServiceGetFriendRequestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceGetFriendRequestsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetFriendRequestsArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceGetFriendRequestsArgs = map[int16]string{
	1: "req",
}

type LoginServiceGetFriendRequestsResult struct {
	Success *GetFriendRequestsRes `thrift:"success,0,optional" frugal:"0,optional,GetFriendRequestsRes" json:"success,omitempty"`
}

func NewLoginServiceGetFriendRequestsResult() *LoginServiceGetFriendRequestsResult {
	return &LoginServiceGetFriendRequestsResult{}
}

func (p *LoginServiceGetFriendRequestsResult) InitDefault() {
}

var LoginServiceGetFriendRequestsResult_Success_DEFAULT *GetFriendRequestsRes

func (p *LoginServiceGetFriendRequestsResult) GetSuccess() (v *GetFriendRequestsRes) {
	if !p.IsSetSuccess() {
		return LoginServiceGetFriendRequestsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceGetFriendRequestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendRequestsRes)
}

func (p *LoginServiceGetFriendRequestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceGetFriendRequestsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetFriendRequestsResult(%+v)", *p)
}

var fieldIDToName_LoginServiceGetFriendRequestsResult = map[int16]string{
	0: "success",
}

type LoginServiceCreateFriendGroupArgs struct {
	Req *CreateFriendGroupReq `thrift:"req,1" frugal:"1,default,CreateFriendGroupReq" json:"req"`
}

func NewLoginServiceCreateFriendGroupArgs() *LoginServiceCreateFriendGroupArgs {
	return &LoginServiceCreateFriendGroupArgs{}
}

func (p *LoginServiceCreateFriendGroupArgs) InitDefault() {
}

var LoginServiceCreateFriendGroupArgs_Req_DEFAULT *CreateFriendGroupReq

func (p *LoginServiceCreateFriendGroupArgs) GetReq() (v *CreateFriendGroupReq) {
	if !p.IsSetReq() {
		return LoginServiceCreateFriendGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceCreateFriendGroupArgs) SetReq(val *CreateFriendGroupReq) {
	p.Req = val
}

func (p *LoginServiceCreateFriendGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceCreateFriendGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCreateFriendGroupArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceCreateFriendGroupArgs = map[int16]string{
	1: "req",
}

type LoginServiceCreateFriendGroupResult struct {
	Success *CreateFriendGroupRes `thrift:"success,0,optional" frugal:"0,optional,CreateFriendGroupRes" json:"success,omitempty"`
}

func NewLoginServiceCreateFriendGroupResult() *LoginServiceCreateFriendGroupResult {
	return &LoginServiceCreateFriendGroupResult{}
}

func (p *LoginServiceCreateFriendGroupResult) InitDefault() {
}

var LoginServiceCreateFriendGroupResult_Success_DEFAULT *CreateFriendGroupRes

func (p *LoginServiceCreateFriendGroupResult) GetSuccess() (v *CreateFriendGroupRes) {
	if !p.IsSetSuccess() {
		return LoginServiceCreateFriendGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceCreateFriendGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateFriendGroupRes)
}

func (p *LoginServiceCreateFriendGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceCreateFriendGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCreateFriendGroupResult(%+v)", *p)
}

var fieldIDToName_LoginServiceCreateFriendGroupResult = map[int16]string{
	0: "success",
}

type LoginServiceUpdateFriendGroupArgs struct {
	Req *UpdateFriendGroupReq `thrift:"req,1" frugal:"1,default,UpdateFriendGroupReq" json:"req"`
}

func NewLoginServiceUpdateFriendGroupArgs() *LoginServiceUpdateFriendGroupArgs {
	return &LoginServiceUpdateFriendGroupArgs{}
}

func (p *LoginServiceUpdateFriendGroupArgs) InitDefault() {
}

var LoginServiceUpdateFriendGroupArgs_Req_DEFAULT *UpdateFriendGroupReq

func (p *LoginServiceUpdateFriendGroupArgs) GetReq() (v *UpdateFriendGroupReq) {
	if !p.IsSetReq() {
		return LoginServiceUpdateFriendGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceUpdateFriendGroupArgs) SetReq(val *UpdateFriendGroupReq) {
	p.Req = val
}

func (p *LoginServiceUpdateFriendGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceUpdateFriendGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateFriendGroupArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateFriendGroupArgs = map[int16]string{
	1: "req",
}

type LoginServiceUpdateFriendGroupResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceUpdateFriendGroupResult() *LoginServiceUpdateFriendGroupResult {
	return &LoginServiceUpdateFriendGroupResult{}
}

func (p *LoginServiceUpdateFriendGroupResult) InitDefault() {
}

var LoginServiceUpdateFriendGroupResult_Success_DEFAULT *CommonRes

func (p *LoginServiceUpdateFriendGroupResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceUpdateFriendGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceUpdateFriendGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceUpdateFriendGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceUpdateFriendGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateFriendGroupResult(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateFriendGroupResult = map[int16]string{
	0: "success",
}

type LoginServiceDeleteFriendGroupArgs struct {
	Req *DeleteFriendGroupReq `thrift:"req,1" frugal:"1,default,DeleteFriendGroupReq" json:"req"`
}

func NewLoginServiceDeleteFriendGroupArgs() *LoginServiceDeleteFriendGroupArgs {
	return &LoginServiceDeleteFriendGroupArgs{}
}

func (p *LoginServiceDeleteFriendGroupArgs) InitDefault() {
}

var LoginServiceDeleteFriendGroupArgs_Req_DEFAULT *DeleteFriendGroupReq

func (p *LoginServiceDeleteFriendGroupArgs) GetReq() (v *DeleteFriendGroupReq) {
	if !p.IsSetReq() {
		return LoginServiceDeleteFriendGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceDeleteFriendGroupArgs) SetReq(val *DeleteFriendGroupReq) {
	p.Req = val
}

func (p *LoginServiceDeleteFriendGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceDeleteFriendGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceDeleteFriendGroupArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceDeleteFriendGroupArgs = map[int16]string{
	1: "req",
}

type LoginServiceDeleteFriendGroupResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceDeleteFriendGroupResult() *LoginServiceDeleteFriendGroupResult {
	return &LoginServiceDeleteFriendGroupResult{}
}

func (p *LoginServiceDeleteFriendGroupResult) InitDefault() {
}

var LoginServiceDeleteFriendGroupResult_Success_DEFAULT *CommonRes

func (p *LoginServiceDeleteFriendGroupResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceDeleteFriendGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceDeleteFriendGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceDeleteFriendGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceDeleteFriendGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceDeleteFriendGroupResult(%+v)", *p)
}

var fieldIDToName_LoginServiceDeleteFriendGroupResult = map[int16]string{
	0: "success",
}

type LoginServiceMoveFriendToGroupArgs struct {
	Req *MoveFriendToGroupReq `thrift:"req,1" frugal:"1,default,MoveFriendToGroupReq" json:"req"`
}

func NewLoginServiceMoveFriendToGroupArgs() *LoginServiceMoveFriendToGroupArgs {
	return &LoginServiceMoveFriendToGroupArgs{}
}

func (p *LoginServiceMoveFriendToGroupArgs) InitDefault() {
}

var LoginServiceMoveFriendToGroupArgs_Req_DEFAULT *MoveFriendToGroupReq

func (p *LoginServiceMoveFriendToGroupArgs) GetReq() (v *MoveFriendToGroupReq) {
	if !p.IsSetReq() {
		return LoginServiceMoveFriendToGroupArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceMoveFriendToGroupArgs) SetReq(val *MoveFriendToGroupReq) {
	p.Req = val
}

func (p *LoginServiceMoveFriendToGroupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceMoveFriendToGroupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceMoveFriendToGroupArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceMoveFriendToGroupArgs = map[int16]string{
	1: "req",
}

type LoginServiceMoveFriendToGroupResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceMoveFriendToGroupResult() *LoginServiceMoveFriendToGroupResult {
	return &LoginServiceMoveFriendToGroupResult{}
}

func (p *LoginServiceMoveFriendToGroupResult) InitDefault() {
}

var LoginServiceMoveFriendToGroupResult_Success_DEFAULT *CommonRes

func (p *LoginServiceMoveFriendToGroupResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceMoveFriendToGroupResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceMoveFriendToGroupResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceMoveFriendToGroupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceMoveFriendToGroupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceMoveFriendToGroupResult(%+v)", *p)
}

var fieldIDToName_LoginServiceMoveFriendToGroupResult = map[int16]string{
	0: "success",
}

type LoginServiceUpdateFriendRemarkArgs struct {
	Req *UpdateFriendRemarkReq `thrift:"req,1" frugal:"1,default,UpdateFriendRemarkReq" json:"req"`
}

func NewLoginServiceUpdateFriendRemarkArgs() *LoginServiceUpdateFriendRemarkArgs {
	return &LoginServiceUpdateFriendRemarkArgs{}
}

func (p *LoginServiceUpdateFriendRemarkArgs) InitDefault() {
}

var LoginServiceUpdateFriendRemarkArgs_Req_DEFAULT *UpdateFriendRemarkReq

func (p *LoginServiceUpdateFriendRemarkArgs) GetReq() (v *UpdateFriendRemarkReq) {
	if !p.IsSetReq() {
		return LoginServiceUpdateFriendRemarkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceUpdateFriendRemarkArgs) SetReq(val *UpdateFriendRemarkReq) {
	p.Req = val
}

func (p *LoginServiceUpdateFriendRemarkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceUpdateFriendRemarkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateFriendRemarkArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateFriendRemarkArgs = map[int16]string{
	1: "req",
}

type LoginServiceUpdateFriendRemarkResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceUpdateFriendRemarkResult() *LoginServiceUpdateFriendRemarkResult {
	return &LoginServiceUpdateFriendRemarkResult{}
}

func (p *LoginServiceUpdateFriendRemarkResult) InitDefault() {
}

var LoginServiceUpdateFriendRemarkResult_Success_DEFAULT *CommonRes

func (p *LoginServiceUpdateFriendRemarkResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceUpdateFriendRemarkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceUpdateFriendRemarkResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceUpdateFriendRemarkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceUpdateFriendRemarkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateFriendRemarkResult(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateFriendRemarkResult = map[int16]string{
	0: "success",
}

type LoginServiceGetFriendGroupsArgs struct {
	Req *GetFriendGroupsReq `thrift:"req,1" frugal:"1,default,GetFriendGroupsReq" json:"req"`
}

func NewLoginServiceGetFriendGroupsArgs() *LoginServiceGetFriendGroupsArgs {
	return &LoginServiceGetFriendGroupsArgs{}
}

func (p *LoginServiceGetFriendGroupsArgs) InitDefault() {
}

var LoginServiceGetFriendGroupsArgs_Req_DEFAULT *GetFriendGroupsReq

func (p *LoginServiceGetFriendGroupsArgs) GetReq() (v *GetFriendGroupsReq) {
	if !p.IsSetReq() {
		return LoginServiceGetFriendGroupsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceGetFriendGroupsArgs) SetReq(val *GetFriendGroupsReq) {
	p.Req = val
}

func (p *LoginServiceGetFriendGroupsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceGetFriendGroupsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetFriendGroupsArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceGetFriendGroupsArgs = map[int16]string{
	1: "req",
}

type LoginServiceGetFriendGroupsResult struct {
	Success *GetFriendGroupsRes `thrift:"success,0,optional" frugal:"0,optional,GetFriendGroupsRes" json:"success,omitempty"`
}

func NewLoginServiceGetFriendGroupsResult() *LoginServiceGetFriendGroupsResult {
	return &LoginServiceGetFriendGroupsResult{}
}

func (p *LoginServiceGetFriendGroupsResult) InitDefault() {
}

var LoginServiceGetFriendGroupsResult_Success_DEFAULT *GetFriendGroupsRes

func (p *LoginServiceGetFriendGroupsResult) GetSuccess() (v *GetFriendGroupsRes) {
	if !p.IsSetSuccess() {
		return LoginServiceGetFriendGroupsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceGetFriendGroupsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFriendGroupsRes)
}

func (p *LoginServiceGetFriendGroupsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceGetFriendGroupsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetFriendGroupsResult(%+v)", *p)
}

var fieldIDToName_LoginServiceGetFriendGroupsResult = map[int16]string{
	0: "success",
}

type LoginServiceSearchUserByAccountArgs struct {
	Req *SearchUserByAccountReq `thrift:"req,1" frugal:"1,default,SearchUserByAccountReq" json:"req"`
}

func NewLoginServiceSearchUserByAccountArgs() *LoginServiceSearchUserByAccountArgs {
	return &LoginServiceSearchUserByAccountArgs{}
}

func (p *LoginServiceSearchUserByAccountArgs) InitDefault() {
}

var LoginServiceSearchUserByAccountArgs_Req_DEFAULT *SearchUserByAccountReq

func (p *LoginServiceSearchUserByAccountArgs) GetReq() (v *SearchUserByAccountReq) {
	if !p.IsSetReq() {
		return LoginServiceSearchUserByAccountArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceSearchUserByAccountArgs) SetReq(val *SearchUserByAccountReq) {
	p.Req = val
}

func (p *LoginServiceSearchUserByAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceSearchUserByAccountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceSearchUserByAccountArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceSearchUserByAccountArgs = map[int16]string{
	1: "req",
}

type LoginServiceSearchUserByAccountResult struct {
	Success *SearchUserByAccountRes `thrift:"success,0,optional" frugal:"0,optional,SearchUserByAccountRes" json:"success,omitempty"`
}

func NewLoginServiceSearchUserByAccountResult() *LoginServiceSearchUserByAccountResult {
	return &LoginServiceSearchUserByAccountResult{}
}

func (p *LoginServiceSearchUserByAccountResult) InitDefault() {
}

var LoginServiceSearchUserByAccountResult_Success_DEFAULT *SearchUserByAccountRes

func (p *LoginServiceSearchUserByAccountResult) GetSuccess() (v *SearchUserByAccountRes) {
	if !p.IsSetSuccess() {
		return LoginServiceSearchUserByAccountResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceSearchUserByAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchUserByAccountRes)
}

func (p *LoginServiceSearchUserByAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceSearchUserByAccountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceSearchUserByAccountResult(%+v)", *p)
}

var fieldIDToName_LoginServiceSearchUserByAccountResult = map[int16]string{
	0: "success",
}

type LoginServiceGetUserNamesArgs struct {
	Req *GetUserNamesReq `thrift:"req,1" frugal:"1,default,GetUserNamesReq" json:"req"`
}

func NewLoginServiceGetUserNamesArgs() *LoginServiceGetUserNamesArgs {
	return &LoginServiceGetUserNamesArgs{}
}

func (p *LoginServiceGetUserNamesArgs) InitDefault() {
}

var LoginServiceGetUserNamesArgs_Req_DEFAULT *GetUserNamesReq

func (p *LoginServiceGetUserNamesArgs) GetReq() (v *GetUserNamesReq) {
	if !p.IsSetReq() {
		return LoginServiceGetUserNamesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceGetUserNamesArgs) SetReq(val *GetUserNamesReq) {
	p.Req = val
}

func (p *LoginServiceGetUserNamesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceGetUserNamesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetUserNamesArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceGetUserNamesArgs = map[int16]string{
	1: "req",
}

type LoginServiceGetUserNamesResult struct {
	Success *GetUserNamesRes `thrift:"success,0,optional" frugal:"0,optional,GetUserNamesRes" json:"success,omitempty"`
}

func NewLoginServiceGetUserNamesResult() *LoginServiceGetUserNamesResult {
	return &LoginServiceGetUserNamesResult{}
}

func (p *LoginServiceGetUserNamesResult) InitDefault() {
}

var LoginServiceGetUserNamesResult_Success_DEFAULT *GetUserNamesRes

func (p *LoginServiceGetUserNamesResult) GetSuccess() (v *GetUserNamesRes) {
	if !p.IsSetSuccess() {
		return LoginServiceGetUserNamesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceGetUserNamesResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserNamesRes)
}

func (p *LoginServiceGetUserNamesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceGetUserNamesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetUserNamesResult(%+v)", *p)
}

var fieldIDToName_LoginServiceGetUserNamesResult = map[int16]string{
	0: "success",
}

type LoginServiceGetUserIdsByAccountsArgs struct {
	Req *GetUserIdsByAccountsReq `thrift:"req,1" frugal:"1,default,GetUserIdsByAccountsReq" json:"req"`
}

func NewLoginServiceGetUserIdsByAccountsArgs() *LoginServiceGetUserIdsByAccountsArgs {
	return &LoginServiceGetUserIdsByAccountsArgs{}
}

func (p *LoginServiceGetUserIdsByAccountsArgs) InitDefault() {
}

var LoginServiceGetUserIdsByAccountsArgs_Req_DEFAULT *GetUserIdsByAccountsReq

func (p *LoginServiceGetUserIdsByAccountsArgs) GetReq() (v *GetUserIdsByAccountsReq) {
	if !p.IsSetReq() {
		return LoginServiceGetUserIdsByAccountsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceGetUserIdsByAccountsArgs) SetReq(val *GetUserIdsByAccountsReq) {
	p.Req = val
}

func (p *LoginServiceGetUserIdsByAccountsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceGetUserIdsByAccountsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetUserIdsByAccountsArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceGetUserIdsByAccountsArgs = map[int16]string{
	1: "req",
}

type LoginServiceGetUserIdsByAccountsResult struct {
	Success *GetUserIdsByAccountsRes `thrift:"success,0,optional" frugal:"0,optional,GetUserIdsByAccountsRes" json:"success,omitempty"`
}

func NewLoginServiceGetUserIdsByAccountsResult() *LoginServiceGetUserIdsByAccountsResult {
	return &LoginServiceGetUserIdsByAccountsResult{}
}

func (p *LoginServiceGetUserIdsByAccountsResult) InitDefault() {
}

var LoginServiceGetUserIdsByAccountsResult_Success_DEFAULT *GetUserIdsByAccountsRes

func (p *LoginServiceGetUserIdsByAccountsResult) GetSuccess() (v *GetUserIdsByAccountsRes) {
	if !p.IsSetSuccess() {
		return LoginServiceGetUserIdsByAccountsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceGetUserIdsByAccountsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserIdsByAccountsRes)
}

func (p *LoginServiceGetUserIdsByAccountsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceGetUserIdsByAccountsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetUserIdsByAccountsResult(%+v)", *p)
}

var fieldIDToName_LoginServiceGetUserIdsByAccountsResult = map[int16]string{
	0: "success",
}

type LoginServiceGetUsersInfoByAccountsArgs struct {
	Req *GetUsersInfoByAccountsReq `thrift:"req,1" frugal:"1,default,GetUsersInfoByAccountsReq" json:"req"`
}

func NewLoginServiceGetUsersInfoByAccountsArgs() *LoginServiceGetUsersInfoByAccountsArgs {
	return &LoginServiceGetUsersInfoByAccountsArgs{}
}

func (p *LoginServiceGetUsersInfoByAccountsArgs) InitDefault() {
}

var LoginServiceGetUsersInfoByAccountsArgs_Req_DEFAULT *GetUsersInfoByAccountsReq

func (p *LoginServiceGetUsersInfoByAccountsArgs) GetReq() (v *GetUsersInfoByAccountsReq) {
	if !p.IsSetReq() {
		return LoginServiceGetUsersInfoByAccountsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceGetUsersInfoByAccountsArgs) SetReq(val *GetUsersInfoByAccountsReq) {
	p.Req = val
}

func (p *LoginServiceGetUsersInfoByAccountsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceGetUsersInfoByAccountsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetUsersInfoByAccountsArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceGetUsersInfoByAccountsArgs = map[int16]string{
	1: "req",
}

type LoginServiceGetUsersInfoByAccountsResult struct {
	Success *GetUsersInfoByAccountsRes `thrift:"success,0,optional" frugal:"0,optional,GetUsersInfoByAccountsRes" json:"success,omitempty"`
}

func NewLoginServiceGetUsersInfoByAccountsResult() *LoginServiceGetUsersInfoByAccountsResult {
	return &LoginServiceGetUsersInfoByAccountsResult{}
}

func (p *LoginServiceGetUsersInfoByAccountsResult) InitDefault() {
}

var LoginServiceGetUsersInfoByAccountsResult_Success_DEFAULT *GetUsersInfoByAccountsRes

func (p *LoginServiceGetUsersInfoByAccountsResult) GetSuccess() (v *GetUsersInfoByAccountsRes) {
	if !p.IsSetSuccess() {
		return LoginServiceGetUsersInfoByAccountsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceGetUsersInfoByAccountsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUsersInfoByAccountsRes)
}

func (p *LoginServiceGetUsersInfoByAccountsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceGetUsersInfoByAccountsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceGetUsersInfoByAccountsResult(%+v)", *p)
}

var fieldIDToName_LoginServiceGetUsersInfoByAccountsResult = map[int16]string{
	0: "success",
}

type LoginServiceUpdateAvatarArgs struct {
	Req *UpdateAvatarReq `thrift:"req,1" frugal:"1,default,UpdateAvatarReq" json:"req"`
}

func NewLoginServiceUpdateAvatarArgs() *LoginServiceUpdateAvatarArgs {
	return &LoginServiceUpdateAvatarArgs{}
}

func (p *LoginServiceUpdateAvatarArgs) InitDefault() {
}

var LoginServiceUpdateAvatarArgs_Req_DEFAULT *UpdateAvatarReq

func (p *LoginServiceUpdateAvatarArgs) GetReq() (v *UpdateAvatarReq) {
	if !p.IsSetReq() {
		return LoginServiceUpdateAvatarArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceUpdateAvatarArgs) SetReq(val *UpdateAvatarReq) {
	p.Req = val
}

func (p *LoginServiceUpdateAvatarArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceUpdateAvatarArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateAvatarArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateAvatarArgs = map[int16]string{
	1: "req",
}

type LoginServiceUpdateAvatarResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceUpdateAvatarResult() *LoginServiceUpdateAvatarResult {
	return &LoginServiceUpdateAvatarResult{}
}

func (p *LoginServiceUpdateAvatarResult) InitDefault() {
}

var LoginServiceUpdateAvatarResult_Success_DEFAULT *CommonRes

func (p *LoginServiceUpdateAvatarResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceUpdateAvatarResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceUpdateAvatarResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceUpdateAvatarResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceUpdateAvatarResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateAvatarResult(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateAvatarResult = map[int16]string{
	0: "success",
}

type LoginServiceCreateBotUserArgs struct {
	Req *CreateBotUserReq `thrift:"req,1" frugal:"1,default,CreateBotUserReq" json:"req"`
}

func NewLoginServiceCreateBotUserArgs() *LoginServiceCreateBotUserArgs {
	return &LoginServiceCreateBotUserArgs{}
}

func (p *LoginServiceCreateBotUserArgs) InitDefault() {
}

var LoginServiceCreateBotUserArgs_Req_DEFAULT *CreateBotUserReq

func (p *LoginServiceCreateBotUserArgs) GetReq() (v *CreateBotUserReq) {
	if !p.IsSetReq() {
		return LoginServiceCreateBotUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceCreateBotUserArgs) SetReq(val *CreateBotUserReq) {
	p.Req = val
}

func (p *LoginServiceCreateBotUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceCreateBotUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCreateBotUserArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceCreateBotUserArgs = map[int16]string{
	1: "req",
}

type LoginServiceCreateBotUserResult struct {
	Success *CreateBotUserRes `thrift:"success,0,optional" frugal:"0,optional,CreateBotUserRes" json:"success,omitempty"`
}

func NewLoginServiceCreateBotUserResult() *LoginServiceCreateBotUserResult {
	return &LoginServiceCreateBotUserResult{}
}

func (p *LoginServiceCreateBotUserResult) InitDefault() {
}

var LoginServiceCreateBotUserResult_Success_DEFAULT *CreateBotUserRes

func (p *LoginServiceCreateBotUserResult) GetSuccess() (v *CreateBotUserRes) {
	if !p.IsSetSuccess() {
		return LoginServiceCreateBotUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceCreateBotUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateBotUserRes)
}

func (p *LoginServiceCreateBotUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceCreateBotUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceCreateBotUserResult(%+v)", *p)
}

var fieldIDToName_LoginServiceCreateBotUserResult = map[int16]string{
	0: "success",
}

type LoginServiceUpdateBotUserNameArgs struct {
	Req *UpdateBotUserNameReq `thrift:"req,1" frugal:"1,default,UpdateBotUserNameReq" json:"req"`
}

func NewLoginServiceUpdateBotUserNameArgs() *LoginServiceUpdateBotUserNameArgs {
	return &LoginServiceUpdateBotUserNameArgs{}
}

func (p *LoginServiceUpdateBotUserNameArgs) InitDefault() {
}

var LoginServiceUpdateBotUserNameArgs_Req_DEFAULT *UpdateBotUserNameReq

func (p *LoginServiceUpdateBotUserNameArgs) GetReq() (v *UpdateBotUserNameReq) {
	if !p.IsSetReq() {
		return LoginServiceUpdateBotUserNameArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LoginServiceUpdateBotUserNameArgs) SetReq(val *UpdateBotUserNameReq) {
	p.Req = val
}

func (p *LoginServiceUpdateBotUserNameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginServiceUpdateBotUserNameArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateBotUserNameArgs(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateBotUserNameArgs = map[int16]string{
	1: "req",
}

type LoginServiceUpdateBotUserNameResult struct {
	Success *CommonRes `thrift:"success,0,optional" frugal:"0,optional,CommonRes" json:"success,omitempty"`
}

func NewLoginServiceUpdateBotUserNameResult() *LoginServiceUpdateBotUserNameResult {
	return &LoginServiceUpdateBotUserNameResult{}
}

func (p *LoginServiceUpdateBotUserNameResult) InitDefault() {
}

var LoginServiceUpdateBotUserNameResult_Success_DEFAULT *CommonRes

func (p *LoginServiceUpdateBotUserNameResult) GetSuccess() (v *CommonRes) {
	if !p.IsSetSuccess() {
		return LoginServiceUpdateBotUserNameResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LoginServiceUpdateBotUserNameResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonRes)
}

func (p *LoginServiceUpdateBotUserNameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginServiceUpdateBotUserNameResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginServiceUpdateBotUserNameResult(%+v)", *p)
}

var fieldIDToName_LoginServiceUpdateBotUserNameResult = map[int16]string{
	0: "success",
}
