// Code generated by Kitex v0.16.2. DO NOT EDIT.

package knowledgeservice

import (
	"context"
	knowledge "github.com/Airiseina/answer/kitex_service/knowledge_service/kitex_gen/knowledge"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateKnowledgeBase(ctx context.Context, req *knowledge.CreateKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CreateKnowledgeBaseRes, err error)
	GetKnowledgeBase(ctx context.Context, req *knowledge.GetKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.GetKnowledgeBaseRes, err error)
	GetUserKnowledgeBases(ctx context.Context, req *knowledge.GetUserKnowledgeBasesReq, callOptions ...callopt.Option) (r *knowledge.GetUserKnowledgeBasesRes, err error)
	UpdateKnowledgeBase(ctx context.Context, req *knowledge.UpdateKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	DeleteKnowledgeBase(ctx context.Context, req *knowledge.DeleteKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	AddDocument(ctx context.Context, req *knowledge.AddDocumentReq, callOptions ...callopt.Option) (r *knowledge.AddDocumentRes, err error)
	GetDocuments(ctx context.Context, req *knowledge.GetDocumentsReq, callOptions ...callopt.Option) (r *knowledge.GetDocumentsRes, err error)
	DeleteDocument(ctx context.Context, req *knowledge.DeleteDocumentReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	RetryDocument(ctx context.Context, req *knowledge.RetryDocumentReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	BindKnowledgeBase(ctx context.Context, req *knowledge.BindKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	UnbindKnowledgeBase(ctx context.Context, req *knowledge.UnbindKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	GetBotKnowledgeBases(ctx context.Context, req *knowledge.GetBotKnowledgeBasesReq, callOptions ...callopt.Option) (r *knowledge.GetBotKnowledgeBasesRes, err error)
	SearchKnowledge(ctx context.Context, req *knowledge.SearchKnowledgeReq, callOptions ...callopt.Option) (r *knowledge.SearchKnowledgeRes, err error)
	BindSystemKnowledgeBase(ctx context.Context, req *knowledge.BindSystemKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error)
	AddSystemDocument(ctx context.Context, req *knowledge.AddSystemDocumentReq, callOptions ...callopt.Option) (r *knowledge.AddDocumentRes, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kKnowledgeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kKnowledgeServiceClient struct {
	*kClient
}

func (p *kKnowledgeServiceClient) CreateKnowledgeBase(ctx context.Context, req *knowledge.CreateKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CreateKnowledgeBaseRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) GetKnowledgeBase(ctx context.Context, req *knowledge.GetKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.GetKnowledgeBaseRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) GetUserKnowledgeBases(ctx context.Context, req *knowledge.GetUserKnowledgeBasesReq, callOptions ...callopt.Option) (r *knowledge.GetUserKnowledgeBasesRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserKnowledgeBases(ctx, req)
}

func (p *kKnowledgeServiceClient) UpdateKnowledgeBase(ctx context.Context, req *knowledge.UpdateKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) DeleteKnowledgeBase(ctx context.Context, req *knowledge.DeleteKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) AddDocument(ctx context.Context, req *knowledge.AddDocumentReq, callOptions ...callopt.Option) (r *knowledge.AddDocumentRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddDocument(ctx, req)
}

func (p *kKnowledgeServiceClient) GetDocuments(ctx context.Context, req *knowledge.GetDocumentsReq, callOptions ...callopt.Option) (r *knowledge.GetDocumentsRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDocuments(ctx, req)
}

func (p *kKnowledgeServiceClient) DeleteDocument(ctx context.Context, req *knowledge.DeleteDocumentReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDocument(ctx, req)
}

func (p *kKnowledgeServiceClient) RetryDocument(ctx context.Context, req *knowledge.RetryDocumentReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RetryDocument(ctx, req)
}

func (p *kKnowledgeServiceClient) BindKnowledgeBase(ctx context.Context, req *knowledge.BindKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) UnbindKnowledgeBase(ctx context.Context, req *knowledge.UnbindKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbindKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) GetBotKnowledgeBases(ctx context.Context, req *knowledge.GetBotKnowledgeBasesReq, callOptions ...callopt.Option) (r *knowledge.GetBotKnowledgeBasesRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBotKnowledgeBases(ctx, req)
}

func (p *kKnowledgeServiceClient) SearchKnowledge(ctx context.Context, req *knowledge.SearchKnowledgeReq, callOptions ...callopt.Option) (r *knowledge.SearchKnowledgeRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchKnowledge(ctx, req)
}

func (p *kKnowledgeServiceClient) BindSystemKnowledgeBase(ctx context.Context, req *knowledge.BindSystemKnowledgeBaseReq, callOptions ...callopt.Option) (r *knowledge.CommonRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindSystemKnowledgeBase(ctx, req)
}

func (p *kKnowledgeServiceClient) AddSystemDocument(ctx context.Context, req *knowledge.AddSystemDocumentReq, callOptions ...callopt.Option) (r *knowledge.AddDocumentRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddSystemDocument(ctx, req)
}
